In [1]:
'''import os
import sys
from pathlib import Path
sys.path.append(os.path.abspath('..'))  # Ensures the project root is in Python's search path

if Path("/kaggle").exists():
    
    # Create directory structure
    !mkdir -p corrosion_scoring_v3
    
    # Download the necessary files each session always
    !wget -O corrosion_scoring_v3/__init__.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/__init__.py
    !wget -O corrosion_scoring_v3/global_terms.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/global_terms.py
    !wget -O corrosion_scoring_v3/scoring_system.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3scoring_system.py
    !wget -O corrosion_scoring_v3/term_processor.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/term_processor.py
    # Add current directory to path
    import sys
    sys.path.append(os.getcwd())
    
else:
    print("Running in local (VSCode) environment")
    
    ## When in vscode local env first time only
    #!{sys.executable} -m pip uninstall -y corrosion_scoring !{sys.executable} -m pip cache purge !{sys.executable} -m pip install --no-cache-dir --force-reinstall "git+https://github.com/MagicAlex238/2_Micro.git@main#subdirectory=corrosion_scoring_root"
    !pip uninstall -y corrosion_scoring || true pip cache purge
    !pip install git+https://github.com/MagicAlex238/2_Micro.git@main#subdirectory=corrosion_scoring_root
   
import corrosion_scoring_v3 as cs
from corrosion_scoring_v3.term_processor import TermProcessor
from corrosion_scoring_v3.name_utils import enhanced_clean_protein_name, clean_protein_name
from corrosion_scoring_v3.utils_ec import normalize_ec_id, strip_all_ec_tokens
from corrosion_scoring_v3.validators import ValidationError
from corrosion_scoring_v3.exceptions import ScoringError, TextMiningError, SynergyDetectionError
from corrosion_scoring_v3.global_terms import metal_terms_dict, functional_categories_dict, corrosion_synergies_dict, mechanisms_dict, pathway_dict, operational_environmental_factors_dict

# create processors (use cs.<name> for consistency)
fc_processor = TermProcessor(cs.functional_categories_dict)
metal_processor = TermProcessor(cs.metal_terms_dict)
synergy_processor = TermProcessor(cs.corrosion_synergies_dict)
mechanisms_processor = TermProcessor(cs.mechanisms_dict)
pathway_processor = TermProcessor(cs.pathway_dict)
ope_processor = TermProcessor(cs.operational_environmental_factors_dict)

processors =   { 'fc_processor': fc_processor,
    'metal_processor': metal_processor,
    'synergy_processor': synergy_processor
}
# Initialize v3 components with existing processors
config = cs.ScoringConfig()

text_miner = cs.TextMiner(config)
if 'processors' in globals():
    text_miner.processors = processors

score_calculator = cs.ScoreCalculator(config)
synergy_detector = cs.SynergyDetector(config)'''

'import os\nimport sys\nfrom pathlib import Path\nsys.path.append(os.path.abspath(\'..\'))  # Ensures the project root is in Python\'s search path\n\nif Path("/kaggle").exists():\n    \n    # Create directory structure\n    !mkdir -p corrosion_scoring_v3\n    \n    # Download the necessary files each session always\n    !wget -O corrosion_scoring_v3/__init__.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/__init__.py\n    !wget -O corrosion_scoring_v3/global_terms.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/global_terms.py\n    !wget -O corrosion_scoring_v3/scoring_system.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3scoring_system.py\n    !wget -O corrosion_scoring_v3/term_processor.py https://raw.githubusercontent.com/MagicAlex238/2_Micro/main/corrosion_scoring_root/corrosion_scoring_v3/term_processor.py\n    # Add current directory to path\n    import sys\n    sys.path.append(os.getcwd())\n    \nelse:\n    print("Running in local (VSCode) environment")\n    \n    ## When in vscode local env first time only\n    #!{sys.executable} -m pip uninstall -y corrosion_scoring !{sys.executable} -m pip cache purge !{sys.executable} -m pip install --no-cache-dir --force-reinstall "git+https://github.com/MagicAlex238/2_Micro.git@main#subdirectory=corrosion_scoring_root"\n    !pip uninstall -y corrosion_scoring || true pip cache purge\n    !pip install git+https://github.com/MagicAlex238/2_Micro.git@main#subdirectory=corrosion_scoring_root\n   \nimport corrosion_scoring_v3 as cs\nfrom corrosion_scoring_v3.term_processor import TermProcessor\nfrom corrosion_scoring_v3.name_utils import enhanced_clean_protein_name, clean_protein_name\nfrom corrosion_scoring_v3.utils_ec import normalize_ec_id, strip_all_ec_tokens\nfrom corrosion_scoring_v3.validators import ValidationError\nfrom corrosion_scoring_v3.exceptions import ScoringError, TextMiningError, SynergyDetectionError\nfrom corrosion_scoring_v3.global_terms import metal_terms_dict, functional_categories_dict, corrosion_synergies_dict, mechanisms_dict, pathway_dict, operational_environmental_factors_dict\n\n# create processors (use cs.<name> for consistency)\nfc_processor = TermProcessor(cs.functional_categories_dict)\nmetal_processor = TermProcessor(cs.metal_terms_dict)\nsynergy_processor = TermProcessor(cs.corrosion_synergies_dict)\nmechanisms_processor = TermProcessor(cs.mechanisms_dict)\npathway_processor = TermProcessor(cs.pathway_dict)\nope_processor = TermProcessor(cs.operational_environmental_factors_dict)\n\nprocessors =   { \'fc_processor\': fc_processor,\n    \'metal_processor\': metal_processor,\n    \'synergy_processor\': synergy_processor\n}\n# Initialize v3 components with existing processors\nconfig = cs.ScoringConfig()\n\ntext_miner = cs.TextMiner(config)\nif \'processors\' in globals():\n    text_miner.processors = processors\n\nscore_calculator = cs.ScoreCalculator(config)\nsynergy_detector = cs.SynergyDetector(config)'

_________________________
## importing scoring system
___________________________

In [1]:
import os, sys
REPO_ROOT = os.path.abspath(os.path.join(os.getcwd()))
if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)
sys.path.append(os.path.abspath('..'))
REPO_ROOT = "/home/beatriz/MIC/2_Micro/corrosion_scoring_root"
sys.path.insert(0, '/home/beatriz/MIC/2_Micro/corrosion_scoring_root')
import corrosion_scoring_v3 as cs
from corrosion_scoring_v3.term_processor import TermProcessor
from corrosion_scoring_v3.name_utils import enhanced_clean_protein_name, clean_protein_name
from corrosion_scoring_v3.utils_ec import normalize_ec_id, strip_all_ec_tokens
from corrosion_scoring_v3.validators import ValidationError
from corrosion_scoring_v3.exceptions import ScoringError, TextMiningError, SynergyDetectionError
from corrosion_scoring_v3.global_terms import metal_terms_dict, functional_categories_dict, corrosion_synergies_dict, mechanisms_dict, pathway_dict, operational_environmental_factors_dict

# create processors (use cs.<name> for consistency)
fc_processor = TermProcessor(cs.functional_categories_dict)
metal_processor = TermProcessor(cs.metal_terms_dict)
synergy_processor = TermProcessor(cs.corrosion_synergies_dict)
mechanisms_processor = TermProcessor(cs.mechanisms_dict)
pathway_processor = TermProcessor(cs.pathway_dict)
ope_processor = TermProcessor(cs.operational_environmental_factors_dict)

processors =   { 'fc_processor': fc_processor,
    'metal_processor': metal_processor,
    'synergy_processor': synergy_processor
}
# Initialize v3 components with existing processors
config = cs.ScoringConfig()

text_miner = cs.TextMiner(config)
if 'processors' in globals():
    text_miner.processors = processors

score_calculator = cs.ScoreCalculator(config)
synergy_detector = cs.SynergyDetector(config)

__________________
## Libraries Imports
_______________

In [2]:
# Standard library imports
import sys
import os
from pathlib import Path
import ast
import subprocess
import logging
import time
from datetime import datetime
import shutil
from io import StringIO
import psutil
import re
from IPython import get_ipython
from IPython.display import display

# Data processing and analysis
import pandas as pd
import numpy as np
import openpyxl
import seaborn as sns
import networkx as nx
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import plotly.io as pio
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.cm as cm
%matplotlib inline
from matplotlib.colors import to_rgba, LinearSegmentedColormap
import matplotlib.patches as mpatches
from collections import defaultdict
from collections import Counter 
from itertools import chain
from lxml import etree

# Machine learning and statistical analysis
from sklearn.preprocessing import StandardScaler, RobustScaler, MinMaxScaler
from sklearn.decomposition import PCA, NMF
from sklearn.cluster import AgglomerativeClustering, KMeans
from scipy.cluster import hierarchy
from sklearn.manifold import TSNE
import umap
import scipy
from scipy import stats
from scipy.cluster.hierarchy import linkage, dendrogram
import scipy.cluster.hierarchy as sch
from statsmodels.stats.multitest import multipletests
from scipy.spatial.distance import pdist
from scipy.stats import spearmanr, kruskal, mannwhitneyu
from kneed import KneeLocator
from scipy.signal import savgol_filter
from community import community_louvain
from joblib import Parallel, delayed

# Bioinformatics
from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord
from biom import Table, load_table
from biom.util import biom_open
import xml.etree.ElementTree as ET

# Utility libraries
import gzip
import random
from natsort import natsorted
from typing import Dict, List, Tuple, Set, Optional, Iterable, Union
import pickle
import gc
import joblib
import h5py
import os
import csv
import json
import pyarrow.parquet as pq
from collections import defaultdict
import warnings
import logging
# Set up logging
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

os.environ['DISPLAY'] = ':0'

____________________
## Paths
_______________

In [3]:
# Initial environment detection and package installation
is_colab = "google.colab" in sys.modules
is_kaggle = Path("/kaggle").exists()
is_vscode = not (is_colab or is_kaggle)

if is_colab:
    print("Running in Google Colab environment")
    %pip install psutil, biopython, biom-format, umap-learn, fuzzywuzzy, lxml pandas, pyarrow, openpyxl, scipy, python-Levenshtein, -U kaleido, statsmodels, kneed, natsort, adjustText
    from google.colab import drive
    drive.mount('/content/drive')
    base_dir  = Path("/content/drive/My Drive")
    os.chdir(base_dir) # Change directory to base_dir
    # Directory to output large files # eccontris, compilated db
    large_dir = base_dir / "MIC"
    data_ref = large_dir / "2_Micro/data_ref" #input dir 
    data_qiime = large_dir / "2_Micro/data_qiime" #input dir 
    data_picrust = large_dir/ "2_Micro/data_picrust" #main output dir
    data_picrust.mkdir(parents=True, exist_ok=True) 
    
elif is_kaggle:
    print("Running in Kaggle environment")
    !pip install psutil, biopython, biom-format, umap-learn, fuzzywuzzy, lxml pandas, pyarrow, openpyxl, scipy, python-Levenshtein, -U kaleido, statsmodels, kneed, natsort, adjustText
    base_dir  = Path("/kaggle/input") 
    data_Ref  = base_dir / "place dataref" # revisit in kaggle "2_Micro/data_ref" #input dir
    data_qiime  = base_dir / "crust" #  needs revisiting
    # Directory to output large files # eccontris, compilated db
    large_dir =  Path("/kaggle/working/")  
    data_picrust = large_dir / "data_picrust" # directory assignment no creation
 
else:
    print("Running in VSCode/local environment")
    base_dir = Path("/home/beatriz")
    large_dir  = base_dir /"MIC"  
    data_qiime = large_dir / "2_Micro" / "data_qiime"  # this already come from former notebook and it is not to make
    data_Ref  = large_dir /  "2_Micro" / "data_Ref" # this already come from former notebook and it is not to make
    data_picrust  = large_dir / "2_Micro" / "data_picrust" 
    data_picrust.mkdir(parents=True, exist_ok=True)
    

output_dir = data_picrust
#datasets large galaxies and databases
input_galaxy = large_dir  / "data_galaxies"
db_dir = large_dir / "Databases"
newick_path = input_galaxy / "Galaxy7-PICRUSt2-Full-pipeline-on-data-2-and-data-1-Tree-reference-study-16S-sequences.newick" 
# Directory to output large files # eccontris, compilated db
output_large = large_dir / "output_large"
output_large.mkdir(parents=True, exist_ok=True)

abundance_excel= data_Ref / "merged_to_sequence.xlsx" #C:\home\beatriz\MIC\2_Micro\data_Ref\merged_to_sequence.xlsx
fasta_file_final = data_qiime / "results_match_gg/final_sequences_gg.fasta"
aligned_fasta = data_qiime / "results_match_gg/aligned-dna-sequences_gg.fasta"
# Create output directory if it doesn't exist
output_base = output_dir / "output_base" # directory4
output_base.mkdir(parents=True, exist_ok=True)
# Print the paths for verification
print(f"Using base_dir: {base_dir}")
print(f"Using abundance_excel: {abundance_excel}")
print(f"Using fasta_file_final: {fasta_file_final}")
print(f"Using output_base: {output_base}")
print(f"Using large_dir: {large_dir}")
print(f"Using db_dir: {db_dir}")
print(f"Using input_galaxy: {input_galaxy}")
print(f"Using output_large: {output_large}")

Running in VSCode/local environment
Using base_dir: /home/beatriz
Using abundance_excel: /home/beatriz/MIC/2_Micro/data_Ref/merged_to_sequence.xlsx
Using fasta_file_final: /home/beatriz/MIC/2_Micro/data_qiime/results_match_gg/final_sequences_gg.fasta
Using output_base: /home/beatriz/MIC/2_Micro/data_picrust/output_base
Using large_dir: /home/beatriz/MIC
Using db_dir: /home/beatriz/MIC/Databases
Using input_galaxy: /home/beatriz/MIC/data_galaxies
Using output_large: /home/beatriz/MIC/output_large

In [4]:
# Integrated taxa from origin genus as headers with levels 6 for the genera, 7 for the GID, muss be cleaned
Integrated_T = pd.read_excel(abundance_excel, sheet_name='core_check_usual_taxa', header=[0,1,2,3,4,5,6,7], engine ='openpyxl')
# Drop first row (index 0) and first column in one chain
Integrated_T = Integrated_T.drop(index=0).drop(Integrated_T.columns[0], axis=1)
Integrated_T= Integrated_T.astype({'Sites': str})
Integrated_T['Sites'] = Integrated_T['Sites'].fillna('Source')
# Remove 'Unnamed' level names
Integrated_T.columns = Integrated_T.columns.map(lambda x: tuple('' if 'Unnamed' in str(level) else level for level in x))
# Changing dtypes to category whiles respecting structure
Integrated_T["Category"] = Integrated_T["Category"].astype("Int64")
Integrated_T= Integrated_T.set_index("Sites")
pre_Integrated = Integrated_T.T

In [5]:
#temporal function
def notify_complete():
   
    # Visual notification
    print(f"\n🔔 TASK FINISHED at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')} 🔔")
    
    # Try audio methods (no installation required)
    try:
        # Method 1: PowerShell (Windows/WSL)
        os.system('powershell.exe -c "[console]::beep(4800,8800)"')
    except:
        try:
            # Method 2: Terminal bell
            print('\a\a\a')
            print('\a\a\a')
            print('\a\a\a')
            sys.stdout.flush()
        except:
            # Method 3: Just visual
            print("🚨🚨🚨 DONE 🚨🚨🚨")

____________
## Databases Paths
___________

In [7]:
def setup_paths() -> Dict[str, Path]:
    """Set up paths for database access"""

    # Database paths
    db_paths = {
        'enzyme': db_dir / 'enzyme',
        'enzyme_class': db_dir / 'enzclass.txt',
        'enzyme_brenda' : db_dir/ 'brenda_2024.txt',
        'ko': db_dir / 'kegg_ko.txt',
        'ko_hierarchy': db_dir / 'ko_hierarchy.txt',
        'ko_brite': db_dir / 'ko00001.keg',
        'pathway': db_dir / 'pathway',
        'module': db_dir / 'module',
        'reaction': db_dir / 'reaction',
        'compound': db_dir / 'compound',
        'metalpdb': db_dir / 'flat_db_file.xml', #MetalPDB
        'ko_pathway': db_dir / 'ec_pathway.list' #Mapping between EC numbers and KEGG pathway IDs
    }

    return db_paths

#  Calling the paths
if __name__ == "__main__":
    paths = setup_paths()
    # Print paths to verify
    for db_name, path in paths.items():
        print(f"{db_name}: {path}")
        print(f"Exists: {path.exists()}")

enzyme: /home/beatriz/MIC/Databases/enzyme
Exists: True
enzyme_class: /home/beatriz/MIC/Databases/enzclass.txt
Exists: True
enzyme_brenda: /home/beatriz/MIC/Databases/brenda_2024.txt
Exists: True
ko: /home/beatriz/MIC/Databases/kegg_ko.txt
Exists: True
ko_hierarchy: /home/beatriz/MIC/Databases/ko_hierarchy.txt
Exists: True
ko_brite: /home/beatriz/MIC/Databases/ko00001.keg
Exists: True
pathway: /home/beatriz/MIC/Databases/pathway
Exists: True
module: /home/beatriz/MIC/Databases/module
Exists: True
reaction: /home/beatriz/MIC/Databases/reaction
Exists: True
compound: /home/beatriz/MIC/Databases/compound
Exists: True
metalpdb: /home/beatriz/MIC/Databases/flat_db_file.xml
Exists: True
ko_pathway: /home/beatriz/MIC/Databases/ec_pathway.list
Exists: True

___________
## Brenda Parser
_______________

In [8]:
logger = logging.getLogger(__name__)

# =========================
# Tag parsing & utilities
# =========================

# Accept either:
#   TAG value
# or
#   LONG_SECTION SHORT_TAG value
TAG_LINE_RE = re.compile(r'^([A-Z_]{2,30})(?:\s+([A-Z]{2,10}))?\s+(.*)$')
INDEX_PREFIX_RE = re.compile(r'^#(\d+(?:,\d+)*)#\s*')      # "#1,4,7# text ..."
CITATION_HASH_RE = re.compile(r'#\s*\d+(?:\s*,\s*\d+)*#?')          # "#1#" or "#1,2,3#" "#1,2,3#" and "#1,2,3".
CITATION_ANGLE_RE = re.compile(r'<[^>]*>')                 # "<44>"
WS_RE = re.compile(r'\s+')
MECH_RE = re.compile(r'\bmechanism\b', re.IGNORECASE)
_COFACTOR_LEXICON = ('NADPH', 'NADP+', 'NADP', 'NADH', 'NAD+', 'NAD','FAD', 'FMN', 'HEME', 'BIOTIN', 'SAM', 'TPP', 'PLP', 'THF', 'COA')

# Long section names to short tags
LONG_TO_SHORT = {
    'RECOMMENDED_NAME': 'RN',
    'SYSTEMATIC_NAME': 'SN',
    'SYNONYMS': 'SY',
    'COFACTOR': 'CF',
    'ACTIVATING_COMPOUND': 'AC',
    'INHIBITORS': 'IN',
    'METALS_IONS': 'ME',
    'SUBSTRATE_PRODUCT': 'SP',
    'NATURAL_SUBSTRATE_PRODUCT': 'NSP',
    'GENERAL_INFORMATION': 'GI',
    'GENERAL_STABILITY': 'GS',
    'STORAGE_STABILITY': 'SS',
    'OXIDATION_STABILITY': 'OS',
    'PH_OPTIMUM': 'PO',
    'PH_STABILITY': 'PS',
    'PH_RANGE': 'PHR',
    'TEMPERATURE_OPTIMUM': 'TO',
    'TEMPERATURE_STABILITY': 'TS',
    'TEMPERATURE_RANGE': 'TR',
    'ORGANIC_SOLVENT_STABILITY': 'OSS',
    'IONIC_STRENGTH': 'IS',
    'PROTEIN_MODIFICATIONS': 'PM',
    'POSTTRANSLATIONAL_MODIFICATION': 'PM',
    'PROTEIN': 'PR',
    'CLONED': 'CL',
    'EXPRESSION': 'EXP',  # ignored
    # Intentionally NOT mapping REFERENCE/REACTION/MW/PI/AP/EN/CR/LO/ST/KM/SA/PU here (ignored)
}

# Short tags we accept from the file
VALID_SHORT_TAGS = {
    'ID', 'PR', 'RN', 'SN',
    'SY',
    'CF', 'AC',
    'ME', 'SP', 'NSP', 'IN',
    'GI', 'GS', 'SS', 'OS', 'PO', 'PS', 'PHO', 'PHS', 'PHR',
    'TO', 'TS', 'TR', 'OSS', 'IS',
    'PM',
    'CL',
    'EXP',
    # tolerated but ignored:
    'RE', 'RF', 'MW', 'PI', 'AP', 'EN', 'CR', 'LO', 'ST', 'KM', 'SA', 'PU', 'RT', 'BR'
}

# Safe aliases (do NOT alias REN→RN to avoid name pollution)
SHORT_TAG_ALIAS = {
    'PHO': 'PO',
    'PHS': 'PS',
}

# Kept environmental tags (captured for later; not used in current scoring)
ENV_TAGS = {'OS', 'GS', 'SS', 'PO', 'PS', 'PHR', 'TO', 'TS', 'TR', 'OSS', 'IS'}

EC_CLASS_MAP = {
    '1': 'oxidoreductases',
    '2': 'transferases',
    '3': 'hydrolases',
    '4': 'lyases',
    '5': 'isomerases',
    '6': 'ligases',
    '7': 'translocases',
}

def enzyme_class_from_ec(ec: str) -> str:
    if not ec:
        return ""
    return EC_CLASS_MAP.get(ec.split('.', 1)[0], "")

def brenda_sanitize_text(text: str) -> str:
    if not isinstance(text, str):
        if isinstance(text, (list, tuple)):
            text = ' '.join(map(str, text))
        else:
            text = '' if text is None else str(text)

    t = CITATION_HASH_RE.sub('', text)       # "#1,2#"
    t = CITATION_ANGLE_RE.sub('', t)         # "<44>"
    t = re.sub(r'\{[^}]*\}', '', t)          # "{r}" blocks
   # Check for chemistry tags and handle parentheses accordingly
    chemistry_tags = ['CF', 'ME', 'SP', 'NSP', 'RE']
    has_chemistry_tags = any(tag in t for tag in chemistry_tags)

    if has_chemistry_tags:
        # For chemistry tags: replace parentheses with spaces
        t = re.sub(r'[()]', ' ', t)
    else:
        # For non-chemistry tags: remove parentheses and their contents entirely
        t = re.sub(r'\([^)]*\)', '', t)
    t = WS_RE.sub(' ', t).strip()
    t = re.sub(r'^\s*[,;]?\s*\d[\d,\s]*\s*', '', t)  # leading enumerations

    # strip trailing section ghost labels
    t = re.sub(
        r'\s+(?:METALS_IONS|PH_RANGE|INHIBITORS|SUBSTRATE_PRODUCT|NATURAL_SUBSTRATE_PRODUCT|'
        r'PH_OPTIMUM|PH_STABILITY|TEMPERATURE_OPTIMUM|TEMPERATURE_STABILITY|SPECIFIC_ACTIVITY|'
        r'SUBUNITS|MOLECULAR_WEIGHT)\s*$',
        '', t
    )
    t = re.sub(r'\s*[:;,\-–]\s*$', '', t)
    assert isinstance(t, str), f"sanitize produced non-str: {type(t)}"
    return t

def is_valid_text(text):
    if not text or len(text) < 10:
        return False
    if '...' in text or '?' in text:
        return False
    if text.lower() in ('unknown', 'n/a', 'none'):
        return False
    return True

def is_valid_equation(eq: str) -> bool:
    # Basic filter for chemical equations
    if not eq or len(eq) < 10:
        return False
    if eq.startswith('+') or '...' in eq or eq.count('=') > 1:
        return False
    if not any(token in eq for token in ['+', '=', '→', '⇌']):
        return False
    return True

def extract_indices_and_value(value: str) -> Tuple[Optional[List[str]], str]:
    """Extract leading #idx[,idx]#; return (indices, rest)."""
    if not value:
        return None, ""
    m = INDEX_PREFIX_RE.match(value)
    if not m:
        return None, value.strip()
    idxs = m.group(1).split(',')
    rest = value[m.end():].strip()
    return idxs, rest

def extract_genus(species: str) -> str:
    """Return genus from species name; handle 'Candidatus X ...'."""
    if not species:
        return ""
    tokens = species.strip().split()
    if not tokens:
        return ""
    if tokens[0].lower() == 'candidatus' and len(tokens) > 1:
        return tokens[1]
    return tokens[0]

def contains_mechanism(text: str) -> bool:
    return bool(text and MECH_RE.search(text))

def mechanism_snippet(text: str) -> str:
    if not text:
        return ""
    m = MECH_RE.search(text)
    return text[m.start():].strip() if m else text.strip()

def _is_gene_token(tok: str) -> bool:
    if not tok:
        return False
    t = tok.strip().strip('.,;:()[]{}').replace('"','').replace("'",'')
    # Reject obvious non-genes (add/remove terms as needed)
    BAD = {'gene', 'locus', 'tag', 'orf', 'protein', 'domain', 'subunit', 'fragment', 'hypothetical', 'functional', 'cluster'}
    if t.lower() in BAD:
        return False
    # Typical gene tokens: short alnum with optional mixed case, underscores or dashes
    if not re.match(r'^[A-Za-z][A-Za-z0-9._-]{1,10}$', t):
        return False
    return True

# Conservative gene capture patterns from CL (cloned) lines
CL_GENE_PATTERNS = [
    re.compile(r'\bgene\s+([A-Za-z0-9_\-\.]{2,20})', re.IGNORECASE),
    re.compile(r'\b([A-Za-z0-9_\-\.]{2,20})\s+gene\b', re.IGNORECASE),
    re.compile(r'\blocus\s+tag\s+([A-Za-z0-9_\-\.]{2,20})', re.IGNORECASE),
    re.compile(r'\b(ORF[A-Za-z0-9_\-\.]{1,19})\b', re.IGNORECASE)]

# =========================
# Parser
# =========================

def parse_brenda_file() -> Dict[str, dict]:
    """
    Trimmed BRENDA parser (concise, no bloat):
    - protein_name: RN (fallback SN). No REN aliasing.
    - organisms: PR indices -> {species, genus}
    - by_genus routing via indices for SP/NSP, IN, ME, CF, AC, GI(mechanism)
    - corrosion_mechanisms: from GI 'mechanism...' snippets ONLY (no physiological_functions)
    - operational_environmental_factors: OS/GS/SS/PO/PS/PHR/TO/TS/TR/OSS/IS (captured for later; not used here)
    - gene_name: from SY "(gene name ...)" AND enriched from CL lines (without retaining cloning_info)
    - Ignored entirely: reactions (RE), references (RF), applications (AP), engineering (EN),
      structural info (CR/LO/ST/SU), biochemical kinetics/properties (KM/SA/MW/PI),
      purification info (PU), expression (EXP)
    """
    # parse_1 Resolve paths 
    paths = setup_paths()  # must return {'enzyme_brenda': path}
    enzyme_brenda_path = paths['enzyme_brenda']

    if not os.path.exists(enzyme_brenda_path):
        logger.error("BRENDA file not found at path: %s", enzyme_brenda_path)
        return {}

    ec_info: Dict[str, dict] = {}
    current_ec: Optional[str] = None
    in_entry = False

    # parse_2 Continuations
    last_tag: Optional[str] = None
    last_ec_field_list_name: Optional[str] = None
    last_by_genus_targets: Optional[List[str]] = None

    # parse_3 GI buffering
    gi_buffer_text: Optional[str] = None
    gi_buffer_genera: Optional[List[str]] = None

    kept, skipped = 0, 0
    missing_headers = set()
    # parse_4 Helper functions ensure_ec, append_ec_list, append_by_genus, indices_to_genera, flush_gi_buffer
    ###############
    DEFAULT_GENUS_FIELDS = ('substrates','inhibitors','metals','cofactors','activators',
                            'corrosion_mechanisms','reaction_equation','operational_environmental_factors','gene_names')
    def _make_genus_bucket():
        '''Avoids repeating same dict construction'''
        return {k: [] for k in DEFAULT_GENUS_FIELDS}

    def ensure_ec(ec: str):
        if ec not in ec_info:
            ec_info[ec] = {
                'ec_number': ec,
                'protein_name': "",
                'enzyme_class': enzyme_class_from_ec(ec),

                # Core lists kept
                'substrates': [],
                'inhibitors': [],
                'metals': [],
                'cofactors': [],
                'compounds': [],
                'activators': [],
                'corrosion_mechanisms': [],
                'reaction_equation': [],  # from RE lines only
                'operational_environmental_factors': [],
                'brenda_metals': [],
                '_metal_text': [],
                '_mech_text': [], 
                # Gene aggregation
                'gene_name': [],
                # Organisms and per-genus routing
                'organisms': {},  # idx -> {'species','genus'}
                'by_genus': defaultdict(_make_genus_bucket),
            }
    _METAL_PATTERNS = [(re.compile(rf'(?<![A-Za-z0-9]){re.escape(k)}(?![A-Za-z0-9])'), v)
                        for k, v in cs.metal_mapping.items()]
    # parse_5 append_ec_list, append_by_genus, indices_to_genera, flush_gi_buffer
    ###############
    def append_ec_list(ec: str, field: str, value: str):
        if not value:
            return
        v = brenda_sanitize_text(value)
        if not v:
            return
        # Make this resilient: create the list if it doesn't exist
        if field not in ec_info[ec]:
            ec_info[ec][field] = []
        lst = ec_info[ec][field]
        if v not in lst:
            lst.append(v)
    # parse_6 append by genus
    def append_by_genus(ec: str, genera: List[str], field: str, value: str):
        if not value or not genera:
            return
        v = brenda_sanitize_text(value)
        if not v:
            return
        for g in genera:
            gen_bucket = ec_info[ec]['by_genus'][g]
            if field not in gen_bucket:
                gen_bucket[field] = []
            if v not in gen_bucket[field]:
                gen_bucket[field].append(v)
    # parse_7
    def indices_to_genera(ec: str, idxs: Optional[List[str]]) -> List[str]:
        if not idxs:
            return []
        gens, seen = [], set()
        for idx in idxs:
            org = ec_info[ec]['organisms'].get(idx)
            g = org['genus'] if org else None
            if g and g not in seen:
                seen.add(g)
                gens.append(g)
        return gens
    # parse_8 for general information
    def flush_gi_buffer():
        nonlocal gi_buffer_text, gi_buffer_genera
        if not (current_ec and gi_buffer_text):
            gi_buffer_text = None
            gi_buffer_genera = None
            return
        text = brenda_sanitize_text(gi_buffer_text)
        # parse_9
        if text:
            ec_info[current_ec]['_mech_text'].append(text)
        gi_buffer_text = None
        gi_buffer_genera = None
    # parse_12 Main file loop
    ###############
    try:
        with open(enzyme_brenda_path, 'r', encoding='utf-8', errors='ignore') as fh:
            for raw_line in fh:
                # Skip star banners; do not treat as delimiters
                if raw_line.startswith('*' * 20):
                    continue

                line = raw_line.rstrip('\n')
                if not line.strip():
                    continue

                # Entry delimiter
                if line.strip() == "///":
                    flush_gi_buffer()
                    current_ec = None
                    in_entry = False
                    last_tag = None
                    last_ec_field_list_name = None
                    last_by_genus_targets = None
                    continue

                m = TAG_LINE_RE.match(line)
                if not m:
                    # Continuation: extend last list item and GI buffer only
                    if not (in_entry and current_ec and last_tag):
                        continue
                    cont = brenda_sanitize_text(line.strip())
                    if not cont:
                        continue
                    # parse_13 Continuation handling    
                    # Extend EC-wide list item
                    if last_ec_field_list_name:
                        lst = ec_info[current_ec][last_ec_field_list_name]
                        if lst:
                            # only allow continuation if the continuation line is short (e.g., < 100 chars) and the last line isn't already long.
                            if len(cont) < 100 and len(lst[-1]) < 200:
                                lst[-1] = brenda_sanitize_text(f"{lst[-1]} {cont}")
                            else:   
                                lst.append(cont)
                        else:
                            lst.append(cont)

                    # Extend per-genus list item
                    if last_by_genus_targets and last_ec_field_list_name:
                        for g in last_by_genus_targets:
                            gen_bucket = ec_info[current_ec]['by_genus'][g]
                            if last_ec_field_list_name not in gen_bucket:
                                gen_bucket[last_ec_field_list_name] = []
                            lst = gen_bucket[last_ec_field_list_name]
                            if lst:
                                if len(cont) < 100 and len(lst[-1]) < 200:
                                    lst[-1] = brenda_sanitize_text(f"{lst[-1]} {cont}")
                                else:
                                    lst.append(cont)
                            else:
                                lst.append(cont)

                    # Extend GI buffer
                    if last_tag == "GI":
                        gi_buffer_text = f"{gi_buffer_text or ''} {cont}".strip()
                    # Also collect continuation text for metal text-mining (exclude CF)
                    if last_tag in ("RN","SN","SP","NSP","IN","AC","RE","GI") and current_ec:
                        ec_info[current_ec]['_metal_text'].append(cont)
                        ec_info[current_ec]['_mech_text'].append(cont)
                    continue

                # parse_14 New tagged line handling → flush GI if we were buffering
                if last_tag == "GI":
                    flush_gi_buffer()

                tag1, maybe_tag2, value = m.group(1), m.group(2), m.group(3)
                tag1 = tag1.strip()
                val = value.strip()

                # Resolve tag
                if maybe_tag2 and maybe_tag2 in VALID_SHORT_TAGS:
                    tag = maybe_tag2
                elif tag1 in VALID_SHORT_TAGS:
                    tag = tag1
                else:
                    tag = LONG_TO_SHORT.get(tag1)

                if tag in SHORT_TAG_ALIAS:
                    tag = SHORT_TAG_ALIAS[tag]

                if tag is None:
                    # Unknown section header; track and continue (do not reset entry)
                    missing_headers.add(tag1)
                    last_tag = None
                    last_ec_field_list_name = None
                    last_by_genus_targets = None
                    continue

                # parse_15 Start of a new EC entry
                if tag == "ID":
                    norm = normalize_ec_id(val)
                    if not norm:
                        current_ec = None
                        in_entry = False
                        last_tag = None
                        skipped += 1
                        continue
                    current_ec = norm
                    in_entry = True
                    ensure_ec(current_ec)
                    ec_info[current_ec]['enzyme_class'] = enzyme_class_from_ec(current_ec)
                    kept += 1
                    last_tag = tag
                    last_ec_field_list_name = None
                    last_by_genus_targets = None
                    continue

                if not (in_entry and current_ec):
                    continue

                # Reset continuation anchors for this new tagged line
                last_tag = tag
                last_ec_field_list_name = None
                last_by_genus_targets = None

                # Parse_17 indices and value
                idxs, val_wo_idx = extract_indices_and_value(val)
                clean_val = brenda_sanitize_text(val_wo_idx)
                genera = indices_to_genera(current_ec, idxs) if idxs else []
                # collect text for metal text-mining (exclude CF)
                if clean_val and tag in ("RN","SN","SP","NSP","IN","AC","RE","GI"):
                    ec_info[current_ec]['_metal_text'].append(clean_val)
                    ec_info[current_ec]['_mech_text'].append(clean_val)

                # parse_18 Tag handlers (trimmed to requested set)
                if tag == "PR":
                    if not idxs:
                        continue
                    species = brenda_sanitize_text(val_wo_idx)
                    genus = extract_genus(species)
                    for idx in idxs:
                        ec_info[current_ec]['organisms'][idx] = {'species': species, 'genus': genus}

                elif tag == "RN":
                    if clean_val:
                        ec_info[current_ec]['protein_name'] = enhanced_clean_protein_name(clean_val)

                elif tag == "SN":
                    if clean_val and not ec_info[current_ec]['protein_name']:
                        ec_info[current_ec]['protein_name'] = enhanced_clean_protein_name(clean_val)
                elif tag =="RE":
                        # Extract detailed reaction information
                    if '=' in clean_val and is_valid_text(clean_val):
                        append_ec_list(current_ec, 'reaction_equation', clean_val)
            
                elif tag in ("SP", "NSP"):
                    if is_valid_text(clean_val):
                        append_ec_list(current_ec, 'substrates', clean_val)
                        append_ec_list(current_ec, 'compounds', clean_val)
                        if genera:
                            append_by_genus(current_ec, genera, 'substrates', clean_val)
                    last_ec_field_list_name = 'substrates'
                    last_by_genus_targets = genera

                elif tag == "IN":
                    if is_valid_text(clean_val):
                        append_ec_list(current_ec, 'inhibitors', clean_val)
                        append_ec_list(current_ec, 'compounds', clean_val)
                        if genera:
                            append_by_genus(current_ec, genera, 'inhibitors', clean_val)
                    last_ec_field_list_name = 'inhibitors'
                    last_by_genus_targets = genera

                elif tag == "ME":
                    if is_valid_text(clean_val):
                        lc = clean_val.lower()
                        metals_found = set()
                        # match mapping keys with safe boundaries to avoid 'fe' in 'female', 'na' in 'nadh'
                        for pat, sym in _METAL_PATTERNS:
                            # word-ish boundary: not alnum on either side of the key
                            if pat.search(lc):
                                metals_found.add(sym)
                        for sym in metals_found:
                            append_ec_list(current_ec, 'metals', sym)
                            if genera:
                                append_by_genus(current_ec, genera, 'metals', sym)
                    last_ec_field_list_name = 'metals'
                    last_by_genus_targets = genera

                elif tag == "CF":
                    if is_valid_text(clean_val):
                        # remove inline citations, angle refs, (...) blocks, concentrations
                        t = CITATION_HASH_RE.sub('', clean_val)
                        t = CITATION_ANGLE_RE.sub('', t)
                        t = re.sub(r'\([^)]*\)', '', t)
                        t = re.sub(r'\b\d[\d.\s]*\s*(?:mM|µM|uM|nM|pM|M)\b', '', t, flags=re.IGNORECASE)
                        t = re.sub(r'\s{2,}', ' ', t).strip()
                        up = t.upper()

                        tok = next((k for k in _COFACTOR_LEXICON if k in up), None)
                        if not tok:
                            tok = t.split(';',1)[0].split(',',1)[0].split(' ',1)[0]

                        append_ec_list(current_ec, 'cofactors', tok)
                        append_ec_list(current_ec, 'compounds', clean_val)
                        if genera:
                            append_by_genus(current_ec, genera, 'cofactors', clean_val)
                        tokens = set(re.split(r'[\s,;()]+', up))
                        hits = [c for c in _COFACTOR_LEXICON if c in tokens]
                        for cof in hits:
                            append_ec_list(current_ec, 'cofactors', cof)
                            # keep compounds comment out if too noisy
                            #append_ec_list(current_ec, 'compounds', clean_val)
                            if genera:
                                append_by_genus(current_ec, genera, 'cofactors', cof)    

                    last_ec_field_list_name = 'cofactors'
                    last_by_genus_targets = genera

                elif tag == "AC":
                    if is_valid_text(clean_val):
                        append_ec_list(current_ec, 'activators', clean_val)
                        append_ec_list(current_ec, 'compounds', clean_val)
                        if genera:
                            append_by_genus(current_ec, genera, 'activators', clean_val)
                    last_ec_field_list_name = 'activators'
                    last_by_genus_targets = genera

                elif tag == "SY":
                    # Capture only explicit "(gene name ...)" annotations.
                    if is_valid_text(val_wo_idx):
                        # Use a lighter clean to preserve parentheses content needed for the pattern
                        sy_raw = CITATION_HASH_RE.sub('', val_wo_idx)
                        sy_raw = CITATION_ANGLE_RE.sub('', sy_raw).strip()
                        m_gene = re.search(r'\(gene name[:\s]*([A-Za-z0-9._-]{2,20})\)', sy_raw, flags=re.IGNORECASE)
                        gene = m_gene.group(1) if m_gene else None

                        if gene:
                            if genera:
                                for g in genera:
                                    gb = ec_info[current_ec]['by_genus'][g]
                                    if 'gene_names' not in gb:
                                        gb['gene_names'] = []
                                    if gene not in gb['gene_names']:
                                        gb['gene_names'].append(gene)
                            else:
                                # fall back to top-level if no indices
                                if gene not in ec_info[current_ec]['gene_name']:
                                    ec_info[current_ec]['gene_name'].append(gene)
            
                elif tag == "CL":
                    # Enrich gene_name from CL text without keeping cloning_info
                    if is_valid_text(clean_val) and genera:
                        found = set()
                        for pat in CL_GENE_PATTERNS:
                            for m in pat.finditer(clean_val):
                                token = m.group(1).strip()
                                if _is_gene_token(token):
                                    found.add(token)
                        if found:
                            for g in genera:
                                gb = ec_info[current_ec]['by_genus'][g]
                                if 'gene_names' not in gb:
                                    gb['gene_names'] = []
                                for token in found:
                                    if token not in gb['gene_names']:
                                        gb['gene_names'].append(token)

                elif tag == "GI":
                    # Buffer for mechanism-only extraction
                    gi_buffer_text = clean_val
                    gi_buffer_genera = genera

                elif tag in ENV_TAGS:
                    if is_valid_text(clean_val):
                        labeled = f"{tag}: {clean_val}"
                        append_ec_list(current_ec, 'operational_environmental_factors', labeled)
                        if genera:
                            append_by_genus(current_ec, genera, 'operational_environmental_factors', labeled)
                    last_ec_field_list_name = 'operational_environmental_factors'
                    last_by_genus_targets = genera

                # Everything else is ignored to keep output concise
                elif tag in ("RE", "RF", "MW", "PI", "AP", "EN", "CR", "LO", "ST", "KM", "SA", "PU", "EXP", "RT", "BR"):
                    last_ec_field_list_name = None
                    last_by_genus_targets = None

                else:
                    # Unknown/unused tag
                    last_ec_field_list_name = None
                    last_by_genus_targets = None
        # parse_19 Final flush at EOF
        flush_gi_buffer()
        
        # # parse_20 deduplicate reactions dict fromkeys and sort by lenght prioritize equation with = sign                  
        for ec, info in ec_info.items():                    
            reactions = info.get('reaction_equation', [])
            # Sort reactions: those containing '=' first, keep top 10 by length reaction[:10]
            sorted_reactions = sorted(reactions, key=lambda s: (('=' not in s), -len(s)))
            # Deduplicate while preserving order
            deduped_reactions = list(dict.fromkeys(sorted_reactions))[:10]
            info['reaction_equation'] = deduped_reactions

        # parse_21 Finalize: dedupe lists and aggregate gene names to top-level
        for ec, info in ec_info.items():
            # Build top-level gene_name from per-genus gene_names
            agg_gene = set(info.get('gene_name', []))

            # Clean and dedupe per-genus
            by_genus_clean = {}
            for g, buckets in info['by_genus'].items():
                cleaned = {k: list(dict.fromkeys(v)) for k, v in buckets.items()}
                by_genus_clean[g] = cleaned
                for gn in cleaned.get('gene_names', []):
                    agg_gene.add(gn)

            info['by_genus'] = by_genus_clean
            info['gene_name'] = sorted(agg_gene)

            # parse_21b: Mechanism classification from buffered text - EXTRACT CHILD TERMS
            mech_corpus = ' '.join(info.get('_mech_text', []))
                           
            mechanisms_processor = TermProcessor(mechanisms_dict)
            mech_hits = mechanisms_processor.find_all_matches(mech_corpus)
            
            # FIXED: Extract child terms instead of subcategory keys
            child_terms_found = []
            subcategories_involved = []
            for subcategory, child_terms in mech_hits.items():
                if child_terms:  # Only if we actually found terms
                    subcategories_involved.append(subcategory)
                    child_terms_found.extend(child_terms)
            
            # Store child terms (for text mining evidence)
            info['corrosion_mechanisms'] = sorted(set(child_terms_found))
            
            # Optionally store subcategories too (for analysis/debugging)
            info['corrosion_mechanism_categories'] = sorted(set(subcategories_involved))

            
            info.pop('_mech_text', None)   # drop buffer

            # parse 22 Finalize: metal text-mining#brenda_metals = ME ∪ mined-text (exclude CF)
            corpus = ' '.join(info.get('_metal_text', [])).lower()
            mined_syms = set()
            if corpus:
                for pat, sym in _METAL_PATTERNS: #metal processor incorporated
                    if pat.search(corpus):
                        mined_syms.add(sym)  

            # Symbols already captured from ME tag (parser put canonical symbols there)
            me_syms = set(info.get('metals', []))
            # Whitelist to canonical symbols only, as defined by the mapping values
            allowed_symbols = set(cs.metal_mapping.values())
            merged = [s for s in dict.fromkeys(list(me_syms | mined_syms)) if s in allowed_symbols]

            # parse 23 merging of all the metals from brenda
            info['brenda_metals'] = merged # corresponds to all the metals that are found in brenda
            info.pop('_metal_text', None)
            info.pop('metals', None)

            # Deduplicate EC-wide lists
            for fld, val in list(info.items()):
                if fld == 'by_genus':
                    continue
                if isinstance(val, list):
                    info[fld] = list(dict.fromkeys(val))

        # parse_24 Stats   
        ec_with_org = sum(1 for v in ec_info.values() if v['organisms'])
        ec_with_name = sum(1 for v in ec_info.values() if v['protein_name'])
        ec_with_metals = sum(1 for v in ec_info.values() if v['brenda_metals'])
        ec_with_mech = sum(1 for v in ec_info.values() if v['corrosion_mechanisms'])
        ec_with_compounds = sum(1 for v in ec_info.values() if v['compounds'])
        ec_with_reaction = sum(1 for v in ec_info.values() if v['reaction_equation'])
        ec_with_env = sum(1 for v in ec_info.values() if v['operational_environmental_factors'])
        ec_with_cofactors = sum(1 for v in ec_info.values() if v['cofactors'])
        ec_with_activators = sum(1 for v in ec_info.values() if v['activators'])
        ec_with_gene = sum(1 for v in ec_info.values() if v['gene_name'])

        total = max(kept, 1)
        logger.info("BRENDA parsing (trimmed): kept=%d, skipped=%d | organisms=%d (%.1f%%), names=%d (%.1f%%), brenda_metals=%d (%.1f%%), mechanisms=%d (%.1f%%), env=%d (%.1f%%), cofactors=%d (%.1f%%), activators=%d (%.1f%%), gene=%d (%.1f%%), reactions=%d (%.1f%%)", kept, skipped, ec_with_org, 100*ec_with_org/total, ec_with_name, 100*ec_with_name/total, ec_with_metals, 100*ec_with_metals/total, ec_with_mech, 100*ec_with_mech/total, ec_with_env, 100*ec_with_env/total, ec_with_cofactors, 100*ec_with_cofactors/total, ec_with_activators, 100*ec_with_activators/total, ec_with_gene, 100*ec_with_gene/total, ec_with_reaction, 100*ec_with_reaction/total) # ec_with_pathway, 100*ec_with_pathway/total,

        if missing_headers:
            logger.debug("Unmapped section headers encountered (ignored): %s", sorted(missing_headers))

        return ec_info

    except Exception as e:
        logger.exception("Error parsing BRENDA file: %s", e)
    
    return {}
#brenda_data = parse_brenda_file()

In [9]:
#brenda_data_df = pd.DataFrame.from_dict(brenda_data, orient='index')
#brenda_data_df.reset_index(drop=True, inplace=True)
#print(brenda_data_df.head())

_____________________
## Process Brenda Data
_______________

In [10]:
def process_brenda_data(brenda_data, processors, cs, config):
    """
    Redesign: build brenda_en with full v3 scoring and NO field loss.
    - Preserves ALL original parser fields (no pops/deletes).
    - Adds/overwrites the important scoring fields so they are always present.
    - Uses parser's `brenda_metals` as-is (name preserved).
    """
    if not isinstance(brenda_data, dict):
        logger.error("Invalid brenda_data; expected dict")
        return {}

    REQUIRED_DEFAULTS = {
        'functional_categories': [],
        'functional_child_terms': [],
        'functional_matches_detailed': {},
        'fc_cooccurrence_synergy_hit': False,
        'synergy_child_terms_found': [],
        'synergy_categories_involved': [],
        'synergy_description': '',
        'synergy_type': 'none',
        'functional_score': 0.0,
        'overall_functional_score': 0.0,
        'metal_score': 0.0,
        'overall_metal_score': 0.0,
        'synergy_score': 0.0,
        'overall_synergy_score': 0.0,
        'corrosion_relevance_score': 0.0,
        'metal_count': 0,
        'metal_categories_detected': []
    }

    processed = {}

    # local config passthrough—use given config as-is
    local_cfg = config if isinstance(config, cs.ScoringConfig) else cs.ScoringConfig()

    for ec_number, rec in brenda_data.items():
        if not isinstance(rec, dict):
            continue

        # --- 1) Preserve ALL original parser fields (shallow copy)
        out = dict(rec)

        # --- 2) Build analysis text (same evidence recipe as before)
        def _is_valid_equation(eq):
            if not eq or len(eq) < 10: return False
            if eq.startswith('+') or '...' in eq or eq.count('=') > 1: return False
            return any(tok in eq for tok in ['+', '=', '→', '⇌'])

        subs  = ' '.join(out.get('substrates', []) or [])
        cof   = ' '.join(out.get('cofactors', []) or [])
        inhib = ' '.join(out.get('inhibitors', []) or [])
        comp  = ' '.join(out.get('compounds', []) or [])
        env   = ' '.join(out.get('operational_environmental_factors', []) or [])
        rxn   = ' '.join([r for r in (out.get('reaction_equation', []) or []) if _is_valid_equation(r)])
        prot  = str(out.get('protein_name', '') or '')
        mechs = ' '.join(out.get('corrosion_mechanisms', []) or [])  # child terms from parser

        parts = [subs, cof, inhib, comp, env, rxn, prot, mechs]
        analysis_text = ' '.join(p for p in parts if p).strip()

        # Metals from parser (keep name/content)
        brenda_metals = list(dict.fromkeys(out.get('brenda_metals', []) or []))

        # --- 3) Score with v3 (processors dict)
        try:
            results = cs.calculate_overall_scores(
                text=analysis_text,
                processors=processors,     # {'fc_processor':..., 'metal_processor':..., 'synergy_processor':...}
                config=local_cfg,
                brenda_metals=brenda_metals
            )
        except Exception as e:
            logger.error(f"V3 scoring failed for EC {ec_number}: {e}")
            results = {}

        # --- 4) Normalize synergy child terms to plain list
        syn_terms = results.get('synergy_child_terms_found', [])
        if isinstance(syn_terms, set):
            syn_terms = sorted(syn_terms)
        elif isinstance(syn_terms, list):
            syn_terms = list(dict.fromkeys(syn_terms))
        else:
            syn_terms = []

        # --- 5) Inject/overwrite ONLY the important fields (no deletions of originals)
        out.update({
            # keep parser’s identifiers
            'ec_number': out.get('ec_number', ec_number),
            'protein_name': out.get('protein_name', ''),
            'enzyme_class': out.get('enzyme_class', ''),

            # keep parser metals name exactly
            'brenda_metals': brenda_metals,

            # functional mining outputs
            'functional_categories': results.get('functional_categories_detected', REQUIRED_DEFAULTS['functional_categories']),
            'functional_child_terms': results.get('functional_child_terms', REQUIRED_DEFAULTS['functional_child_terms']),
            'functional_matches_detailed': results.get('functional_matches_detailed', REQUIRED_DEFAULTS['functional_matches_detailed']),

            # synergy outputs
            'fc_cooccurrence_synergy_hit': results.get('fc_cooccurrence_synergy_hit', REQUIRED_DEFAULTS['fc_cooccurrence_synergy_hit']),
            'synergy_child_terms_found': syn_terms,
            'synergy_categories_involved': results.get('synergy_categories_involved', REQUIRED_DEFAULTS['synergy_categories_involved']),
            'synergy_description': results.get('synergy_description', REQUIRED_DEFAULTS['synergy_description']),
            'synergy_type': results.get('synergy_type', REQUIRED_DEFAULTS['synergy_type']),

            # scores
            'functional_score': results.get('functional_score', REQUIRED_DEFAULTS['functional_score']),
            'overall_functional_score': results.get('overall_functional_score', REQUIRED_DEFAULTS['overall_functional_score']),
            'metal_score': results.get('metal_score', REQUIRED_DEFAULTS['metal_score']),
            'overall_metal_score': results.get('overall_metal_score', REQUIRED_DEFAULTS['overall_metal_score']),
            'synergy_score': results.get('synergy_score', REQUIRED_DEFAULTS['synergy_score']),
            'overall_synergy_score': results.get('overall_synergy_score', REQUIRED_DEFAULTS['overall_synergy_score']),
            'corrosion_relevance_score': results.get('corrosion_relevance_score', REQUIRED_DEFAULTS['corrosion_relevance_score']),

            # metal detection metadata
            'metal_count': results.get('metal_count', REQUIRED_DEFAULTS['metal_count']),
            'metal_categories_detected': results.get('metal_categories_detected', REQUIRED_DEFAULTS['metal_categories_detected']),
        })

        # NO pops. NO deletions. Everything from parser stays; important fields are guaranteed.
        processed[ec_number] = out

    logger.info("Processed %d enzyme records with v3 scoring (preserve-all).", len(processed))
    return processed

In [11]:
'''# process data sample
{'1.1.1.1': {'ec_number': '1.1.1.1',
  'protein_name': 'alcohol-dehydrogenase',
  'enzyme_class': 'oxidoreductases',
  'substrates': ['acetaldehyde + NADH + H+ = ethanol + NAD+ ( cells with an extra copy of ADH1 display chronological life-span extension. Antioxidant enzymes are induced in 2xADH1 cells. Strains carrying an extra ADH1 copy show extended replicative life span and',
   'increased Sir2p activity )',
   'methylglyoxal + NADH + H+ = acetol + NAD+',
'''

"# process data sample\n{'1.1.1.1': {'ec_number': '1.1.1.1',\n  'protein_name': 'alcohol-dehydrogenase',\n  'enzyme_class': 'oxidoreductases',\n  'substrates': ['acetaldehyde + NADH + H+ = ethanol + NAD+ ( cells with an extra copy of ADH1 display chronological life-span extension. Antioxidant enzymes are induced in 2xADH1 cells. Strains carrying an extra ADH1 copy show extended replicative life span and',\n   'increased Sir2p activity )',\n   'methylglyoxal + NADH + H+ = acetol + NAD+',\n"

___________________
## output brenda_en
________

In [12]:
'''# Temporal brenda sample creation for testing purposes # 20 min at 11 GB and 3 cores 
import random
def create_brenda_sample(brenda_data, sample_size=1000):
    """Create a small sample of BRENDA data for testing"""
    if not brenda_data:
        return {}
    
    # Taking first N entries
    sample_keys = list(brenda_data.keys())[:sample_size]
    return {k: brenda_data[k] for k in sample_keys}
# Create a sample of BRENDA data 6 min
brenda_data = create_brenda_sample(brenda_data, sample_size=1500)'''

'# Temporal brenda sample creation for testing purposes # 20 min at 11 GB and 3 cores \nimport random\ndef create_brenda_sample(brenda_data, sample_size=1000):\n    """Create a small sample of BRENDA data for testing"""\n    if not brenda_data:\n        return {}\n    \n    # Taking first N entries\n    sample_keys = list(brenda_data.keys())[:sample_size]\n    return {k: brenda_data[k] for k in sample_keys}\n# Create a sample of BRENDA data 6 min\nbrenda_data = create_brenda_sample(brenda_data, sample_size=1500)'

In [13]:
#brenda_en = process_brenda_data(brenda_data, processors, cs, config)

In [14]:
#brenda_en_df_co = pd.DataFrame.from_dict(brenda_en, orient='index')
#len(brenda_en_df_co["corrosion_mechanisms"].explode().unique())

___________________
### Enzyme names
____________________
The database containing enzyme names and EC numbers

wget https://www.enzyme-database.org/downloads/enzyme-database.sql.gz

In [15]:
def read_enzyme_names(unique_ecs_to_filter=None):
    """
    Read and parse enzyme file to get EC numbers and their names.
    - Normalizes EC keys (strip 'EC ', accept hyphens)
    - Applies enhanced_clean_protein_name to each name
    - Optionally filters to a set of (normalized) ECs
    """
    paths = setup_paths()
    enzyme_path = paths['enzyme']

    # Normalize the filter set up front
    ec_filter_norm = None
    if unique_ecs_to_filter is not None:
        ec_filter_norm = {normalize_ec_id(ec) for ec in unique_ecs_to_filter}
        ec_filter_norm.discard(None)

    ec_to_names = {}
    with open(enzyme_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            parts = line.rstrip('\n').split('\t', 1)
            if len(parts) < 2:
                continue
            raw_ec, raw_names = parts[0], parts[1]
            ec_norm = normalize_ec_id(raw_ec)
            if not ec_norm:
                continue
            if ec_filter_norm is not None and ec_norm not in ec_filter_norm:
                continue
            if raw_names.lower().startswith("transferred to"):
                continue
            # Robust split on semicolons with optional spaces
            names = [n.strip() for n in raw_names.split(';') if n.strip()]
            cleaned = [enhanced_clean_protein_name(n) for n in names]
            ec_to_names[ec_norm] = cleaned

    return ec_to_names
#ec_to_names = read_enzyme_names(ECcontri_Uniprot["ec"].unique())# THis is just for testing purposes this is to be silenced

'''ec_to_names
{'1.1.1.1': ['alcohol-dehydrogenase',
  'aldehyde-reductase',
  'adh',
  'alcohol-dehydrogenase',
  'aliphatic alcohol-dehydrogenase',
  'ethanol-dehydrogenase',
  'nad-dependent alcohol-dehydrogenase',
  'nad-specific aromatic alcohol-dehydrogenase',
  'nadh-alcohol-dehydrogenase',
  'nadh-aldehyde-dehydrogenase',
  'primary alcohol-dehydrogenase',
  'yeast alcohol-dehydrogenase'],'''
ec_to_names = read_enzyme_names()

___________
### Enzyme Class
________________
The enzyme classification system (text-based hierarchy).

In [16]:
def read_enzyme_class():
    """Parse enzclass.txt exactly as provided (handles spaces inside the code)."""
    paths = setup_paths()
    ec_file_path = paths['enzyme_class']
    enzyme_class = {}
    with open(ec_file_path, 'r', encoding='utf-8', errors='ignore') as f:
        for line in f:
            s = line.strip()
            if not s or not s[0].isdigit():
                continue
            # split on 2+ spaces → [code-part, description]
            parts = re.split(r'\s{2,}', s, maxsplit=1)
            if len(parts) != 2:
                continue
            code_raw, desc = parts[0], parts[1].strip()
            ec_id = code_raw.replace(' ', '')  # "1. 1. 1.-" → "1.1.1.-", "1. -. -.-" → "1.-.-.-"
            if ec_id:
                enzyme_class[ec_id] = desc
    return enzyme_class
#enzyme_class =read_enzyme_class()
#enzyme_class

_________________________________________
### Reaction Data
____________________________________________
 Reaction-level information.

!wget -c "ftp://ftp.genome.jp/pub/kegg/reaction/reaction.tar.gz" # This reaction data wont be used in the creation of the db

In [17]:
def read_reaction_data():
    paths = setup_paths()
    reaction_file_path = paths['reaction']

    reaction_info = {}

    with open(reaction_file_path, 'r') as f:
        for line in f:
            line = line.strip()
            if not line:
                continue

            parts = line.split(None, 1)  # Split on first whitespace
            if len(parts) >= 2:
                rxn_id = parts[0]
                desc_parts = parts[1].split(';')

                # First part is reaction name
                name = desc_parts[0].strip()

                # Rest might contain equation
                equation = desc_parts[1].strip() if len(desc_parts) > 1 else ""

                reaction_info[rxn_id] = {
                    'name': name,
                    'equation': equation
                }

    return reaction_info
'''
{'R00001': {'name': 'polyphosphate polyphosphohydrolase',
  'equation': 'Polyphosphate + n H2O <=> (n+1) Oligophosphate'},
 'R00002': {'name': 'reduced ferredoxin:dinitrogen oxidoreductase (ATP-hydrolysing)',
  'equation': '16 ATP + 16 H2O + 8 Reduced ferredoxin <=> 8 e- + 16 Orthophosphate + 16 ADP + 8 Oxidized ferredoxin'},
 'R00004': {'name': 'diphosphate phosphohydrolase'}'''
#reaction_info = read_reaction_data()

"\n{'R00001': {'name': 'polyphosphate polyphosphohydrolase',\n  'equation': 'Polyphosphate + n H2O <=> (n+1) Oligophosphate'},\n 'R00002': {'name': 'reduced ferredoxin:dinitrogen oxidoreductase (ATP-hydrolysing)',\n  'equation': '16 ATP + 16 H2O + 8 Reduced ferredoxin <=> 8 e- + 16 Orthophosphate + 16 ADP + 8 Oxidized ferredoxin'},\n 'R00004': {'name': 'diphosphate phosphohydrolase'}"

________________________________
### Create reaction mapping
_____________________

In [18]:
def create_ec_to_reaction_mapping():  
    ec_to_names = read_enzyme_names()
    reaction_info = read_reaction_data()
    # join the reaction_brenda on ec numbers
    reaction_brenda = pd.DataFrame(list(reaction_info.values()), index=reaction_info.keys())
    
    # Build keyword-to-ECs reverse index
    keyword_to_ecs = {}
    for ec, names in ec_to_names.items():
        words = set()
        for name in names:
            for word in str(name).lower().split():
                if len(word) > 4:
                    words.add(word)
        for keyword in words:
            if keyword not in keyword_to_ecs:
                keyword_to_ecs[keyword] = set()
            keyword_to_ecs[keyword].add(ec)
    
    # Preprocess reaction names
    rxn_name_lower = {rxn_id: info['name'].lower() for rxn_id, info in reaction_info.items()}
        
    # Match reactions to ECs
    ec_to_reaction = {}
    for rxn_id, rxn_name in rxn_name_lower.items():
        matched_ecs = set()
        for keyword in keyword_to_ecs:
            if keyword in rxn_name: 
                matched_ecs.update(keyword_to_ecs[keyword])
        for ec in matched_ecs:
            if ec not in ec_to_reaction:
                ec_to_reaction[ec] = set()
            ec_to_reaction[ec].add(rxn_id)
    
    return {ec: list(rxns) for ec, rxns in ec_to_reaction.items()}  
#ec_to_reaction = create_ec_to_reaction_mapping()

______________________________
### reaction curated
____________________________

In [19]:
def build_reactions_db_curated(record, brenda_en, ec_to_reaction, reaction_info,
                               max_items: int = 10, max_str_len: int = 220):
    """
    Mutates `record` to add:
      record['reaction_db'] : list[str] (prefer DB "name: equation"; fallback BRENDA equations)

    - Dedupe (preserve order)
    - Priority: entries containing '=' first, then length desc
    - Cap to `max_items`
    - Truncate each string to `max_str_len` chars
    """
    if not isinstance(record, dict):
        raise TypeError("record must be a dict with 'ec_number'")
    ec = normalize_ec_id(record.get('ec_number', '') or '')
    if not ec:
        record['reaction_db'] = []
        return record

    out = []

    # 1) DB reactions via ec_to_reaction → reaction_info
    for rid in (ec_to_reaction.get(ec, []) or []):
        info = reaction_info.get(rid, {}) or {}
        nm = (info.get('name') or '').strip()
        eq = (info.get('equation') or '').strip()
        if nm and eq:
            s = f"{nm}: {eq}"
        elif nm:
            s = nm
        elif eq:
            s = eq
        else:
            continue
        s = ' '.join(s.split())  # compress whitespace
        if len(s) > max_str_len:
            s = s[:max_str_len - 1] + '…'
        out.append(s)

    # 2) Fallback — BRENDA reaction_equation (only if DB list is empty)
    if not out and brenda_en and ec in brenda_en:
        for s in (brenda_en.get(ec,  {}).get('reaction_equation', []) or []):
            if not isinstance(s, str):
                continue
            s = ' '.join(s.split()).strip()
            if not s:
                continue
            if len(s) > max_str_len:
                s = s[:max_str_len - 1] + '…'
            out.append(s)

    # 3) Dedupe, prioritize '=', then cap
    seen = set()
    dedup = []
    for s in out:
        if s not in seen:
            seen.add(s)
            dedup.append(s)

    dedup.sort(key=lambda x: (('=' not in x), -len(x)))
    record['reaction_db'] = dedup[:max_items]
    return record
#reaction_db # single EC test
#rec = {"ec_number": "1.1.1.1"}
#rec = build_reactions_db_curated(rec, brenda_en_co, ec_to_reaction, reaction_info)
# rec['reaction_db'] -> compact list[str]

____________________
### ec_to_pathway mapping
_______________________

wget -O ec_pathway.list "https://rest.kegg.jp/link/pathway/ec"

In [20]:
def read_ec_pathway_mapping():
    """Read EC to pathway mapping file downloaded from KEGG"""
    paths = setup_paths()
    ko_pathway_path = paths['ko_pathway']

    ec_to_pathway = {}

    try:
        with open(ko_pathway_path , 'r') as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) == 2:
                    ec_id = parts[0].replace('ec:', '')
                    # normalise ec
                    normalized_ec = normalize_ec_id(ec_id)
                    
                    pathway_id = parts[1].replace('path:', '')

                    if not normalized_ec:
                        continue
                    if normalized_ec not in ec_to_pathway:
                        ec_to_pathway[normalized_ec] = []
                    ec_to_pathway[normalized_ec].append(pathway_id)

        print(f"Loaded pathway mappings for {len(ec_to_pathway)} EC numbers")
    except Exception as e:
        print(f"Error reading EC-pathway mapping: {e}")
        return {}

    return ec_to_pathway
#ec_pathway_mapping = read_ec_pathway_mapping()
'''
ec_pathway_mapping
{'1.1.1.1': ['map00010',
  'ec00010',
  'map00071',
  'ec00071',
  'map00260',
  'ec00260',
  'map00350',
  'ec00350'''

"\nec_pathway_mapping\n{'1.1.1.1': ['map00010',\n  'ec00010',\n  'map00071',\n  'ec00071',\n  'map00260',\n  'ec00260',\n  'map00350',\n  'ec00350"

_________________
### Ko Database
____________________
 A new variable mapping  KO numbers to EC numbers from KEGG KO file.
rsync -avz rsync://rest.kegg.jp/kegg/ko/ .

In [21]:
def read_ko_data() -> dict:
    """Read and parse KEGG KO file into a dict of {Kxxxxx: {definition, pathway}}"""
    paths = setup_paths()
    ko_file_path = paths['ko'] # from 'ko': db_dir / 'kegg_ko.txt',

    ec_pattern = re.compile(r'\[EC:([0-9\.\-\s]+)\]')

    ko_info = {}
    with open(ko_file_path, 'r') as f:
        for line in f:
            if line.startswith('K'):
                parts = line.strip().split('\t')
                ko_id = parts[0]
                raw_definition = parts[1] if len(parts) > 1 else ''
                # keep raw for EC extraction
                definition_raw = raw_definition
                # also keep a cleaned version without EC tokens 
                definition = strip_all_ec_tokens(raw_definition)

                # extract ALL EC numbers from raw definition
                ec_blob = ec_pattern.findall(definition_raw)  # list like ["1.1.1.1", "3.2.-.-"]
                ec_numbers = []
                for blob in ec_blob:
                    # blobs sometimes have space-separated ECs within the brackets
                    for token in blob.split():
                        ec_norm = normalize_ec_id(token)
                        if ec_norm:
                            ec_numbers.append(ec_norm)
                path_ids = re.findall(r'\bmap\d{5}\b', definition_raw)  # also find any inline mapXXXXX
                ko_info[ko_id] = {
                    'definition_raw': definition_raw,
                    'definition': definition,
                    'pathway': sorted(set(path_ids)),
                    'ec_numbers': sorted(set(ec_numbers)),
                }

    return ko_info
#ko_ec = read_ko_data()
'''
ko_ec sample 
{'K00001': {'definition_raw': 'E1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]',
  'definition': 'E, adh; alcohol dehydrogenase [EC:]',
  'pathway': '',
  'ec_numbers': ['1.1.1.1']},
 'K00002': {'definition_raw': 'AKR1A1, adh; alcohol dehydrogenase (NADP+) [EC:1.1.1.2]',
  'definition': 'AKR1A1, adh; alcohol dehydrogenase (NADP+) [EC:]',
  'pathway': '','''

"\nko_ec sample \n{'K00001': {'definition_raw': 'E1.1.1.1, adh; alcohol dehydrogenase [EC:1.1.1.1]',\n  'definition': 'E, adh; alcohol dehydrogenase [EC:]',\n  'pathway': '',\n  'ec_numbers': ['1.1.1.1']},\n 'K00002': {'definition_raw': 'AKR1A1, adh; alcohol dehydrogenase (NADP+) [EC:1.1.1.2]',\n  'definition': 'AKR1A1, adh; alcohol dehydrogenase (NADP+) [EC:]',\n  'pathway': '',"

_______________
### ko Hierarchi
________________
The KEGG Orthology system is structured hierarchically into broad categories (A), subcategories (B), pathways (C), and then individual KO entries (D) which have functional annotations and often include enzyme commission (EC) numbers(ncbi)
Hierarchy of KO numbers (helps in pathway mapping).The BRITE hierarchy (ko00001.keg) is part of KEGG's comprehensive classification system representing various biological processes and protein families. B: Subcategories or BRITE categories - include "Protein families: metabolism" or "Protein families: signaling and cellular processes" which group functionally related protein families.
The strategy to use here is to chose only from the categories A and B, Table 1. but also only allow some categories, later the inclusion factors are given in table 2
Table 1. Kegg Ortology levels A and B

|Level A	Example |Level B (Subcategory)|
|--|--|
|Metabolism |	Nucleotide metabolism, Amino acid metabolism, Carbohydrate metabolism, Energy metabolism|
|Genetic Information Processing|	Transcription, Translation, Replication and repair, Chromosome|
|Environmental Information Processing|	Membrane transport, Signaling molecules and interaction|
|Cellular Processes|	Cell motility, Cell growth and death, Cellular community eukaryotes|
|Organismal Systems|	Immune system, Nervous system, Endocrine system|
|Human Diseases	|Infectious disease (bacterial, parasitic), Cancer, Neurodegenerative disease|
|BRITE Hierarchies|	Protein families: metabolism, Protein families: signaling and cellular processes|

Table 2. Kegg Ortology allowed Categories taken as Hierarchi for the present study

|Category Type	|Reason for inclusion|
|--|--|
|Protein families: metabolism|	Core metabolic enzymes linked to microbial life|
|Xenobiotics biodegradation and metabolism|	Microbial pathways for breaking down industrial chemicals, pollutants|
|Transporters|	Microbial substrate uptake and efflux, key to biofilm survival
|Signal transduction|	Microbial response to environmental stresses
|Cellular community - prokaryotes|	Biofilm formation and quorum sensing
|Energy metabolism|	Core energy pathways, important in microbial corrosion
|Metabolism of cofactors and vitamins|	Support enzymatic functions, influence microbial activity
|Protein families: signaling and cellular processes	|Immune evasion, stress response—may influence persistence
|Aging and stress response pathways|	Microbial adaptation to hostile conditions
|Infectious disease (bacterial & parasitic)|	Possible indicators of bacterial species present

In [22]:
def read_ko_hierarchy():
    paths = setup_paths()
    ko_path = paths['ko_hierarchy']   # from db_dir / 'ko_hierarchy.txt',
    allowed_categories = [
    'Protein families: metabolism', 'Metabolism of cofactors and vitamins', 'Xenobiotics biodegradation and metabolism',
    'Cellular community - prokaryotes','Signal transduction','Protein families: signaling and cellular processes',
    'Transport and catabolism','Energy metabolism','Nucleotide metabolism','Amino acid metabolism',
    'Glycan biosynthesis and metabolism','Carbohydrate metabolism', 'Lipid metabolism','Metabolism of terpenoids and polyketides',
    'Biosynthesis of other secondary metabolites',
    ]

    all_hierarchy = {
        'A': {},  # Top level Metabolism, Genetic, Environmental, etc.
        'B': {},  # ko Category detailed subcategories (Nucleotide metabolism, Signal transduction, etc.).
        'C': {},  # Pathway specific biochemical or signaling pathways within subcategories.
        'D': {}   # KO/Enzyme  Individual orthologous genes, proteins, enzymes, and their functional annotations.
    } 

    current = {'A': None, 'B': None, 'C': None, 'D': None}
    rows=[]

    with open(ko_path, 'r') as f:
        for line in f:
            if line.startswith('B'):
                parts = line.strip().split()
                b_id = parts[1]
                hierarchy = ' '.join(parts[2:])
                if hierarchy in allowed_categories:
                    current['B'] = b_id
                    current['B_name'] = hierarchy
                else:
                    current['B'] = None
                    current['B_name'] = None

            elif line.startswith('C') and current['B'] is not None:
                parts = line.strip().split()
                c_id = parts[1]
                pathway = ' '.join(parts[2:])
                if '[PATH:' in pathway:
                    pathway = pathway.split('[PATH:')[0].strip()
                current['C'] = c_id
                current['C_name'] = pathway

            elif line.startswith('D') and current['C'] is not None and current['B'] is not None:
                parts = line.strip().split()
                ko_id = parts[1]
                protein_name = ' '.join(parts[2:])
                ec_number = []
                if '[EC:' in protein_name:
                    ec_part = protein_name.split('[EC:')[1].split(']')[0]
                    ec_number = ec_part.split()
                    protein_name = protein_name.split('[EC:')[0].strip()
                ec = ';'.join(ec_number) if ec_number else None

                rows.append({
                        'ko': ko_id,
                        'hierarchy': current['B_name'],
                        'protein_name': protein_name,
                        'ec': ec,
                        'pathway': current['C_name']
                    })

    df_hierarchy = pd.DataFrame(rows)
    return df_hierarchy
hierarchy_all =  read_ko_hierarchy()

'''{'A': {'Metabolism': '',
  'Genetic': 'Information Processing',
  'Environmental': 'Information Processing',
  'Cellular': 'Processes',
  'Organismal': 'Systems',
  'Human': 'Diseases',
  'Brite': 'Hierarchies',
  'Not': 'Included in Pathway or Brite'},
 'B': {'09101': {'name': 'Carbohydrate metabolism', 'parent': 'Metabolism'},
  '09102': {'name': 'Energy metabolism', 'parent': 'Metabolism'},
  '09103': {'name': 'Lipid metabolism', 'parent': 'Metabolism'},
  '09104': {'name': 'Nucleotide metabolism', 'parent': 'Metabolism'},
  '09105': {'name': 'Amino acid metabolism', 'parent': 'Metabolism'}'''

"{'A': {'Metabolism': '',\n  'Genetic': 'Information Processing',\n  'Environmental': 'Information Processing',\n  'Cellular': 'Processes',\n  'Organismal': 'Systems',\n  'Human': 'Diseases',\n  'Brite': 'Hierarchies',\n  'Not': 'Included in Pathway or Brite'},\n 'B': {'09101': {'name': 'Carbohydrate metabolism', 'parent': 'Metabolism'},\n  '09102': {'name': 'Energy metabolism', 'parent': 'Metabolism'},\n  '09103': {'name': 'Lipid metabolism', 'parent': 'Metabolism'},\n  '09104': {'name': 'Nucleotide metabolism', 'parent': 'Metabolism'},\n  '09105': {'name': 'Amino acid metabolism', 'parent': 'Metabolism'}"

I decided against getting all the KEGG ortogonal classification because it was too much and it was necesary just the broad picture, so the Brite database was instead retrieved. The brite database had also more EC and protein_names retrievable from the eccontri.

In [23]:
paths = setup_paths()
brite_path = paths['ko_brite'] # from 'ko_brite': db_dir / 'ko00001.keg',

allowed_categories = [
    'Protein families: metabolism', 'Metabolism of cofactors and vitamins', 'Xenobiotics biodegradation and metabolism',
    'Cellular community - prokaryotes','Signal transduction','Protein families: signaling and cellular processes',
    'Transport and catabolism','Energy metabolism','Nucleotide metabolism','Amino acid metabolism','Infectious disease: bacterial',
    'Glycan biosynthesis and metabolism','Carbohydrate metabolism', 'Lipid metabolism','Metabolism of terpenoids and polyketides',
    'Biosynthesis of other secondary metabolites', 'Metabolism of other amino acids', 'Drug resistance: antimicrobial','Environmental adaptation'
    ]
def parse_ko_brite_filtered(brite_path: str, allowed_b_names: Iterable[str]):
    """
    Parse brite database and gets level B as hierarchy, C as pathways and D as protein_name.
    Builds a flat DataFrame with columns: ko, hierarchy, protein_name, ec, pathway.
    """

    # "D      K08041  ADCY1; adenylate cyclase 1 [EC:4.6.1.1]"
    pattern = re.compile(r'^D\s+(\w+)\s+([^\[]+)(?:\[EC:(.*?)\])?')

    brite_rows = []
    with open(brite_path, 'r', encoding='utf-8') as f:
        current_category = None
        current_pathway = None
        for line in f:
            if line.startswith('B'):
                parts = line.strip().split()
                b_id = parts[1] if len(parts) > 2 else None
                hierarchy = ' '.join(parts[2:]) if len(parts) > 2 else ""
                current_category = hierarchy if hierarchy in allowed_b_names else None
 
            elif line.startswith('C'):
                payload = line[1:].strip()  # drop leading "C"
                payload = re.sub(r'\[PATH:[^\]]+\]', '', payload).strip()
                current_pathway = re.sub(r'^\d+\s+', '', payload)

            elif line.startswith('D'):
                m = pattern.match(line)
                if m and current_category:
                    ko = m.group(1)
                    names = m.group(2).strip()  # "ADCY1; adenylate cyclase 1"
                    ec = m.group(3).strip() if m.group(3) else ""
                    for name in re.split(r'[;,/]', names):
                        brite_rows.append({
                            'ko': ko,
                            'protein_name': name.strip(),
                            'ec_number': ec,
                            'hierarchy': current_category,
                            'pathway': current_pathway
                        })
    hierarchy_brite = pd.DataFrame(brite_rows)
    #hierarchy_brite["protein_name"] = hierarchy_brite["protein_name"].apply(clean_protein_name)
    hierarchy_brite["protein_name"] = hierarchy_brite["protein_name"].apply(enhanced_clean_protein_name)
    return hierarchy_brite

#hierarchy_brite = parse_ko_brite_filtered(brite_path, allowed_categories)

'''    ko protein_name       ec                hierarchy  \
0  K00844           hk  2.7.1.1  Carbohydrate metabolism   
1  K00844   hexokinase  2.7.1.1  Carbohydrate metabolism   
2  K12407          gck  2.7.1.2  Carbohydrate metabolism   
3  K12407  glucokinase  2.7.1.2  Carbohydrate metabolism '''

'    ko protein_name       ec                hierarchy  0  K00844           hk  2.7.1.1  Carbohydrate metabolism   \n1  K00844   hexokinase  2.7.1.1  Carbohydrate metabolism   \n2  K12407          gck  2.7.1.2  Carbohydrate metabolism   \n3  K12407  glucokinase  2.7.1.2  Carbohydrate metabolism '

___________________________
### Cleaning pathways function
______________________________
 The following function applies the correct pandas series logic Series.apply behavior and regular expression design (Pandas documentation, 2024).
For regex practice
Friedl, J. E. F. (2006). Mastering Regular Expressions (3rd ed.). O'Reilly Media.

In [24]:
def clean_pathway_strings(pathway_series: pd.Series) -> pd.Series:
    """
    Clean pathway strings by removing common headers and database references that don't represent specific pathways.
    Parameters:pathway_series : pandas.Series containing pathway strings with pathways separated by semicolons
    Returns:  pandas.Series with cleaned pathway strings
    """
    # Terms to remove - add or remove based on specific needs
    terms_to_remove = [
        'Enzymes with EC numbers', # anotations mistake
        'proteins [BR:ko00194]', # anotations mistake
        #'Metabolic pathways', # to broad term
        'Other Metabolic Processes',
        #'Biosynthesis of secondary metabolites', # to broad term
        'Microbial metabolism in diverse environments','Microbial metabolism in diverse environments', 'Metabolic pathways', # to broad term
        'Exosome \[BR:ko04147\]', # mostly eucariotic
        'photosynthesis', 'Photosynthesis', 'Photosynthesis  proteins [BR:ko00194]', # mostly plants
        'Photosynthesis proteins', # mostly plants
    ]
    
    # Compile regex pattern
    pattern = re.compile(
        '|'.join([re.escape(term) for term in terms_to_remove]),
        flags=re.IGNORECASE
    )
    
    def clean_single_entry(entry: str) -> str:
        if pd.isna(entry) or not isinstance(entry, str) or entry.strip() == '[]':
            return ''
        
        # Remove matched unwanted terms
        cleaned = pattern.sub('', entry)
        
        # Clean up formatting issues
        cleaned = pattern.sub('', entry)
        cleaned = re.sub(r';\s*;', ';', cleaned)
        cleaned = re.sub(r'[;\s]+$', '', cleaned)
        cleaned = re.sub(r'^[;\s]+', '', cleaned)
        
        return cleaned
    
    return pathway_series.apply(clean_single_entry)

______________________
### Pathway Database
________________
Chemical compounds database.wget https://biocyc.org/download.shtml. wget https://www.brenda-enzymes.org/download.php

In [25]:
def read_pathway_data():
    paths = setup_paths()
    pathway_path = paths['pathway']

    pathway_data = {}
    with open(pathway_path, 'r') as f:
          for line in f:
              parts = line.strip().split('\t')
              if len(parts) >= 2:
                  pathway_id = parts[0]
                  pathway_name = parts[1]
                  pathway_data[pathway_id] = pathway_name
    return pathway_data
#pathway_data =read_pathway_data()
'''pathway_data
{'map01100': 'Metabolic pathways',
 'map01110': 'Biosynthesis of secondary metabolites',
 'map01120': 'Microbial metabolism in diverse environments',
 'map01200': 'Carbon metabolism',
 'map01210': '2-Oxocarboxylic acid metabolism',
 'map01212': 'Fatty acid metabolism','''

"pathway_data\n{'map01100': 'Metabolic pathways',\n 'map01110': 'Biosynthesis of secondary metabolites',\n 'map01120': 'Microbial metabolism in diverse environments',\n 'map01200': 'Carbon metabolism',\n 'map01210': '2-Oxocarboxylic acid metabolism',\n 'map01212': 'Fatty acid metabolism',"

______________________
### Mapping ko to ec
______________________

In [26]:
def build_ec_to_ko_map(ko_ec:dict) -> dict:
    """
    Create a map {ec_number: [KO IDs]} from the parsed KO dict, using ec_numbers collected from definition_raw.
    """
    ec_to_ko = defaultdict(list)
    for ko_id, data in ko_ec.items():
        for ec in data.get('ec_numbers', []):
            ec_to_ko[ec].append(ko_id)
    # make lists unique and consistent
    return {k: sorted(set(v)) for k, v in ec_to_ko.items()}

#ko_ec = read_ko_data() # previous function called that feed this one
#ec_to_ko = build_ec_to_ko_map(ko_ec)
#ec_to_ko_sample = {k: ec_to_ko[k] for k in list(ec_to_ko.keys())[:10]}
''' {'1.1.1.1': ['K00001',
  'K11440',
  'K13951',
  'K13952',
  'K13953',
  'K13954',
  'K13980',
  'K18857'],
 '1.1.1.2': ['K00002', 'K13979'],'''

" {'1.1.1.1': ['K00001',\n  'K11440',\n  'K13951',\n  'K13952',\n  'K13953',\n  'K13954',\n  'K13980',\n  'K18857'],\n '1.1.1.2': ['K00002', 'K13979'],"

_________________
### Pathway Curated   

This master assembler takes the outputs from various parsers (BRENDA, pathway_info/data, pathway_mapping) and combines them.

In [27]:
def _std_map_id(pid: str) -> str:
    """Standardize pathway ID format - FAIL if invalid."""
    if not isinstance(pid, str):
        raise TypeError(f"Expected string, got {type(pid)}")
    
    m = re.match(r'^(map|ec)(\d{5})$', pid.strip(), flags=re.IGNORECASE)
    if not m:
        raise ValueError(f"Invalid pathway ID format: {pid}")
    
    return f"map{m.group(2)}"

def build_pathways_db_curated(record, ec_pathway_mapping, pathway_data, ko_ec, ec_to_ko):
    """
    Builds the 'pathways_db' list using a prioritized hierarchy of data sources.
    Hierarchy: 1. BRENDA -> 2. KEGG DB -> 3. KEGG KO
    
    Args:
        record (dict): The enzyme record being built.
        brenda_en (dict): processed data from BRENDA.
        ec_pathway_mapping (dict): map from {ec: [map_id_list]}.
        pathway_data (dict):  map from {map_id: description}.
        ko_ec (dict):  map from {ko_id: data}, used for KO lookups.
    """
    normalized_ec = normalize_ec_id(record.get('ec_number', ''))
    if not normalized_ec:
        record['pathways_db'] = []
        return record

    found_pathways = set()

    # --- Priority 2: structured KEGG EC→map mapping
    if normalized_ec in ec_pathway_mapping:
        for path_id in ec_pathway_mapping[normalized_ec]:
            std_id = path_id.replace('ec', 'map')
            name = pathway_data.get(std_id)
            if name:
                found_pathways.add(name)

    # --- Priority 3: KO as fallback
    if not found_pathways:
        ko_ids = ec_to_ko.get(normalized_ec, [])
        for ko_id in ko_ids:
            ko_rec = ko_ec.get(ko_id, {}) or {}

            # 3.a direct 'pathway' field
            ko_paths = ko_rec.get('pathway', [])
            if isinstance(ko_paths, str):
                iter_paths = [ko_paths] if ko_paths.strip() else []
            elif isinstance(ko_paths, list):
                iter_paths = ko_paths
            else:
                iter_paths = []

            for path in iter_paths:
                p = str(path).strip()
                if not p:
                    continue
                pid = p.replace('ec', 'map')  # standardize id form
                found_pathways.add(pathway_data.get(pid, pid))

            # 3.b parse definition_raw for [PATH:mapxxxxx]
            def_raw = ko_rec.get('definition_raw', '') or ''
            for pid in re.findall(r'\[PATH:(map\d{5})\]', def_raw):
                found_pathways.add(pathway_data.get(pid, pid))

    record['pathways_db'] = sorted(list(found_pathways))
    record['pathways_db'] = clean_pathway_strings(pd.Series(record['pathways_db'])).tolist()
    
    return record

In [28]:
'''# test
ec = str(ECcontri_Uniprot["ec"].iloc[0])
rec = {"ec_number": ec}
rec = build_pathways_db_curated(rec, ec_pathway_mapping, pathway_data, ko_ec, ec_to_ko)
rec
{'ec_number': '1.1.1.1',
 'pathways_db': ['Biosynthesis of secondary metabolites',
  'Chloroalkane and chloroalkene degradation',
  'Drug metabolism - cytochrome P450'''

'# test\nec = str(ECcontri_Uniprot["ec"].iloc[0])\nrec = {"ec_number": ec}\nrec = build_pathways_db_curated(rec, ec_pathway_mapping, pathway_data, ko_ec, ec_to_ko)\nrec\n{\'ec_number\': \'1.1.1.1\',\n \'pathways_db\': [\'Biosynthesis of secondary metabolites\',\n  \'Chloroalkane and chloroalkene degradation\',\n  \'Drug metabolism - cytochrome P450'

In [29]:
pd.set_option("display.max_colwidth", True)
pd.reset_option('display.max_colwidth')

_________________
### Module Database
_________________

In [30]:
def read_module_data():
    paths = setup_paths()
    module_path = paths['module']

    module_info = {}
    with open(module_path, 'r') as f:
      for line in f:
          parts = line.strip().split('\t')
          if len(parts) >= 2:
              module_id = parts[0]
              module_desc = parts[1]
              module_info[module_id] = module_desc
    return module_info
#module_info = read_module_data()
'''M00001': 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate',
 'M00002': 'Glycolysis, core module involving three-carbon compounds',
 'M00003': 'Gluconeogenesis, oxaloacetate => fructose-6P',
 'M00004': 'Pentose phosphate pathway (Pentose p'''

"M00001': 'Glycolysis (Embden-Meyerhof pathway), glucose => pyruvate',\n 'M00002': 'Glycolysis, core module involving three-carbon compounds',\n 'M00003': 'Gluconeogenesis, oxaloacetate => fructose-6P',\n 'M00004': 'Pentose phosphate pathway (Pentose p"

_____________________
### Compound Database
_____________________

In [31]:
def read_compound_data():
    paths = setup_paths()
    compound_path = paths['compound']

    compound_info = {}
    with open(compound_path, 'r') as f:
            for line in f:
                parts = line.strip().split('\t')
                if len(parts) >= 2:
                    compound_id = parts[0]
                    compound_names = parts[1].split('; ')
                    compound_info[compound_id] = {
                        'name': compound_names[0],
                        'synonyms': compound_names[1:] if len(compound_names) > 1 else []
                    }
    return compound_info

#compound_info= read_compound_data()
#compound_info
'''{'C00001': {'name': 'H2O', 'synonyms': ['Water']},
 'C00002': {'name': 'ATP', 'synonyms': ["Adenosine 5'-triphosphate"]},
 'C00003': {'name': 'NAD+',
  'synonyms': ['NAD',
   'Nicotinamide adenine dinucleotide',
   'DPN',
   'Diphosphopyridine nucleotide',
   'Nadide',
   'beta-NAD+']},'''

'{\'C00001\': {\'name\': \'H2O\', \'synonyms\': [\'Water\']},\n \'C00002\': {\'name\': \'ATP\', \'synonyms\': ["Adenosine 5\'-triphosphate"]},\n \'C00003\': {\'name\': \'NAD+\',\n  \'synonyms\': [\'NAD\',\n   \'Nicotinamide adenine dinucleotide\',\n   \'DPN\',\n   \'Diphosphopyridine nucleotide\',\n   \'Nadide\',\n   \'beta-NAD+\']},'

___________
### Metal pdb
____________
MetalPDB in 2018: a database of metal sites in biological macromolecular structures.
Putignano V., Rosato A., Banci L., Andreini C.
Nucleic Acids Res. 2018 Jan;46(D1):D459-D464. [PMID: 29077942]

In [32]:
def parse_metalpdb_xml():
    paths = setup_paths()
    metalpdb_path = paths['metalpdb']

    def norm_symbol(raw: str) -> str | None:
        # Only output normal periodic symbols, never species
        if not raw: return None
        r = raw.strip()
        # If mapped, just use the base symbol (no charge)
        mapped = cs.metal_mapping.get(r.lower())
        if mapped:
            m = re.match(r'^([A-Z][a-z]?)\d?[+-]?$', mapped)
            if m:
                return m.group(1)
            return mapped
        # fallback: proper-case
        return r[0].upper()+r[1:].lower() if len(r)>=2 else r.upper()

    out = {}
    context = etree.iterparse(metalpdb_path, events=('end',), tag='site', recover=True)
    for _ev, site in context:
        try:
            site_name = (site.findtext('site_name') or '').strip()
            pdb_code  = (site.findtext('pdb_code')  or '').strip()

            ec_numbers = set()
            for sc in site.findall('.//site_chain') or site.findall('.//{*}site_chain'):
                ec = (sc.findtext('ec_number') or sc.findtext('{*}ec_number') or '').strip()
                if ec:
                    ec_numbers.add(ec)

            for m_idx, metal in enumerate(site.findall('.//metal') or site.findall('.//{*}metal'), start=1):
                sym = norm_symbol(metal.findtext('periodic_symbol') or metal.findtext('{*}periodic_symbol') or '')
                if not sym: 
                    continue
                cn_txt = (metal.findtext('coordination_number') or metal.findtext('{*}coordination_number') or '').strip()
                try: cn = int(cn_txt)
                except Exception: cn = None

                ligs = metal.findall('ligands/ligand') or metal.findall('.//ligand') or metal.findall('.//{*}ligand')
                residues, seen = [], set()
                for lig in ligs:
                    def gl(tag): return (lig.findtext(tag) or lig.findtext(f'{{*}}{tag}') or '').strip()
                    key = (gl('residue_name').upper(), gl('residue_pdb_number'), gl('chain_letter'), gl('endo_exo') or None)
                    if key in seen: 
                        continue
                    seen.add(key)
                    residues.append({
                        'residue_name': key[0],
                        'residue_number': key[1],
                        'chain': key[2],
                        'binding_type': key[3],
                    })

                site_key = f"{pdb_code}_{site_name}_{sym}_{m_idx:02d}"
                out[site_key] = {
                    'pdb_code': pdb_code,
                    'site_name': site_name,
                    'metal': {'symbol': sym, 'coordination_number': cn},
                    'residues': residues,
                    'ec_numbers': sorted(ec_numbers),
                }
        finally:
            site.clear()
            while site.getprevious() is not None:
                del site.getparent()[0]
            
    return out
#metal_binding_data = parse_metalpdb_xml()
'''metal_binding_data
{'101d_101d_1_Mg_01': {'pdb_code': '101d',
  'site_name': '101d_1',
  'metal': {'symbol': 'Mg', 'coordination_number': 3},
  'residues': [{'residue_name': 'HOH',
    'residue_number': '61',
    'chain': 'A',
    'binding_type': 'exogenous'},
   {'residue_name': 'HOH',
    'residue_number': '60'''

"metal_binding_data\n{'101d_101d_1_Mg_01': {'pdb_code': '101d',\n  'site_name': '101d_1',\n  'metal': {'symbol': 'Mg', 'coordination_number': 3},\n  'residues': [{'residue_name': 'HOH',\n    'residue_number': '61',\n    'chain': 'A',\n    'binding_type': 'exogenous'},\n   {'residue_name': 'HOH',\n    'residue_number': '60"

_____________________
### metals consolidated
_____________________

In [33]:
SPECIES_RE = re.compile(r'^[A-Z][a-z]?\d?[+-]$')  # Fe3+, Ni2+, V5+, Al3+, Zn2+, etc.

def _proper_elem(sym: str) -> str:
    s = (sym or '').strip()
    if not s: return s
    return s[0].upper() + s[1:].lower() if len(s) >= 2 else s.upper()

def _to_symbol(val: str) -> str | None:
    if not val: return None
    m = re.match(r'^([A-Z][a-z]?)(?:\d?[+-])?$', val.strip())
    return m.group(1) if m else None

def _norm_token_any(tok: str, mapping: dict) -> tuple[str | None, str | None]:
    """
    Accepts raw tokens ('CO','zn','magnesium','Fe3+').
    Returns (base_symbol, species_or_None), using mapping when helpful.
    """
    raw = (tok or '').strip()
    if not raw:
        return (None, None)

    # 1) normalize via mapping using lowercase key (handles words like 'magnesium')
    mapped = mapping.get(raw.lower(), raw).strip()

    # 2) if mapped is a species (e.g., 'V5+'), keep species + base
    if SPECIES_RE.match(mapped):
        return (_to_symbol(mapped), mapped)

    # 3) if raw itself is species
    if SPECIES_RE.match(raw):
        return (_to_symbol(raw), raw)

    # 4) treat as element symbol/word -> take base and proper-case
    base = _to_symbol(mapped) or _to_symbol(raw)
    return (_proper_elem(base) if base else None, None)

# cache built from your CURRENT metal_binding_data structure: each site: {'metal': {'symbol': ...}, 'ec_numbers': [...]}
_EC2PDB: dict[str, set[str]] | None = None
def _build_ec2pdb_symbols_index(metal_binding_data: dict) -> dict[str, set[str]]:
    idx: dict[str, set[str]] = defaultdict(set)
    for site in (metal_binding_data or {}).values():
        m = site.get('metal') or {}
        sym = m.get('symbol')
        if not sym:
            continue
        # Normalize PDB symbol to a proper element (never species)
        base, _ = _norm_token_any(sym, {})  # mapping not needed here; PDB is elemental
        if not base:
            continue
        for ec in site.get('ec_numbers', []) or []:
            if ec:
                idx[ec].add(base)  # store proper-case base symbol (e.g., 'Fe','Zn')
    return dict(idx)

def build_metals_db_curated(record: dict, brenda_en: dict, allowed_symbols=None) -> dict:
    """
    Sets record['consolidated_metals'] from union of:
      - BRENDA brenda_metals (species allowed, preferred)
      - PDB symbols for this EC (base elements)
    Dedupe; preserve order; filter by base element against allowed_symbols (if provided).
    Also keeps a copy of raw BRENDA list in record['brenda_metals'] for audit.
    """
    global _EC2PDB, metal_binding_data
    # lazy-build EC -> {PDB base symbols} from current metal_binding_data
    if _EC2PDB is None:
        _EC2PDB = _build_ec2pdb_symbols_index(metal_binding_data or {})

    metal_mapping = cs.metal_mapping  # your mapping (words/aliases/species)
    # allowed by BASE element
    allowed_base = None
    if allowed_symbols:
        allowed_base = {_to_symbol(s) for s in allowed_symbols if _to_symbol(s)}

    ec = normalize_ec_id(record.get('ec_number', '') or '')
    be = brenda_en.get(ec, {}) if brenda_en else {}
    br_raw = [s for s in (be.get('brenda_metals') or []) if isinstance(s, str) and s.strip()]
    record['brenda_metals'] = list(dict.fromkeys(br_raw))  # audit copy

    pdb_syms = sorted(_EC2PDB.get(ec, []))  # already base symbols, proper-cased

    best: dict[str, dict] = {}
    order: list[str] = []
    seen_lower: set[str] = set()

    def observe(token: str):
        base, species = _norm_token_any(token, metal_mapping)
        if not base:
            return
        if allowed_base and base not in allowed_base:
            return
        k = base.lower()
        if k not in seen_lower:
            seen_lower.add(k)
            order.append(base)
            best[base] = {'symbol': _proper_elem(base), 'species': None}
        if species:
            # upgrade to species if ever seen from BRENDA
            best[base]['species'] = species

    # Union: BRENDA first (to capture species), then PDB (base)
    for t in br_raw:   observe(t)
    for t in pdb_syms: observe(t)

    # Emit species if present, else base symbol (proper-cased). No ALL‑CAPS leaks.
    record['consolidated_metals'] = [(best[b]['species'] or best[b]['symbol']) for b in order]
    return record

____________________________
### Integrating pathways to the ECcontri_Uniprot Data 
__________________________

In [34]:
# Reading loading 10 min
output_path = output_large / "chunks_pathway"
chunk_files = sorted([os.path.join(output_path, f) for f in os.listdir(output_path) if f.startswith('chunk_') and f.endswith('.pkl')])
ECcontri_pathway = pd.concat((pd.read_pickle(f) for f in chunk_files), ignore_index=True)
# Extract the number from 'site_X'
ECcontri_pathway['sample_num'] = ECcontri_pathway['Sites'].str.extract('site_(\d+)').astype(int)
# Sort by the numerical part
ECcontri_pathway = ECcontri_pathway.sort_values(by='sample_num')
# Drop the temporary column
ECcontri_pathway = ECcontri_pathway.drop(columns=['sample_num'])
ECcontri_pathway = ECcontri_pathway.drop_duplicates(subset=["ec", "Sites", "Genus"])
ECcontri_pathway = ECcontri_pathway.copy()
ECcontri_pathway["Sites"] = ECcontri_pathway["Sites"].astype("category")
ECcontri_pathway["Genus"] = ECcontri_pathway["Genus"].astype("category")
ECcontri_pathway["pathway"] = ECcontri_pathway["pathway"].astype("category")
ECcontri_pathway["ipath"] = ECcontri_pathway["ipath"].astype("category")

In [35]:
# Read the df ECcontri_Uniprot
ECcontri_Uniprot_path = output_large / 'pre_ECcontri_Uniprot.parquet'
ECcontri_Uniprot = pd.read_parquet(ECcontri_Uniprot_path)
print(f"DataFrame loaded from {ECcontri_Uniprot_path} with shape {ECcontri_Uniprot.shape}")
print(f"Memory usage after loading: {ECcontri_Uniprot.memory_usage(deep=True).sum() / 1024**2:.2f} MB") 
#32.97

DataFrame loaded from /home/beatriz/MIC/output_large/pre_ECcontri_Uniprot.parquet with shape (1491288, 7)
Memory usage after loading: 43.32 MB

In [36]:
ECcontri_Uniprot = pd.merge(ECcontri_Uniprot, ECcontri_pathway, on=['Sites', 'Genus', 'ec'], how='left')

In [37]:
# Making sure the nans are Nans
ECcontri_Uniprot['pathway']= ECcontri_Uniprot['pathway'].astype('str')
ECcontri_Uniprot['ipath']= ECcontri_Uniprot['ipath'].astype('str')
ECcontri_Uniprot['protein_name'] = ECcontri_Uniprot['protein_name'].astype('str')
ECcontri_Uniprot['pathway'] = ECcontri_Uniprot['pathway'].replace('nan', np.nan)
ECcontri_Uniprot['protein_name'] = ECcontri_Uniprot['protein_name'].replace('nan', np.nan)
ECcontri_Uniprot['ipath'] = ECcontri_Uniprot['ipath'].replace('nan', np.nan)
ECcontri_Uniprot["pathway"].isna().sum()

758316

In [38]:
del ECcontri_pathway
gc.collect()  # Run garbage collection to free up memory

29

______________
### Create a consolidated pathway column primary_pathway
_________
In order to use the pathway to retrieve data from the db, the programatic ipath is no suitable since the db do no contain data wiht pwy id so the best option is to find them with the descriptive pathways obtained from pathway column. However when there are nans the programatic column would be used to fill the gaps when ever posible.

In [39]:
# It takes the value from 'pathway'. If that value is null, it fills it with the value from 'ipath' from the exact same row.
ECcontri_Uniprot['pathways'] = ECcontri_Uniprot['pathway'].fillna(ECcontri_Uniprot['ipath'])
# Remove the ipath and pathway to let only one comprehensive column pathways
ECcontri_Uniprot = ECcontri_Uniprot.drop(columns=["pathway", "ipath"])
# Renaming the pathways column to pathway_primary in order to recall its origin
ECcontri_Uniprot = ECcontri_Uniprot.rename(columns={"pathways": "pathway_primary"})
# probe that the number of nans has decresed
ECcontri_Uniprot["pathway_primary"].isna().sum()

597293

In [40]:
ECcontri_Uniprot['pathway_primary']= ECcontri_Uniprot['pathway_primary'].astype('category')
ECcontri_Uniprot['protein_name'] = ECcontri_Uniprot['protein_name'].astype('category')

In [41]:
# saving the df
ECcontri_Uniprot_path = output_large / 'ECcontri_Uniprot_pathway.parquet'
ECcontri_Uniprot.to_parquet(ECcontri_Uniprot_path)

In [42]:
ECcontri_Uniprot.head()

,idx,Sites,Genus,norm_abund_contri,protein_name,ec,Category,pathway_primary
0,0,site_1,Pseudomonas,0.113280,alcohol-dehydrogenase,1.1.1.1,3,PWY-5751
1,1,site_1,Pseudomonas,0.090601,glyceraldehyde-3-phosphate-dehydrogenase,1.2.1.12,3,glycolysis III (from glucose)
2,2,site_1,Staphylococcus,0.009577,aspartate-semialdehyde-dehydrogenase,1.2.1.11,3,superpathway of L-isoleucine biosynthesis I
3,3,site_1,Novosphingobium,0.001127,aspartate-semialdehyde-dehydrogenase,1.2.1.11,3,norspermidine biosynthesis
4,4,site_1,Simplicispira,0.013128,NaN,1.2.1.12,3,glycolysis III (from glucose)

In [43]:
# I decided that taking KO information was too memory intensive and it would take a year to process on my computer or pay an external platform to do it.
'''# Reintegrating KO information
ko_per_gensite_path = output_base / "ko_per_gensite_tabular.csv"

# reading the csv as pandas df
ko_per_gensite_df = pd.read_csv(ko_per_gensite_path)
# convert the ko column of semicolon separate string to a column of list
ko_per_gensite_df['KOs'] = ko_per_gensite_df['KOs'].apply(lambda x: x.split(';') if pd.notna(x) else [])

# back into the dictionary format {('Sites', 'Genus', 'taxon_abun'): [KOs list], ...}
ko_per_gensite = {}
for index, row in ko_per_gensite_df.iterrows():
    # Create the tuple key for the dictionary
    key_tuple = (row['Sites'], row['Genus'], row['taxon_abun'])
    # Assign the list of KOs to this key
    ko_per_gensite[key_tuple] = row['KOs']
# Add KOs via lookup
def get_ko_for_row(row):
    key = (row['Sites'], row['Genus'], row['taxon_abun'])
    return ko_per_gensite.get(key, [])

ECcontri_Uniprot['KOs'] = ECcontri_Uniprot.apply(get_ko_for_row, axis=1)
ECcontri_Uniprot = ECcontri_Uniprot.rename(columns={"KOs": "iKO"})'''

'# Reintegrating KO information\nko_per_gensite_path = output_base / "ko_per_gensite_tabular.csv"\n\n# reading the csv as pandas df\nko_per_gensite_df = pd.read_csv(ko_per_gensite_path)\n# convert the ko column of semicolon separate string to a column of list\nko_per_gensite_df[\'KOs\'] = ko_per_gensite_df[\'KOs\'].apply(lambda x: x.split(\';\') if pd.notna(x) else [])\n\n# back into the dictionary format {(\'Sites\', \'Genus\', \'taxon_abun\'): [KOs list], ...}\nko_per_gensite = {}\nfor index, row in ko_per_gensite_df.iterrows():\n    # Create the tuple key for the dictionary\n    key_tuple = (row[\'Sites\'], row[\'Genus\'], row[\'taxon_abun\'])\n    # Assign the list of KOs to this key\n    ko_per_gensite[key_tuple] = row[\'KOs\']\n# Add KOs via lookup\ndef get_ko_for_row(row):\n    key = (row[\'Sites\'], row[\'Genus\'], row[\'taxon_abun\'])\n    return ko_per_gensite.get(key, [])\n\nECcontri_Uniprot[\'KOs\'] = ECcontri_Uniprot.apply(get_ko_for_row, axis=1)\nECcontri_Uniprot = ECcontri_Uniprot.rename(columns={"KOs": "iKO"})'

## 9.3. Main Function of Creating a Consolidated DataBase

In [44]:
global brenda_data, metal_binding_data, _EC2PDB, _EC2SITES
brenda_data = parse_brenda_file() or {}
metal_binding_data = parse_metalpdb_xml() or {}
_EC2PDB = None
_EC2SITES = None
def create_metabolism_database(ECcontri_Uniprot, fc_processor, metal_processor, synergy_processor):
    """
    Build a list of dictionaries, each representing a single EC record.    
    This function builds a comprehensive database of enzyme records with detailed information
    about their potential relevance to corrosion processes. It incorporates data from various
    sources, including BRENDA, MetalPDB, KEGG, and own experimental data proccesed by Picrust2.
    
    Args:     ECcontri_Uniprot: Main dataframe with EC, protein, abundances, genus (1.5M rows)       
    Returns:  list: List of dictionaries, each containing information about an enzyme
    """
    global brenda_data, metal_binding_data, _EC2SITES
    try:
        # 1 Read all necessary files
        print(f"[{time.ctime()}] Function started. Processing {len(ECcontri_Uniprot)} rows.")
        print("Globals ready:",
              
        f"brenda_data={len(brenda_data)} entries,",
        f"metal_binding_data={len(metal_binding_data)} sites")
        print("Loading data sources...")
        ec_to_names = read_enzyme_names() or {}
        print(f"[{time.ctime()}] Loading ec_to_names...names={len(ec_to_names)}")
        enzyme_class = read_enzyme_class() or {}
        print(f"[{time.ctime()}] Loading enzyme_class...classes={len(enzyme_class)}")
        ko_ec = read_ko_data() or {}
        print(f"[{time.ctime()}] Loading ko_data...KO={len(ko_ec)}")
        ec_to_ko = build_ec_to_ko_map(ko_ec)
        print(f"[{time.ctime()}] Building ec_to_ko map...ec_to_ko ={len(ec_to_ko)}")
        hierarchy_brite = parse_ko_brite_filtered(brite_path, allowed_categories) 
        if hierarchy_brite is None or (hasattr(hierarchy_brite, 'empty') and hierarchy_brite.empty):
            hierarchy_brite =pd.DataFrame()
        print(f"[{time.ctime()}] Loading hierarchy_brite ...hierarchy_brite = {len(hierarchy_brite)}")
        pathway_data = read_pathway_data() or {}
        print(f"[{time.ctime()}] Loading pathway_data...pathways={len(pathway_data)}")
        reaction_info = read_reaction_data() or {}
        print(f"[{time.ctime()}] Loading reaction_info...rxns={len(reaction_info)}")
        ec_to_reaction = create_ec_to_reaction_mapping() or {}  
        print(f"[{time.ctime()}] Building ec_to_reaction map...ec→rxn={len(ec_to_reaction)}")
        module_info = read_module_data() or {}
        print(f"[{time.ctime()}] Loading module_info...")
        compound_info = read_compound_data() or {}
        print(f"[{time.ctime()}] Loading compound_info...")       
        brenda_en = process_brenda_data(brenda_data, processors, cs, config)  or {}
        print(f"[{time.ctime()}] Loading brenda_en...brenda={len(brenda_en)}")
        metal_binding_data = parse_metalpdb_xml() or {}
        _EC2PDB = None  # reset cache
        _EC2SITES = None 
        print(f"[{time.ctime()}] MetalPDB sites: {len(metal_binding_data)}")
        ec_pathway_mapping = read_ec_pathway_mapping() or {}
        print(f"[{time.ctime()}] Extracting ec_pathway_mapping...ec→path={len(ec_pathway_mapping)}")
        _ALLOWED = set(cs.metal_mapping.values()) 
      
        # 2. The EC that will serve to retrieve the data are selected
        unique_ecs = set()
        for ec in ECcontri_Uniprot['ec'].unique():
            normalized_ec = normalize_ec_id(ec)
            if normalized_ec:
                unique_ecs.add(normalized_ec)
    
        unique_ecs_list = list(unique_ecs)  # Make a list for slicing
        ec_to_names = read_enzyme_names(unique_ecs_to_filter=unique_ecs) or {}
        
        # 3. extract protein information
        print("Preparing protein database...")
        protein_database = []
        # From BRENDA
        if brenda_en:
            for ec_number, data in brenda_en.items():
                # NORMALIZE EC NUMBER
                normalized_ec = normalize_ec_id(ec_number)
                if not normalized_ec:
                    continue
                # 4.Use EC number to find enzyme names from ec_to_names
                if normalized_ec in ec_to_names:
                    protein_name = ec_to_names[normalized_ec][0] if ec_to_names[normalized_ec] else None

                    # 5. Apply clean_protein_name here for the protein_name being added to protein_database
                    protein_name_cleaned = clean_protein_name(protein_name) if protein_name else None
                    if protein_name_cleaned:
                        protein_database.append({
                            'source': 'BRENDA',
                            'ec_number': normalized_ec,
                            'protein_name': protein_name_cleaned,
                            'brenda_en': data
                        })  

        # 6. From MetalPDB
        if metal_binding_data:
            for site_key, site_data in metal_binding_data.items():
                for chain in site_data.get('site_chains', []):
                    if 'molecule_name' in chain and chain['molecule_type'] == 'protein':
                        protein_name = chain['molecule_name']
                        # 7.Apply clean_protein_name here for MetalPDB names
                        protein_name_cleaned = clean_protein_name(protein_name) if protein_name else None
                        if protein_name_cleaned:
                            protein_database.append({
                            'source': 'MetalPDB',
                            'pdb_code': site_data.get('pdb_code'),
                            'protein_name': protein_name_cleaned, 
                            'metal_binding': site_data.get('metal', {})
                        })

    except Exception as e:
        print(f"Error loading data sources: {e}")
        
        return []
    
    # 8. Track statistics for validation
    stats = {
        'total_enzymes': 0,
        'with_brenda_en': 0,
        'with_pathways_db': 0,
        'with_ko': 0,
        'with_metal_involvement': 0,
        'with_corrosion_mechanisms': 0,
        'with_reaction_db': 0
    }
    
    start_time_record = time.time()
    # 9. Prepare a list to store all records
    ec_records = []
    stats['total_enzymes'] = len(unique_ecs)

    print("Pre-computing enzyme class lookups...")
    ec_class_lookup = {}
    for normalized_ec in unique_ecs:
        try:
            ec_prefix = '.'.join(normalized_ec.split('.')[:2])
            # 10.Try exact match first
            if ec_prefix in enzyme_class:
                ec_class_lookup[normalized_ec] = enzyme_class[ec_prefix].strip()
            # 11.Then try pattern match
            else:
                pattern_key = f"{ec_prefix}.-.-"
                if pattern_key in enzyme_class:
                    ec_class_lookup[normalized_ec] = enzyme_class[pattern_key]

        except Exception:
            pass  # Skip if error occurs

    # 12. Create lookup dictionary for faster matching
    print("Building protein lookup..")
    protein_lookup = {}
    for db_rec in protein_database:
        protein_name = db_rec.get('protein_name')
        protein_name_cleaned = clean_protein_name(protein_name) if isinstance(protein_name, str) else None
        protein_name_key = enhanced_clean_protein_name(protein_name_cleaned) if isinstance(protein_name_cleaned, str) else None
        if protein_name_key:
            protein_lookup[protein_name_key] = {**db_rec, 'protein_name': protein_name_cleaned}

    # 15.Populate from ec_to_names for basic enzyme names
    print("Building enzyme records...")

    chunk_size = 500
    for chunk_start in range(0, len(unique_ecs_list), chunk_size):
        chunk_ecs = unique_ecs_list[chunk_start:chunk_start + chunk_size]
        print(f"Processing chunk {chunk_start//chunk_size + 1}")
        for ec_number in chunk_ecs:
            # normalise ec number
            normalized_ec = normalize_ec_id(ec_number)
            if not normalized_ec:
                print(f"Skipping invalid EC number: {ec_number}")
                continue

            names = ec_to_names.get(normalized_ec, [])
                
            if names:  # checks if the list is non-empty
                first_name = names[0]
            else:
                first_name = ''
            # 16. clean protein name
            #protein_name_cleaned = clean_protein_name(first_name) if isinstance(first_name, str) else None
            names_list = names if isinstance(names, list) else [names]
            names_clean = [clean_protein_name(str(n).strip()) for n in names_list if n]
            # Choose protein_name from first valid name (or empty string)
            protein_name_cleaned = names_clean[0] if names_clean else ''
                 
            # 17. create a record for each EC number
            record ={
                'ec_number': normalized_ec,
                'enzyme_names':  names_clean,
                'protein_name': protein_name_cleaned if protein_name_cleaned else '',   
                'enzyme_class': ec_class_lookup.get(normalized_ec, ''),
                'pathways_db': [],
                'reaction_db':[],
                'metal_binding_info': {},  # from MetalPDB
                'hierarchy': [],
                'ko': [],
                'reaction': [],                       
                'consolidated_metals': [],                 
                'corrosion_mechanisms': [],
                'operational_environmental_factors': [],
                'residue_name': [],
                'coordination_number': []
            }
            # 21. Add pathways_db the curated pathway resulting from the consolidation of the db info
            record = build_pathways_db_curated(record, ec_pathway_mapping, pathway_data, ko_ec, ec_to_ko)
            if record['pathways_db']:
                stats['with_pathways_db'] += 1
      
            # 22 Add KO IDs
            record['ko'] = ec_to_ko.get(normalized_ec, [])
            if record['ko']:
                stats['with_ko'] += 1
            
            # 23. Add module information
            #for module_id, module_desc in module_info.items():
            #   if f"[EC:{normalized_ec}]" in module_desc:
            #      record['modules'].append({'id': module_id, 'description': module_desc})
           
            # 24. Add reaction information from brenda and from reaction_info dataframe that we joined back on reaction mapping
            record = build_reactions_db_curated(record=record, brenda_en=brenda_en,
                ec_to_reaction=ec_to_reaction, reaction_info=reaction_info)
            if record['reaction_db']:
                stats['with_reaction_db'] += 1
                       
            # 25. Add BRENDA metal information
            record = build_metals_db_curated(record, brenda_en, allowed_symbols=_ALLOWED)
  
            # 26 Directly extend the record with the mechanisms already processed in `process_brenda_data`.
            precalculated_mechanisms = brenda_en.get(normalized_ec,{}).get('corrosion_mechanisms', [])
            if precalculated_mechanisms:
                record['corrosion_mechanisms'].extend(precalculated_mechanisms)
            stats['with_brenda_en'] += 1  
            # Copy text fields for richer scoring if present
            record['operational_environmental_factors'] = brenda_en.get(normalized_ec,{}).get('operational_environmental_factors', [])
                
            ec_records.append(record)
        
    elapsed_time_record = time.time() - start_time_record
    print(f"Processing took {elapsed_time_record:.2f} seconds")

     # 27. Process records in batches to avoid memory issues
    print("Processing protein names and calculating scores...")
    batch_size = 1000  # Adjust based on available memory
    for i in range(0, len(ec_records), batch_size):
        batch = ec_records[i:i+batch_size]
        
        # 28. Process protein names in batch
        for rec_item in batch:
            # Process protein name matches
            try:
                protein_name_norm = enhanced_clean_protein_name(clean_protein_name(rec_item.get('protein_name', ''))) 
               
                if len(protein_name_norm) > 2:
                    # 29 Direct match first
                    if protein_name_norm in protein_lookup:
                        db_rec_match = protein_lookup[protein_name_norm] # Assign matched record to a variable
                        # 31 Process MetalPDB data, copy metalpdb info if present        
                        if 'metal_binding' in db_rec_match: 
                            if 'metal_binding_info' not in rec_item: # Use rec_item
                                rec_item.setdefault('metal_binding_info', {})
                                metal = db_rec_match['metal_binding'].get('symbol')
                                if metal:
                                    rec_item['metal_binding_info'][metal] = db_rec_match['metal_binding']

                    else:  # Fuzzy match on the same normalized keys
                        for db_name_key, db_rec_val in protein_lookup.items():
                            if db_name_key in protein_name_norm or protein_name_norm in db_name_key:
                                # copy BRENDA metals if present
                                if 'brenda_en' in db_rec_val:
                                    seed = db_rec_val['brenda_en'].get('brenda_metals', [])
 
                                # copy MetalPDB info if present
                                if 'metal_binding' in db_rec_val:
                                    rec_item.setdefault('metal_binding_info', {})
                                    m = db_rec_val['metal_binding'].get('symbol')
                                    if m:
                                        rec_item['metal_binding_info'][m] = db_rec_val['metal_binding']
                                        rec_item.setdefault('consolidated_metals', [])
                                        rec_item['consolidated_metals'].append(m)
                                        break
                    # Deduplicate consolidated_metals
                    if rec_item.get('consolidated_metals'):
                        rec_item['consolidated_metals'] = list(dict.fromkeys(rec_item['consolidated_metals']))
                
            except Exception as e:
                print(f"Error processing protein name {rec_item.get('protein_name')}: {e}") # Use rec_item

        # 32. Calculate scores for this batch
        for rec in batch:
            # Build text for scoring once
            try:
                enzyme_names = rec.get('enzyme_names', []) or []
                class_text = rec.get('enzyme_class', '') or ''
                pathways_txt = ' '.join(rec.get('pathways_db', []) or [])
                rxn_text     = ' '.join(rec.get('reaction_db', []) or [])
  
                # 33. Combined text for all scoring
                subs = []; inhib = []; cofac = []; env = []
                ec_local = rec.get('ec_number')
                if brenda_en and ec_local in brenda_en:
                    be = brenda_en.get(ec_local, {})
                    subs  = be.get('substrates', []) or []
                    inhib = be.get('inhibitors', []) or []
                    cofac = be.get('cofactors', []) or []
                    comp  = be.get('compounds')  or []
                    env   = be.get('operational_environmental_factors', []) or []
                    
                text_parts = [
                    ' '.join(enzyme_names),
                    class_text,
                    pathways_txt,
                    rxn_text,
                    rec.get('protein_name', '') or '',
                    ' '.join(subs), ' '.join(inhib), ' '.join(cofac), ' '.join(env)
                ]
                text = ' '.join([t for t in text_parts if t]).lower()
                
                # 34. Use the scoring system module
                score_results = cs.calculate_overall_scores(text,  processors={'fc_processor': fc_processor,'metal_processor': metal_processor,
                                                                'synergy_processor': synergy_processor  },
                                 config=config, brenda_metals=rec.get('consolidated_metals', []))

                # 35. Merge the score results into the record.
                # Preserve mechanisms from BRENDA (score_results may contain an empty list)
                existing_mechanisms = list(rec.get('corrosion_mechanisms', []))
                score_results.pop('corrosion_mechanisms', None)  
                rec.update(score_results)
                if existing_mechanisms:
                    rec['corrosion_mechanisms'] = list({*existing_mechanisms, *rec.get('corrosion_mechanisms', [])})
                    
            except Exception as e:
                print(f"Error scoring data for {rec.get('ec_number')}: {e}")
                
    # 40. Process metal binding in a separate pass one-time index: EC -> list of PDB sites
    def _build_ec2sites_index(_mbd: dict):
        idx = defaultdict(list)
        for site in (_mbd or {}).values():
            ecs = site.get('ec_numbers', []) or site.get('ecs', [])
            if not ecs:
                continue
            for ec in ecs:
                if ec:
                    idx[ec].append(site)
        return dict(idx)

    print("Processing metal binding information from MetalPDB ...")
    try:
        if _EC2SITES is None:
            _EC2SITES = _build_ec2sites_index(metal_binding_data)

        for rec in ec_records:
            ec = normalize_ec_id(rec.get('ec_number') or '')
            if not ec:
                continue

            # accumulate per-metal residue counts and coordination numbers
            res_counts_by_metal = defaultdict(Counter)  # metal -> Counter(AA)
            cn_list_by_metal = defaultdict(list)        # metal -> [cn,...]

            for site in _EC2SITES.get(ec, []):
                m = site.get('metal', {}) or {}
                sym = m.get('symbol')
                if not sym:
                    continue
                cn = m.get('coordination_number')
                if cn is not None:
                    cn_list_by_metal[sym].append(cn)

                # collect residue 3-letter codes only
                for r in site.get('residues', []) or []:
                    aa = (r.get('residue_name') or '').strip().upper()
                    if aa:
                        res_counts_by_metal[sym][aa] += 1

            # build per-metal summary: top residues + modal coordination number
            metal_binding_info = {}
            overall_residues = Counter()
            overall_cns = []

            for sym in sorted(set(list(res_counts_by_metal.keys()) + list(cn_list_by_metal.keys()))):
                # top 3 residues by frequency for this metal
                top_res = [aa for aa, _cnt in res_counts_by_metal[sym].most_common(3)]
                # modal coordination number for this metal (break ties by larger count, then higher cn)
                cns = cn_list_by_metal[sym]
                if cns:
                    cn_mode = Counter(cns).most_common(1)[0][0]
                else:
                    cn_mode = None

                metal_binding_info[sym] = {
                    'residue_names': top_res,
                    'coordination_number': cn_mode 
                }
                
                overall_residues.update(res_counts_by_metal[sym])
                if cn_mode is not None:
                    overall_cns.append(cn_mode)

            # attach to record
            rec['metal_binding_info'] = metal_binding_info
            # overall per-EC summaries (you asked for these fields explicitly)
            rec['residue_name'] = [aa for aa, _ in overall_residues.most_common(5)]  # top 5 overall AAs
            rec['coordination_number'] = sorted(Counter(overall_cns).keys())         # unique modes across metals

    except Exception as e:
        print(f"Error processing metal binding data (PDB aggregation): {e}")

    # 45 Process KO hierarchy information
    print("Processing KO hierarchy...")
    # hierarchy_brite: DataFrame with columns ['ec_number', 'hierarchy']

    # ec_records is a list of dicts
    for rec in ec_records:
        ec = rec.get('ec_number')
        # Find all hierarchy entries for that ec in hierarchy_brite
        hierarchies = []
        if not hierarchy_brite.empty:
            mask = hierarchy_brite['ec_number'].astype(str).str.contains(# rf'(^|[;\s]){re.escape(ec)}($|[;\s])'
                 rf'(?:^|[;\s]){re.escape(ec)}(?:$|[;\s])', regex=True, na=False
            )

            hierarchies = hierarchy_brite.loc[mask, 'hierarchy'].unique()
        # Ensure 'hierarchy' field is present and a list
        rec.setdefault('hierarchy', [])
        # Add each unique hierarchy if not already present
        for hier in hierarchies:
            if hier and hier not in rec['hierarchy']:
                rec['hierarchy'].append(hier)

    # 49. Calculate final corrosion relevance scores using the scoring module
    print("Calculating corrosion relevance scores...")

    for rec in ec_records:
        try:
            # First, ensure rec is a dictionary
            if not isinstance(rec, dict):
                print(f"Warning: Found non-dict record: {type(rec)} - {rec}")
                continue

            # 50. Assign corrosion mechanisms based on all available pathway data
            existing_mechanisms = set(rec.get('corrosion_mechanisms', []))
            #existing_mechanisms.update(pathway_mechanisms)
            rec['corrosion_mechanisms'] = list(existing_mechanisms)
            
            # 51. Calculate final relevance score using the correct overall scores
            if 'corrosion_relevance_score' not in rec:
                rec['corrosion_relevance_score'] = (
                    float(rec.get('overall_functional_score', 0.0)) +
                    float(rec.get('overall_metal_score', 0.0)) +
                    float(rec.get('overall_synergy_score', 0.0))
                )           

        except Exception as e:
                print(f"Error calculating corrosion score for {rec.get('ec_number', 'unknown')}: {e}")
                rec['corrosion_relevance_score'] = rec.get('corrosion_relevance_score', 0.0)
                continue
        
    ko_counts = [len(rec.get('ko', [])) for rec in ec_records]
    print("Records with ≥1 KO:", sum(1 for c in ko_counts if c > 0))
        #===============================================================================================

    # 53. Filter records without content (rest of the code remains the same)
    print("Filtering records...")
    filtered_ec_records = []
    for rec in ec_records:
        # Skip non-dict records
        if not isinstance(rec, dict):
            print(f"Skipping non-dict record during filtering: {type(rec)}")
            continue
        val = rec.get('protein_name')
        protein_name_cleaned = enhanced_clean_protein_name(val) if isinstance(val, str) else None
        protein_name_cleaned = protein_name_cleaned or ""

        enzyme_names = rec.get('enzyme_names', [])
        enzyme_names = [] if enzyme_names is None else enzyme_names
        normalized_ec = rec.get('ec_number', "")

        # 54.Condition 1: At least one valid identifier must be present
        has_valid_protein = bool(protein_name_cleaned) and len(protein_name_cleaned) > 2 and ("uncharacterized" not in protein_name_cleaned)
        has_valid_enzyme = any(len(name) > 2 for name in enzyme_names)
        has_valid_ec = normalized_ec.count('.') == 3 and all(part.isdigit() for part in normalized_ec.split('.'))

        # 55.Condition 2: Check for valuable data that should be preserved
        has_mechanisms = len(rec.get('corrosion_mechanisms', [])) > 0
        has_pathways_db = len(rec.get('pathways_db', [])) > 0
        has_metals_consolidated = len(rec.get('consolidated_metals', [])) > 0

        # 56.Include record if it meets either condition
        if (has_valid_protein or has_valid_enzyme or has_valid_ec) or (has_mechanisms or has_pathways_db or has_metals_consolidated):
            filtered_ec_records.append(rec)

    # 57. Replace original list with filtered version
    ec_records = filtered_ec_records
    stats['with_corrosion_mechanisms'] = sum(1 for rec in ec_records if rec.get('corrosion_mechanisms'))
    stats['with_pathways_db'] = sum(1 for rec in ec_records if rec.get('pathways_db')) #the instead silenced

    # 58. Print summary statistics
    print("\nMetabolism Database Summary:")
    print(f"Total enzyme records: {stats['total_enzymes']}")

    # A variable is created for the total to avoid repetition and add a safety check.
    total_records = len(ec_records)

    if total_records > 0:
        n_with_brenda = sum(1 for rec in ec_records if rec.get('ec_number') in brenda_en)
        print(f"Records with BRENDA data: {n_with_brenda} ({(n_with_brenda/total_records*100):.1f}%)")
        print(f"Records with reaction_db: {stats.get('with_reaction_db', 0)}")
        print(f"Total DB Pathways: {sum(len(rec.get('pathways_db', [])) for rec in ec_records)}")
        print(f"Total KO terms: {sum(len(rec.get('ko', [])) for rec in ec_records)}")
        print(f"Total corrosion mechanisms: {sum(len(rec.get('corrosion_mechanisms', [])) for rec in ec_records)}")
        print(f"Total consolidated metals: {sum(len(rec.get('consolidated_metals', [])) for rec in ec_records)}")
        print(f"Total corrosion synergies: {sum(len(rec.get('corrosion_synergies', [])) for rec in ec_records)}")
        print(f"Total functional categories: {sum(len(rec.get('functional_categories', [])) for rec in ec_records)}")
        print(f"Total operational environmental factors: {sum(len(rec.get('operational_environmental_factors', [])) for rec in ec_records)}")
    else:
        print("No enzyme records were processed to generate statistics.")
    
    print(f"[{time.ctime()}] finishing ec_records...")

    return ec_records

2025-09-19 23:44:33,244 - INFO - BRENDA parsing (trimmed): kept=7874, skipped=1 | organisms=6708 (85.2%), names=7874 (100.0%), brenda_metals=5302 (67.3%), mechanisms=4213 (53.5%), env=5434 (69.0%), cofactors=3016 (38.3%), activators=2927 (37.2%), gene=2451 (31.1%), reactions=5646 (71.7%)

In [45]:
''' ## Sample Uniprot to test
ECcontri_Uniprot= ECcontri_Uniprot.sort_values("idx", ascending=True)
ECcontri_Uniprot_sample = ECcontri_Uniprot.sample(n=15)
ECcontri_Uniprot_sample= ECcontri_Uniprot_sample.sort_values("idx", ascending=True)'''

' ## Sample Uniprot to test\nECcontri_Uniprot= ECcontri_Uniprot.sort_values("idx", ascending=True)\nECcontri_Uniprot_sample = ECcontri_Uniprot.sample(n=15)\nECcontri_Uniprot_sample= ECcontri_Uniprot_sample.sort_values("idx", ascending=True)'

## output EC_RECORDS

In [46]:
# Takes 30 - 240 min
ec_records = create_metabolism_database(ECcontri_Uniprot, fc_processor, metal_processor, synergy_processor)

[Fri Sep 19 23:44:56 2025] Function started. Processing 1491288 rows.
Globals ready: brenda_data=7874 entries, metal_binding_data=117648 sites
Loading data sources...
[Fri Sep 19 23:44:57 2025] Loading ec_to_names...names=7222
[Fri Sep 19 23:44:57 2025] Loading enzyme_class...classes=408
[Fri Sep 19 23:44:57 2025] Loading ko_data...KO=27408
[Fri Sep 19 23:44:57 2025] Building ec_to_ko map...ec_to_ko =5581
[Fri Sep 19 23:44:58 2025] Loading hierarchy_brite ...hierarchy_brite = 75033
[Fri Sep 19 23:44:58 2025] Loading pathway_data...pathways=578
[Fri Sep 19 23:44:59 2025] Loading reaction_info...rxns=12212
[Fri Sep 19 23:45:24 2025] Building ec_to_reaction map...ec→rxn=5571
[Fri Sep 19 23:45:24 2025] Loading module_info...
[Fri Sep 19 23:45:24 2025] Loading compound_info...

2025-09-20 00:00:49,020 - INFO - Processed 7874 enzyme records with v3 scoring (preserve-all).

[Sat Sep 20 00:00:49 2025] Loading brenda_en...brenda=7874
[Sat Sep 20 00:01:10 2025] MetalPDB sites: 117648
Loaded pathway mappings for 3889 EC numbers
[Sat Sep 20 00:01:10 2025] Extracting ec_pathway_mapping...ec→path=3889
Preparing protein database...
Pre-computing enzyme class lookups...
Building protein lookup..
Building enzyme records...
Processing chunk 1
Processing chunk 2
Processing chunk 3
Processing chunk 4
Processing took 4.80 seconds
Processing protein names and calculating scores...
Processing metal binding information from MetalPDB ...
Processing KO hierarchy...
Calculating corrosion relevance scores...
Records with ≥1 KO: 1709
Filtering records...

Metabolism Database Summary:
Total enzyme records: 1793
Records with BRENDA data: 1792 (99.9%)
Records with reaction_db: 1681
Total DB Pathways: 4154
Total KO terms: 3996
Total corrosion mechanisms: 3338
Total consolidated metals: 5780
Total corrosion synergies: 0
Total functional categories: 3087
Total operational environmental factors: 1310
[Sat Sep 20 00:07:20 2025] finishing ec_records...

In [47]:
ec_records_df = pd.DataFrame(ec_records)

In [48]:
ec_records_df[["consolidated_metals", "brenda_metals"]]

,consolidated_metals,brenda_metals
0,"[BA, CA, CO, CU, Ca, Co, Fe, NI, ZN]","[Cl-, K, Na, Co, Ca, Cu, Ba2+, Fe, Zn, Ni, H]"
1,"[CA, Mn, ZN]","[Ca, Mn, Na, Zn]"
2,"[CA, Fe, Mn, V, V5+]","[Cl-, S, K, Fe, Na, H, Ca, Mn, V]"
3,[ZN],"[Zn, H]"
4,[],[H]
...,...,...
1788,"[Co, Na]",[]
1789,"[CA, ZN]","[Ca, Na, Zn]"
1790,[Na],"[K, H]"
1791,"[Mn, ZN, Zn, magnesium]","[K, Zn, Mn]"
1792,"[Co, Fe, NI, Ni]","[H, S, Na, Fe, Ni]"

In [49]:
# Count occurrences of each value in both columns
enzyme_counts = ec_records_df['enzyme_names'].explode().value_counts()
protein_counts = ec_records_df['protein_name'].value_counts()

# Get the number of unique values in each column
enzyme_unique_count = ec_records_df['enzyme_names'].explode().nunique()
protein_unique_count = ec_records_df['protein_name'].nunique()

# Print the results
print("Enzyme Names - Unique Values:", enzyme_unique_count)
print("Enzyme Names - Top 5 Occurrences:\n", enzyme_counts.head())
print("\nProtein Names - Unique Values:", protein_unique_count)
print("Protein Names - Top 5 Occurrences:\n", protein_counts.head())

Enzyme Names - Unique Values: 9600
Enzyme Names - Top 5 Occurrences:
 enzyme_names
23s rrna-methyltransferase    15
trna-methyltransferase        13
16s rrna-methyltransferase    11
malate-dehydrogenase           8
enoyl-reductase                7
Name: count, dtype: int64

Protein Names - Unique Values: 1617
Protein Names - Top 5 Occurrences:
 protein_name
                              79
23s rrna-methyltransferase    15
16s rrna-methyltransferase    11
trna-methyltransferase         9
malate-dehydrogenase           4
Name: count, dtype: int64

### Checking the output
'ec_number', 'protein_name',
'enzyme_names', # enzymes have list muss be integrated as fallback for protein_name
__Decisive Scoring Columns__
'functional_matches_detailed', # to keep procedence and alignment
'functional_categories_detected', # subcategories from fc
'functional_child_terms', # child terms fc
'brenda_metals', # better than consolidated
'synergy_child_terms_found', # child terms found in synergies
'synergy_categories_involved', # subcategories involved in synergies
'synergy_description', # origin type of synergy
__Other Columns__
 'enzyme_class','pathways_db', 'reaction_db', 'hierarchy', # from combined sources 
'corrosion_mechanism_categories', # subcategories mechanisms     
'corrosion_mechanisms', # child categories
'detected_pathways', # subcategories pathways
? 'pathway_matches_detailed', # subcategories + child terms
 'operational_environmental_factors', # child categories
? 'operational_matches_detailed' # subcategories + child terms
__Scoring Columns__
'overall_functional_score', # fc score overall
'overall_metal_score',  # metal score overall
'overall_synergy_score' # overall synergy score
'corrosion_relevance_score', # relevance overall
______________________
**I am no seeing the following columns utility**
'synergy_type', # useless --type of the synergy
'reaction', # wrong extracted
'consolidated_metals', # wrong extracted
'detected_metal_categories', # no info
'functional_categories', # fc strings + scores
'metal_categories_detected', # metal strings + scores , useless
'metal_matches_detailed', # duplicated info 
'functional_score', # scores fc
fc_cooccurrence_synergy_hit', # useless
'metal_score', # scores metal
'synergy_score', # synergy score overall
'metal_count', # number of metals
'legacy_synergy_groups', # useless
'metal_binding_info',  'ko','coordination_patterns', 'residue_binding', # maybe interesting in the future

In [50]:
# Informative renaming of the columns pendiente cambiar nombres en parse y main no?
ec_records_df = ec_records_df.rename(columns= {'functional_matches_detailed': 'functional_combined', 
        'functional_categories_detected': 'functional_sub',  'functional_child_terms': 'functional_child',  
        'synergy_child_terms_found': 'synergy_child','synergy_categories_involved': 'synergy_sub',
         'synergy_description': 'synergy_combined', 'corrosion_mechanism_categories': 'corrosion_mechanisms_sub', 'pathway_matches_detailed': 'pathway_combi',
         'operational_matches_detailed': 'operational_combi'})

In [51]:
# Save to JSON with timing, Notice that due to capacity this code was run on a separate script and is loaded here as input
json_path = output_large / "ec_records.json"
print(f"Starting JSON save to {json_path}...")
start_time = time.time()

try:
    with open(json_path, 'w') as f:
        json.dump(ec_records, f)

    end_time = time.time()
    elapsed = end_time - start_time
    size_mb = os.path.getsize(json_path) / 1024 / 1024

    print(f"Successfully saved to {json_path} in {elapsed:.2f} seconds ({size_mb:.2f} MB)")
except Exception as e:
    print(f"Error saving to JSON: {e}")

Starting JSON save to /home/beatriz/MIC/output_large/ec_records.json...
Successfully saved to /home/beatriz/MIC/output_large/ec_records.json in 0.37 seconds (6.86 MB)

In [52]:
# display whole column
pd.set_option("display.max_colwidth", True)
pd.reset_option('display.max_colwidth')

In [10]:
## opening ec_records dict
json_path = output_large / "ec_records.json"
with open(json_path, 'r') as f:
    ec_records = json.load(f)
ec_records_df = pd.DataFrame(ec_records)
ec_records_df.head(2)

,ec_number,enzyme_names,protein_name,enzyme_class,pathways_db,reaction_db,metal_binding_info,hierarchy,ko,reaction,...,overall_functional_score,overall_metal_score,corrosion_relevance_score,fc_cooccurrence_synergy_hit,synergy_score,synergy_child_terms_found,synergy_categories_involved,synergy_description,synergy_type,overall_synergy_score
0,2.3.2.13,"[protein-glutamine gamma-glutamyltransferase, ...",protein-glutamine gamma-glutamyltransferase,Acyltransferases.,[],[methylcobalamin:N-acetyldemethylphosphinothri...,"{'Ca': {'residue_names': ['HOH', 'ASN', 'ALA']...",[],"[K00686, K03917, K05619, K05620, K05621, K0562...",[],...,4.44938,1.0,5.44938,True,1.5,"[acetyl, acid, adhesion, surface]","[organic_acid_metabolism, biofilm_formation]",Multi-pathway Synergy (2 categories),functional_category_cooccurrence,3.0
1,5.99.1.3,[],,Other isomerases.,[],[],"{'Ca': {'residue_names': ['HOH'], 'coordinatio...",[],[],[],...,0.00000,0.0,0.00000,False,0.0,[],[],,none,0.0

______________________
## Flattening ec_records
_____________________

In [11]:

def targeted_flatten_ec_records(df):
    """
    Single flat DataFrame.
    - protein_name fallback from enzyme_names (if protein_name invalid)
    - keep list columns as lists (no long tables, no joining)
    - clean list fields (strip, drop '', dedupe preserving order)
    - drop ko/metal_binding_info/coordination/pattern fields
    """
    df = df.copy()

    def _ensure_list(x):
        if x is None or (isinstance(x, float) and pd.isna(x)): return []
        if isinstance(x, (list, tuple, set)): return list(x)
        try:
            import numpy as np
            if isinstance(x, (np.ndarray, pd.Series)): return list(x.tolist())
        except Exception:
            pass
        return [x]

    def _clean_list(seq):
        seen, out = set(), []
        for item in _ensure_list(seq):
            s = str(item).strip()
            if not s or s.lower() in {'nan', 'none'}:
                continue
            key = s  # dedupe by normalized string
            if key not in seen:
                seen.add(key)
                out.append(s)
        return out

    def _first_valid_name(seq):
        for x in _ensure_list(seq):
            s = str(x).strip()
            if s and s.lower() not in {'nan','none','uncharacterized protein','hypothetical protein'}:
                return s
        return ''

    def _needs_fallback(name):
        s = (name or '').strip().lower()
        return (len(s) < 3) or ('uncharacterized' in s) or ('hypothetical' in s)

    # protein_name fallback from enzyme_names
    if 'protein_name' not in df.columns:
        df['protein_name'] = ''
    if 'enzyme_names' in df.columns:
        mask = df['protein_name'].fillna('').map(_needs_fallback)
        df.loc[mask, 'protein_name'] = df.loc[mask, 'enzyme_names'].map(_first_valid_name)

    # ---- columns to keep/drop ----
    keep_cols = [
        'ec_number',                        # strings
        'protein_name',                     # strings
        'enzyme_class',                     # strings
        'enzyme_names',                     # list
     
        #'functional_categories'            # dict sub+child +scoring
        'functional_combined',              # dict sub+child (preserve provenance/alignment)
        'functional_sub',                   # list subcategories (fc)
        'functional_child',                 # list child terms (fc)

        'synergy_child',                    # list child terms (synergies)
        'synergy_sub',                      # list subcategories (synergies)
        'synergy_combined',                 # dict origin/type of synergy

        'consolidated_metals',              # joined list brenda_metals is redundant now
        'pathways_db',                      # list 
        #'detected_pathways'                # pathway subcategories
        #'pathway_combi'                    # dict sub+child
        'reaction_db',                      # list 
        'hierarchy',                        # list hierarchies
        'corrosion_mechanisms',             # list child terms
        #'corrosion_mechanism_sub' ,        # list sub
        #'operational_environmental_factors', # list subcategories
        'operational_combi',                # dict sub + child

        'overall_functional_score',         # float
        'overall_metal_score',              # float
        'overall_synergy_score',            # float
        'corrosion_relevance_score',        # float
    ]

 
    drop_explicit = {
        'ko','metal_binding_info','residue_name','coordination_number',
        'coordination_patterns','residue_binding',
    }
    df.drop(columns=[c for c in drop_explicit if c in df.columns], inplace=True, errors='ignore')

    present_keeps = [c for c in keep_cols if c in df.columns]
    flat = df.loc[:, present_keeps].copy()

    # clean list-like columns we keep as lists
    list_like = [c for c in [
        'enzyme_names','consolidated_metals','pathways_db',
        'reaction_db','corrosion_mechanisms','hierarchy',
        'functional_sub','functional_child','synergy_sub','synergy_child'
    ] if c in flat.columns]

    for c in list_like:
        flat[c] = flat[c].apply(_clean_list)

    # ensure dict columns are dicts (not NaN)
    for dcol in ['functional_combined','synergy_combined','operational_combi']:
        if dcol in flat.columns:
            flat[dcol] = flat[dcol].apply(lambda x: x if isinstance(x, dict) else ({} if x is None or (isinstance(x,float) and pd.isna(x)) else x))

    # quick counts for QC/plots
    for c in ['pathways_db','reaction_db','corrosion_mechanisms','consolidated_metals','enzyme_names']:
        if c in flat.columns:
            flat[f'n_{c}'] = flat[c].map(len)

    return flat

In [54]:
# display whole column
pd.set_option("display.max_colwidth", True)
#pd.reset_option('display.max_colwidth')

In [12]:
ec_record_flat = targeted_flatten_ec_records(ec_records_df)

In [13]:
ec_record_flat.head(2)

,ec_number,protein_name,enzyme_class,enzyme_names,consolidated_metals,pathways_db,reaction_db,hierarchy,corrosion_mechanisms,overall_functional_score,overall_metal_score,overall_synergy_score,corrosion_relevance_score,n_pathways_db,n_reaction_db,n_corrosion_mechanisms,n_consolidated_metals,n_enzyme_names
0,2.3.2.13,protein-glutamine gamma-glutamyltransferase,Acyltransferases.,"[protein-glutamine gamma-glutamyltransferase, ...","[BA, CA, CO, CU, Ca, Co, Fe, NI, ZN]",[],[methylcobalamin:N-acetyldemethylphosphinothri...,[],"[surface, acetic acid, adhesion, acid, attachm...",4.44938,1.0,3.0,5.44938,0,10,6,9,9
1,5.99.1.3,,Other isomerases.,[],"[CA, Mn, ZN]",[],[],[],[],0.00000,0.0,0.0,0.00000,0,0,0,3,0

_____________________
### Enzyme and Protein Ocurrencies
________________

In [14]:
# Count occurrences of each value in both columns
enzyme_counts = ec_record_flat['enzyme_names'].explode().value_counts()
protein_counts = ec_record_flat['protein_name'].value_counts()
ec_counts = ec_record_flat['ec_number'].value_counts()
# Get the number of unique values in each column
enzyme_unique_count = ec_record_flat['enzyme_names'].explode().nunique()
protein_unique_count = ec_record_flat['protein_name'].nunique()
ec_unique_count = ec_record_flat['ec_number'].nunique()

# Print the results
print("EC Numbers - Unique Values:", ec_unique_count)
print("\nProtein Names - Unique Values:", protein_unique_count)
print("Protein Names - Top 5 Occurrences:\n", protein_counts.head())
print("\nEnzyme Names - Unique Values:", enzyme_unique_count)
print("Enzyme Names - Top 5 Occurrences:\n", enzyme_counts.head())

EC Numbers - Unique Values: 1793

Protein Names - Unique Values: 1617
Protein Names - Top 5 Occurrences:
 protein_name
                              79
23s rrna-methyltransferase    15
16s rrna-methyltransferase    11
trna-methyltransferase         9
malate-dehydrogenase           4
Name: count, dtype: int64

Enzyme Names - Unique Values: 9599
Enzyme Names - Top 5 Occurrences:
 enzyme_names
23s rrna-methyltransferase    15
16s rrna-methyltransferase    11
trna-methyltransferase        10
hydrogenase                    5
waaa                           4
Name: count, dtype: int64

______________
## Saving flatten Records
_____________

In [58]:
# save ec_records_fixed to json
output_path = output_large / "ec_record_flat.json"
ec_record_flat.to_json(output_path, orient='records', indent=2)

## Read flat

In [39]:
# read the ec_records_fixed json
output_path = output_large / "ec_record_flat.json"
with open(output_path, 'r') as f:
    ec_record_flat = json.load(f)

In [41]:
ec_record_flat = pd.DataFrame(ec_record_flat)

In [42]:
ec_record_flat = ec_record_flat.rename(columns= {'ec_number': 'ec'})

In [43]:
ec_record_flat.head(2)

,ec,protein_name,enzyme_class,enzyme_names,functional_combined,functional_sub,functional_child,synergy_child,synergy_sub,synergy_combined,...,operational_combi,overall_functional_score,overall_metal_score,overall_synergy_score,corrosion_relevance_score,n_pathways_db,n_reaction_db,n_corrosion_mechanisms,n_consolidated_metals,n_enzyme_names
0,2.3.2.13,protein-glutamine gamma-glutamyltransferase,Acyltransferases.,"[protein-glutamine gamma-glutamyltransferase, ...","{'biofilm_formation': ['adhesion', 'surface'],...","[biofilm_formation, organic_acid_metabolism]","[acetyl, acid, adhesion, surface]","[acetyl, acid, adhesion, surface]","[organic_acid_metabolism, biofilm_formation]",Multi-pathway Synergy (2 categories),...,{},4.44938,1.0,3.0,5.44938,0,10,6,9,9
1,5.99.1.3,,Other isomerases.,[],{},[],[],[],[],,...,{},0.00000,0.0,0.0,0.00000,0,0,0,3,0

In [15]:
# size of the ec_records dictionary on MB
total_memory = ec_records_df.memory_usage(deep=True).sum()
print(f"Memory usage ec_records: {total_memory / 1024**2:.2f} MB")

Memory usage ec_records: 5.62 MB

In [16]:
# size of the json file
json_path = output_large / "ec_record_flat.json"
size_mb = os.path.getsize(json_path) / 1024 / 1024
print(f"Size of the JSON file: {size_mb:.2f} MB")

Size of the JSON file: 5.63 MB

In [50]:
pre_ECcontri_enriched.nunique()

idx                  1491288
Sites                     70
Genus                     85
norm_abund_contri    1087464
protein_name            3946
ec                      1793
Category                   3
pathway_primary          545
react_primary           1160
dtype: int64

In [48]:
ec_record_flat["protein_name"].nunique()

1617

_________________________
## Integrating Reaction_Primary
________________________
database coming from section 7 of notebook 6_picrust_functional.ipynb that has the reaction data saved in chunks

In [18]:
# Reading loading 10 min
output_path = output_large / "chunks_react"
chunk_files = sorted([os.path.join(output_path, f) for f in os.listdir(output_path) if f.startswith('chunk_') and f.endswith('.pkl')])
ECcontri_react = pd.concat((pd.read_pickle(f) for f in chunk_files), ignore_index=True)
# Extract the number from 'site_X'
ECcontri_react['sample_num'] = ECcontri_react['Sites'].str.extract('site_(\d+)').astype(int)
# Sort by the numerical part
ECcontri_react = ECcontri_react.sort_values(by='sample_num')
# Drop the temporary column
ECcontri_react = ECcontri_react.drop(columns=['sample_num'])
ECcontri_react = ECcontri_react.drop_duplicates(subset=["ec", "Sites", "Genus"])
ECcontri_react = ECcontri_react.copy()
ECcontri_react["Sites"] = ECcontri_react["Sites"].astype("category")
ECcontri_react["Genus"] = ECcontri_react["Genus"].astype("category")
ECcontri_react["rxn"] = ECcontri_react["rxn"].astype("category")
ECcontri_react = ECcontri_react.rename(columns = {"rxn": "react_primary"})

In [17]:
ECcontri_Uniprot_path = output_large / 'ECcontri_Uniprot_pathway.parquet' # saved after the pathway join
with open(ECcontri_Uniprot_path, 'rb') as f:
    ECcontri_Uniprot = pd.read_parquet(f)

In [19]:
ECcontri_react.columns

Index(['ec', 'Sites', 'Genus', 'react_primary'], dtype='object')

In [23]:
ECcontri_Uniprot.columns

Index(['idx', 'Sites', 'Genus', 'norm_abund_contri', 'protein_name', 'ec',
       'Category', 'pathway_primary'],
      dtype='object')

In [20]:
pre_ECcontri_enriched = pd.merge(ECcontri_Uniprot, ECcontri_react, on=['Sites', 'Genus', 'ec'], how='left')

In [21]:
pre_ECcontri_enriched.columns

Index(['idx', 'Sites', 'Genus', 'norm_abund_contri', 'protein_name', 'ec',
       'Category', 'pathway_primary', 'react_primary'],
      dtype='object')

______________________________________________
## Enriching ECcontri_Uniprot
______________________________________________

Reactions and pathways are entities that came in the results of picrust2 in the form of Picrus_results df it was composed of progamatic pathways(ipath) and desciptive pathways(pathways), they were 366. However the data also have 3000 Reactions and a parsing dictionary between pathways and reactions. So the pathways obtained through this parcing (path_parce 545). Unfortunately the nature of the dbs available in this study are open access and the programatic pathways are no accesible, that is why the descriptors(pathways) were taken going forward. This pathways column, was taken as backbone and the gaps were filled up with the results from path_parce. This column then contains pathways descriptive but also programatic(pathway_primary). In order to make the allocation of the categories of this pathways for the dictionaries on global_terms.py inside pathways and functional categories, a manual allocation was imposible due to the sheer amount of data (545 names). Therefore, several codes were developed to make the distribution accurate (validation notebook in scoring_system), however the results were rudimentary. Ultimately several language models were used to allocate the columns pathways into the different dictionaries, mainly Gemini and Copilot, and ultimately human review.
______________________
### Auditor Structure 
______________________
the pathway_primary and reaction_primary were used as golden truth and it was keep with no further updating because corresponds to a granular nature of the results from picrust and inputing more data to fillup the gaps would imply diluting the good data and adding noise. The pathway_primary/reaction_primary column was use to validate the retrieved data pathways_db/react_db by objectively measuring the agreement between the two. This helps to improve the scoring system.

In [ ]:
'''def enrich_eccontri_data(eccontri_df, ec_records_flat):
    """
    Enrich the ECcontri_Uniprot dataframe with complete information from ec_records dictionary
    and apply validation using pathways_primary and reaction_primary columns
    It searches protein names, enzyme names and EC numbers from ec_records to enrich the original eccontri.
    When it finds an Uncharacterised protein, it replaces this name with the enzyme names corresponding to the EC number.
    Parameters: eccontri_df : pandas DataFrame original ECcontri_Uniprot data with EC numbers in format without prefix EC:x.x.x.x
                ec_records_flat : list of Dictionary where keys are EC numbers (without 'EC:' prefix) and values are metadata dictionaries
    Returns:    enriched_df : pandas DataFrame with additional metadata columns and scoring applied
    """
 
    # Make a copy to avoid modifying the original
    enriched_df = eccontri_df.copy()

    start_time = time.time()

    # Create dictionaries for faster lookups
    print("Creating lookup dictionaries...")

    # 1. EC number dictionary flaten
    ec_dict = {record['ec_number']: record for record in ec_records_flat if 'ec_number' in record}
    print(f"Created EC dictionary with {len(ec_dict)} entries")

    # 2. Protein name dictionary
    protein_name_dict = {} # the true is that the enzyme names are much rich than the protein name, they eventualy only represent one entity for this study
    for record in ec_records_flat:
        enzyme_names_str = record.get('enzyme_names', '')
        if enzyme_names_str:
            # Handle both string and list formats
            if isinstance(enzyme_names_str, list):
                names = enzyme_names_str
            else:
                # Flattened records will have enzyme_names as semicolon-separated string
                names = [name.strip() for name in enzyme_names_str.split(';')]
            
            for name in names:
                if name:  # Skip empty names
                    protein_name_dict[name.lower()] = record
    print(f"Created protein name dictionary with {len(protein_name_dict)} entries")

    # 3. Create a mapping dictionary to store all matches
    idx_to_metadata = {} # in the current implementation there is already a column with idx with is each line unique

    # data from ec_records
    metadata_columns = ['ec_number', 'protein_name', 'enzyme_class', 'enzyme_names', 'functional_combined', 'functional_sub', 'functional_child',
     'synergy_child', 'synergy_sub', 'synergy_combined','consolidated_metals', 'pathways_db', 'reaction_db', 'hierarchy',
     'corrosion_mechanisms', 'operational_combi', 'overall_functional_score', 'overall_metal_score', 'overall_synergy_score',
     'corrosion_relevance_score'] 
  
    for col in metadata_columns:
        enriched_df[col] = None

    # 4. Define progress reporting
    total_rows = len(enriched_df)
    log_interval = max(1, min(10000, total_rows // 20))  # Log at most 20 times, minimum every 10000 rows

    print(f"Processing {total_rows} rows with logging every {log_interval} rows")

    # 5. try protein name matches
    print("Performing protein name matches...")
    # Get rows without EC+Genus matches
    remaining_indices = set(enriched_df.index) - set(idx_to_metadata.keys())
    mask_remaining = enriched_df.index.isin(remaining_indices)
    mask_valid_protein = enriched_df['protein_name'].notna() & (enriched_df['protein_name'] != "Uncharacterized protein")
    mask_protein_match = mask_remaining & mask_valid_protein

    # 6. This part still needs row-by-row processing for fuzzy matching
    protein_matches = 0
    for idx in enriched_df.index[mask_protein_match]:
        if idx % log_interval == 0:
            print(f"Processing protein matches: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
            
        protein_name = enriched_df.loc[idx, 'protein_name'].lower()

        # 7. Direct lookup in protein name dictionary
        if protein_name in protein_name_dict:
            idx_to_metadata[idx] = protein_name_dict[protein_name]
            protein_matches += 1
        else:
            # Try partial matches
            for name, record in protein_name_dict.items():
                if name in protein_name or protein_name in name:
                    idx_to_metadata[idx] = record
                    protein_matches += 1
                    break

    print(f"Found {protein_matches} protein name matches")

    # 8- For any remaining rows, try EC-only matching
    print("Performing EC-only matches...")
    # Get rows without matches so far
    remaining_indices = set(enriched_df.index) - set(idx_to_metadata.keys())
    mask_remaining = enriched_df.index.isin(remaining_indices)
    mask_valid_ec = enriched_df['EC'].notna()
    mask_ec_match = mask_remaining & mask_valid_ec

    ec_only_matches = 0
    for idx in enriched_df.index[mask_ec_match]:
        if idx % log_interval == 0:
            print(f"Processing EC matches: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
            
        ec_num = enriched_df.loc[idx, 'EC']
        if ec_num in ec_dict:
            idx_to_metadata[idx] = ec_dict[ec_num]
            ec_only_matches += 1

    print(f"Found {ec_only_matches} EC-only matches")

    # 9. Apply all metadata in one go based on the matches we found
    print("Applying metadata to matched rows...")
    for idx, metadata in idx_to_metadata.items():
        if idx % log_interval == 0:
            print(f"Applying metadata: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")

        # Only proceed if we have metadata (either from EC or from protein/enzyme name)
        if metadata is not None:

            # 10. If protein_name is missing or uncharacterized, try to fill it with enzyme_names
            if pd.isna(enriched_df.at[idx, 'protein_name']) or enriched_df.at[idx, 'protein_name'].lower() == "uncharacterized protein":
                if 'enzyme_names' in metadata and metadata['enzyme_names']:
                    # Handle both flattened (string) and non-flattened (list) records
                    if isinstance(metadata['enzyme_names'], list):
                        enriched_df.at[idx, 'protein_name'] = '; '.join(metadata['enzyme_names'])
                    else:
                        enriched_df.at[idx, 'protein_name'] = str(metadata['enzyme_names'])

            # 11. Add basic metadata
            for field in ['enzyme_names', 'enzyme_class', 'pathways', 'hierarchy', 'corrosion_mechanisms',
                          'functional_categories',   'corrosion_synergies']:
                if field in metadata and metadata[field]:
                    if isinstance(metadata[field], list):
                        enriched_df.at[idx, field] = '; '.join(str(v) for v in metadata[field])
                    else:
                        enriched_df.at[idx, field] = str(metadata[field])
            
            # 12.add corrosion_relevance category:
            if 'corrosion_relevance' in metadata:
                enriched_df.at[idx, 'corrosion_relevance'] = metadata['corrosion_relevance']

            # 13. add the consolidated metals field:
            if 'metals_consolidated' in metadata and metadata['metals_consolidated']:
                if isinstance(metadata['metals_consolidated'], list):
                    enriched_df.at[idx, 'metals_consolidated'] = '; '.join(metadata['metals_consolidated'])
                    # Set has_metal flag based on whether metals exist
                    enriched_df.at[idx, 'has_metal'] = len(metadata['metals_consolidated']) > 0
                else:
                    enriched_df.at[idx, 'metals_consolidated'] = str(metadata['metals_consolidated'])
                    # Set has_metal flag for string case too
                    enriched_df.at[idx, 'has_metal'] = bool(metadata['metals_consolidated'])

            # 14. Adding the scores for each component, simple score fields, handle in a loop
            score_fields = ['overall_metal_score', 'overall_corrosion_score', 'overall_functional_score',   
                             'overall_synergy_score', 'corrosion_relevance_score']
            
            for field in score_fields:
                if field in metadata:
                    try:
                        enriched_df.at[idx, field] = float(metadata.get(field, 0))
                    except (ValueError, TypeError):
                        print(f"Row {idx}: Could not convert {field} to float")
                        enriched_df.at[idx, field] = None
            
            # 15. For dictionary score fields, handle in a loop too
            dict_fields = ['metal_scores', 'corrosion_synergy_scores']
            
            for field in dict_fields:
                if field in metadata:
                    enriched_df.at[idx, field] = json.dumps(metadata.get(field, {}))
                            
    # 16. Now perform scoring for all rows, regardless of whether they got metadata from EC records
        print("Calculating scores for rows with missing score data...")
        scores_calculated = 0
        scores_already_present = 0
        
        for idx in enriched_df.index:
            if idx % log_interval == 0:
                print(f"Processing scoring: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
            
            # 17.Check if this row already has scoring data
            if (enriched_df.at[idx, 'overall_metal_score'] is not None and 
                enriched_df.at[idx, 'overall_corrosion_score'] is not None and
                enriched_df.at[idx, 'corrosion_relevance_score'] is not None):
                scores_already_present += 1
                continue  # Skip rows that already have scores
                
            # 18. Only calculate scores if we have some text to analyze
            protein_name = enriched_df.at[idx, 'protein_name']
            if protein_name is not None and not pd.isna(protein_name):
                try:
                    # Generate text to analyze
                    analysis_text = protein_name
                    
                    # Add enzyme class if available
                    enzyme_class = enriched_df.at[idx, 'enzyme_class'] 
                    if enzyme_class is not None and not pd.isna(enzyme_class):
                        analysis_text += ' ' + enzyme_class
                    
                    # Add pathways if available
                    pathways = enriched_df.at[idx, 'pathways']
                    if pathways is not None and not pd.isna(pathways):
                        analysis_text += ' ' + pathways
                        
                    # 19. Calculate scores using the scoring system
                    score_results = cs.calculate_overall_scores(analysis_text)
                    
                    # Update scores in the dataframe
                    for key, value in score_results.items():
                        if key in enriched_df.columns:
                            if isinstance(value, list):
                                enriched_df.at[idx, key] = '; '.join(map(str, value))
                            elif isinstance(value, dict):
                                enriched_df.at[idx, key] = json.dumps(value)
                            else:
                                enriched_df.at[idx, key] = value
                    
                    # 20. Calculate corrosion relevance explicitly
                    corrosion_relevance_score, corrosion_relevance = cs.calculate_corrosion_relevance_score(
                        score_results.get('overall_metal_score', 0),
                        #score_results.get('overall_corrosion_score', 0),
                        #score_results.get('overall_organic_process_score', 0),
                        #score_results.get('overall_keyword_score', 0),
                        score_results.get('overall_synergy_score', 0),
                        score_results.get('overall_functional_score', 0)
                    )
                    enriched_df.at[idx, 'corrosion_relevance_score'] = corrosion_relevance_score
                    enriched_df.at[idx, 'corrosion_relevance'] = corrosion_relevance
                    
                    scores_calculated += 1
                    
                except Exception as e:
                    print(f"Error calculating scores for row {idx}: {e}")
        
        print(f"Scoring complete: {scores_calculated} rows scored, {scores_already_present} rows already had scores")
                      
    # 21. Final report
    end_time = time.time()
    total_time = end_time - start_time
    print(f"Completed enrichment in {total_time:.2f} seconds")
    print(f"Processed {total_rows} rows at {total_rows/total_time:.1f} rows/second")

    # Count non-null values in the metadata columns to see success rate
    metadata_counts = {col: enriched_df[col].notnull().sum() for col in metadata_columns}
    print("\nMetadata population statistics:")
    for col, count in metadata_counts.items():
        print(f"  {col}: {count} rows ({count/total_rows*100:.1f}%)")
    #This part corresponds to the validation part used on ec records but move here for convinience
    # 59. Enhanced validation using the validate_against_pathways function
        print("Running enhanced validation...")
        validation_issues = []
        validation_metrics = {
            'total_validated': 0,
            'high_confidence': 0,
            'medium_confidence': 0,
            'low_confidence': 0,
            'avg_pathway_f1': 0,
            'avg_mechanism_f1': 0
        }

        pathway_f1_scores = []
        mechanism_f1_scores = []

        for i, rec in enumerate(ec_records):
            # Basic field validation (keep your existing checks)
            if not rec.get('ec_number'):
                validation_issues.append(f"Record {i} missing EC number")
            if not rec.get('enzyme_names'):
                validation_issues.append(f"EC {rec.get('ec_number')} missing enzyme names")
            if not rec.get('protein_name'):
                validation_issues.append(f"EC {rec.get('ec_number')} missing protein name")
            if not rec.get('corrosion_relevance_score'):
                validation_issues.append(f"EC {rec.get('ec_number')} missing corrosion relevance score")
            
            # Content validation using your validate_against_pathways function
            try:
                # use pathway_primary ata variable
                validation_results = cs.validate_against_pathways(rec, pathways_primary_mapping)
                
                # Add validation results to the record
                rec['validation_results'] = validation_results
                validation_metrics['total_validated'] += 1
                
                # Categorize confidence levels
                confidence = validation_results['overall_confidence']
                if confidence >= 0.7:
                    validation_metrics['high_confidence'] += 1
                elif confidence >= 0.4:
                    validation_metrics['medium_confidence'] += 1
                else:
                    validation_metrics['low_confidence'] += 1
                
                # Collect F1 scores for averaging
                if 'pathway_validation' in validation_results and 'f1_score' in validation_results['pathway_validation']:
                    pathway_f1_scores.append(validation_results['pathway_validation']['f1_score'])
                
                if 'mechanism_validation' in validation_results and 'f1_score' in validation_results['mechanism_validation']:
                    mechanism_f1_scores.append(validation_results['mechanism_validation']['f1_score'])
                    
            except Exception as e:
                print(f"Error validating {rec.get('ec_number')}: {e}")
                rec['validation_results'] = {'overall_confidence': 0.0, 'error': str(e)}

            # Calculate average F1 scores
            if pathway_f1_scores:
                validation_metrics['avg_pathway_f1'] = sum(pathway_f1_scores) / len(pathway_f1_scores)
            if mechanism_f1_scores:
                validation_metrics['avg_mechanism_f1'] = sum(mechanism_f1_scores) / len(mechanism_f1_scores)

            # 60. Show validation results
            if validation_issues:
                print("\nField Validation Issues:")
                for issue in validation_issues[:10]:
                    print(f"- {issue}")
                if len(validation_issues) > 10:
                    print(f"...and {len(validation_issues) - 10} more issues")
            else:
                print("\nField Validation: All records have essential fields.")

            # 61. Show content validation metrics
            print(f"\nContent Validation Metrics:")
            print(f"Total records validated: {validation_metrics['total_validated']}")
            print(f"High confidence (≥0.7): {validation_metrics['high_confidence']} ({validation_metrics['high_confidence']/validation_metrics['total_validated']*100:.1f}%)")
            print(f"Medium confidence (0.4-0.7): {validation_metrics['medium_confidence']} ({validation_metrics['medium_confidence']/validation_metrics['total_validated']*100:.1f}%)")
            print(f"Low confidence (<0.4): {validation_metrics['low_confidence']} ({validation_metrics['low_confidence']/validation_metrics['total_validated']*100:.1f}%)")
            print(f"Average pathway F1 score: {validation_metrics['avg_pathway_f1']:.3f}")
            print(f"Average mechanism F1 score: {validation_metrics['avg_mechanism_f1']:.3f}")


    return enriched_df'''

In [55]:
import time, json, pandas as pd, numpy as np

def enrich_eccontri_data(eccontri_df, ec_records_flat):
    """
    Enrich ECContri with metadata from ec_records_flat (new lean schema).
    - Keeps your numbered structure so patches are easy.
    - Priority: EC match → protein-name match vs enzyme_names (case-insensitive, partial).
    - Preserves original ECContri columns and appends selected metadata & scores.
    - Performs basic validation vs pathway_primary/react_primary.
    """

    # 0. Safety copies
    enriched_df = eccontri_df.copy()
    recs = list(ec_records_flat) if isinstance(ec_records_flat, list) else ec_records_flat.to_dict("records")

    # =========================
    # 1. Create lookup dicts
    # =========================
    print("Creating lookup dictionaries...")
    # 1a) EC dict (no 'EC:' prefix assumed)
    ec_dict = {}
    for r in recs:
        ec = str(r.get('ec', '')).strip()
        if ec:
            ec_dict[ec] = r
    print(f"[1] EC dictionary: {len(ec_dict)} entries")

    # 1b) Enzyme/protein name dictionary (lowercased)
    #     NEW: enzyme_names are lists; index them individually
    protein_name_dict = {}
    for r in recs:
        names = r.get('enzyme_names', [])
        if isinstance(names, str):
            names = [n.strip() for n in names.split(';') if n.strip()]
        elif not isinstance(names, (list, tuple)):
            names = []
        for nm in names:
            key = nm.strip().lower()
            if key:
                # keep first occurrence (stable)
                protein_name_dict.setdefault(key, r)
    print(f"[1] protein/enzyme name dictionary: {len(protein_name_dict)} entries")

    # =========================
    # 2. Prep output columns
    # =========================
    metadata_columns = [
        'ec_number','protein_name','enzyme_class','enzyme_names',
        'functional_combined','functional_sub','functional_child',
        'synergy_child','synergy_sub','synergy_combined',
        'consolidated_metals','pathways_db','reaction_db','hierarchy',
        'corrosion_mechanisms','operational_combi',
        'overall_functional_score','overall_metal_score',
        'overall_synergy_score','corrosion_relevance_score'
    ]
    for col in metadata_columns:
        if col not in enriched_df.columns:
            enriched_df[col] = None

    # =========================
    # 3. Progress controls
    # =========================
    total_rows = len(enriched_df)
    log_interval = max(1, min(10000, max(1, total_rows // 20)))
    print(f"[3] Processing {total_rows} rows, logging every {log_interval} rows")

    # =========================
    # 4. Row match map
    # =========================
    idx_to_metadata = {}

    # =========================
    # 5. Protein-name matches
    # =========================
    print("[5] Protein/enzyme name matches...")
    protein_matches = 0

    # normalize available name col
    name_col = 'protein_name' if 'protein_name' in enriched_df.columns else None
    if name_col is not None:
        # Skip rows already matched later by EC (we'll fill those after EC pass); here we just precompute candidates
        for i, row in enriched_df.iterrows():
            if i % log_interval == 0:
                print(f"  [5] row {i}/{total_rows} ({i/total_rows*100:.1f}%)")
            raw_name = str(row.get(name_col, '') or '').strip()
            if not raw_name or raw_name.lower() in {"uncharacterized protein","hypothetical protein","nan","none"}:
                continue
            key = raw_name.lower()
            # direct
            hit = protein_name_dict.get(key)
            if hit is None:
                # partial (one pass)
                for k, r in protein_name_dict.items():
                    if k in key or key in k:
                        hit = r
                        break
            if hit is not None:
                idx_to_metadata.setdefault(i, hit)
                protein_matches += 1
    print(f"[5] Found {protein_matches} protein/enzyme name matches")

    # =========================
    # 6. EC-only matches (PRIMARY)
    # =========================
    print("[6] EC-only matches...")
    ec_col = 'ec' if 'ec' in enriched_df.columns else ('EC' if 'EC' in enriched_df.columns else None)
    ec_only_matches = 0
    if ec_col is not None:
        for i, row in enriched_df.iterrows():
            if i % log_interval == 0:
                print(f"  [6] row {i}/{total_rows} ({i/total_rows*100:.1f}%)")
            if i in idx_to_metadata:
                continue
            ec = str(row.get(ec_col, '') or '').strip()
            if not ec:
                continue
            rec = ec_dict.get(ec)
            if rec is not None:
                idx_to_metadata[i] = rec
                ec_only_matches += 1
    print(f"[6] Found {ec_only_matches} EC-only matches")

    # =========================
    # 7. Apply metadata to matched rows
    # =========================
    print("[7] Applying metadata to matched rows...")
    applied = 0

    def _join_list(x):
        if isinstance(x, (list, tuple)):
            return '; '.join(str(v) for v in x if str(v).strip())
        return str(x) if x is not None else None

    for idx, meta in idx_to_metadata.items():
        if idx % log_interval == 0:
            print(f"  [7] row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")

        # 7a. set ec_number (echo) if present
        if meta.get('ec'):
            enriched_df.at[idx, 'ec'] = meta['ec']

        # 7b. protein_name fallback from enzyme_names when uncharacterized/empty
        pn = str(enriched_df.at[idx, 'protein_name']) if 'protein_name' in enriched_df.columns else ''
        if (not pn) or pn.lower() in {"uncharacterized protein","hypothetical protein","nan","none"}:
            ens = meta.get('enzyme_names', [])
            if isinstance(ens, (list, tuple)) and len(ens) > 0:
                enriched_df.at[idx, 'protein_name'] = ens[0]

        # 7c. assign core metadata (lists retained as lists)
        for fld in [
            'enzyme_names','enzyme_class','pathways_db','reaction_db','hierarchy',
            'corrosion_mechanisms','functional_combined','functional_sub','functional_child',
            'synergy_child','synergy_sub','synergy_combined','consolidated_metals',
            'operational_combi'
        ]:
            if fld in meta and meta[fld] is not None:
                enriched_df.at[idx, fld] = meta[fld]

        # 7d. numeric scores (new schema)
        for fld in ['overall_metal_score','overall_functional_score','overall_synergy_score','corrosion_relevance_score']:
            if fld in meta:
                try:
                    enriched_df.at[idx, fld] = float(meta.get(fld, 0))
                except Exception:
                    enriched_df.at[idx, fld] = None

        applied += 1
    print(f"[7] Applied metadata to {applied} rows")

    # =========================
    # 8. Scoring missing rows (lightweight)
    # =========================
    print("[8] Calculating scores for rows lacking scores...")
    scores_calc, scores_skip = 0, 0
    need_cols = ['overall_metal_score','overall_functional_score','overall_synergy_score','corrosion_relevance_score']
    has_cs = hasattr(cs, 'calculate_overall_scores') and hasattr(cs, 'calculate_corrosion_relevance_score')

    if has_cs:
        for i, row in enriched_df.iterrows():
            if i % log_interval == 0:
                print(f"  [8] row {i}/{total_rows} ({i/total_rows*100:.1f}%)")
            if all(pd.notna(row.get(c)) for c in need_cols):
                scores_skip += 1
                continue
            txt = ""
            pn = str(row.get('protein_name') or '').strip()
            if pn: txt += pn + " "
            ec_cl = str(row.get('enzyme_class') or '').strip()
            if ec_cl: txt += ec_cl + " "
            pws = row.get('pathways_db')
            if isinstance(pws, (list, tuple)) and pws:
                txt += "; ".join(map(str, pws)) + " "
            if not txt.strip():
                scores_skip += 1
                continue

            try:
                sr = cs.calculate_overall_scores(txt)
                # write back if present in columns
                if 'overall_metal_score' in enriched_df.columns:        enriched_df.at[i,'overall_metal_score']        = float(sr.get('overall_metal_score', 0))
                if 'overall_functional_score' in enriched_df.columns:   enriched_df.at[i,'overall_functional_score']   = float(sr.get('overall_functional_score', 0))
                if 'overall_synergy_score' in enriched_df.columns:      enriched_df.at[i,'overall_synergy_score']      = float(sr.get('overall_synergy_score', 0))

                crs, _crlabel = cs.calculate_corrosion_relevance_score(
                    sr.get('overall_metal_score', 0),
                    sr.get('overall_synergy_score', 0),
                    sr.get('overall_functional_score', 0)
                )
                if 'corrosion_relevance_score' in enriched_df.columns:
                    enriched_df.at[i,'corrosion_relevance_score'] = float(crs)
                scores_calc += 1
            except Exception as e:
                # keep silent but continue
                pass
    print(f"[8] Scoring done. Calculated: {scores_calc}, skipped: {scores_skip}")

    # =========================
    # 9. Validation vs pathway_primary/react_primary
    # =========================
    print("[9] Validation vs pathway_primary/react_primary...")
    def _norm_list(v):
        if isinstance(v, (list,tuple)):
            return [str(x).strip().lower() for x in v if str(x).strip()]
        if v is None or (isinstance(v,float) and pd.isna(v)):
            return []
        return [str(v).strip().lower()]

    # 9a) Pathway check
    if 'pathway_primary' in enriched_df.columns and 'pathways_db' in enriched_df.columns:
        lhs = enriched_df['pathway_primary'].astype(str).str.strip().str.lower()
        rhs = enriched_df['pathways_db'].apply(_norm_list)
        enriched_df['pathway_hit'] = [
            (p in r) or any(p in x for x in r) if p and r else False
            for p, r in zip(lhs, rhs)
        ]
    else:
        enriched_df['pathway_hit'] = False

    # 9b) Reaction check
    if 'react_primary' in enriched_df.columns and 'reaction_db' in enriched_df.columns:
        lhs = enriched_df['react_primary'].astype(str).str.strip().str.lower()
        rhs = enriched_df['reaction_db'].apply(_norm_list)
        enriched_df['reaction_hit'] = [
            (p in r) or any(p in x for x in r) if p and r else False
            for p, r in zip(lhs, rhs)
        ]
    else:
        enriched_df['reaction_hit'] = False

    # =========================
    # 10. Report
    # =========================
    print(f"[10] Enrichment complete for {total_rows} rows.")
    # success rates for added metadata
    meta_pop = {c: int(enriched_df[c].notna().sum()) for c in metadata_columns if c in enriched_df.columns}
    for k,v in meta_pop.items():
        print(f"   - {k}: {v} rows ({(v/total_rows*100):.1f}%)")
    print(f"   - pathway_hit rate: {enriched_df['pathway_hit'].mean():.3f}")
    print(f"   - reaction_hit rate: {enriched_df['reaction_hit'].mean():.3f}")

    # =========================
    # 11. Final column order
    # =========================
    base_cols = [c for c in ['idx','Sites','Genus','norm_abund_contri','protein_name','ec','Category','pathway_primary','react_primary'] if c in enriched_df.columns]
    meta_cols_present = [c for c in metadata_columns if c in enriched_df.columns]
    final_cols = base_cols + meta_cols_present + ['pathway_hit','reaction_hit']
    enriched_df = enriched_df.loc[:, final_cols].copy()

    return enriched_df

In [56]:
ECcontri_enriched_c, validation_summary = enrich_eccontri_data(pre_ECcontri_enriched, ec_record_flat)

Creating lookup dictionaries...
[1] EC dictionary: 1793 entries
[1] protein/enzyme name dictionary: 9599 entries
[3] Processing 1491288 rows, logging every 10000 rows
[5] Protein/enzyme name matches...
  [5] row 0/1491288 (0.0%)
  [5] row 10000/1491288 (0.7%)
  [5] row 20000/1491288 (1.3%)
  [5] row 30000/1491288 (2.0%)
  [5] row 40000/1491288 (2.7%)
  [5] row 50000/1491288 (3.4%)
  [5] row 60000/1491288 (4.0%)
  [5] row 70000/1491288 (4.7%)
  [5] row 80000/1491288 (5.4%)
  [5] row 90000/1491288 (6.0%)
  [5] row 100000/1491288 (6.7%)
  [5] row 110000/1491288 (7.4%)
  [5] row 120000/1491288 (8.0%)
  [5] row 130000/1491288 (8.7%)
  [5] row 140000/1491288 (9.4%)
  [5] row 150000/1491288 (10.1%)
  [5] row 160000/1491288 (10.7%)
  [5] row 170000/1491288 (11.4%)
  [5] row 180000/1491288 (12.1%)
  [5] row 190000/1491288 (12.7%)
  [5] row 200000/1491288 (13.4%)
  [5] row 210000/1491288 (14.1%)
  [5] row 220000/1491288 (14.8%)
  [5] row 230000/1491288 (15.4%)
  [5] row 240000/1491288 (16.1%)
  [5] row 250000/1491288 (16.8%)
  [5] row 260000/1491288 (17.4%)
  [5] row 270000/1491288 (18.1%)
  [5] row 280000/1491288 (18.8%)
  [5] row 290000/1491288 (19.4%)
  [5] row 300000/1491288 (20.1%)
  [5] row 310000/1491288 (20.8%)
  [5] row 320000/1491288 (21.5%)
  [5] row 330000/1491288 (22.1%)
  [5] row 340000/1491288 (22.8%)
  [5] row 350000/1491288 (23.5%)
  [5] row 360000/1491288 (24.1%)
  [5] row 370000/1491288 (24.8%)
  [5] row 380000/1491288 (25.5%)
  [5] row 390000/1491288 (26.2%)
  [5] row 400000/1491288 (26.8%)
  [5] row 410000/1491288 (27.5%)
  [5] row 420000/1491288 (28.2%)
  [5] row 430000/1491288 (28.8%)
  [5] row 440000/1491288 (29.5%)
  [5] row 450000/1491288 (30.2%)
  [5] row 460000/1491288 (30.8%)
  [5] row 470000/1491288 (31.5%)
  [5] row 480000/1491288 (32.2%)
  [5] row 490000/1491288 (32.9%)
  [5] row 500000/1491288 (33.5%)
  [5] row 510000/1491288 (34.2%)
  [5] row 520000/1491288 (34.9%)
  [5] row 530000/1491288 (35.5%)
  [5] row 540000/1491288 (36.2%)
  [5] row 550000/1491288 (36.9%)
  [5] row 560000/1491288 (37.6%)
  [5] row 570000/1491288 (38.2%)
  [5] row 580000/1491288 (38.9%)
  [5] row 590000/1491288 (39.6%)
  [5] row 600000/1491288 (40.2%)
  [5] row 610000/1491288 (40.9%)
  [5] row 620000/1491288 (41.6%)
  [5] row 630000/1491288 (42.2%)
  [5] row 640000/1491288 (42.9%)
  [5] row 650000/1491288 (43.6%)
  [5] row 660000/1491288 (44.3%)
  [5] row 670000/1491288 (44.9%)
  [5] row 680000/1491288 (45.6%)
  [5] row 690000/1491288 (46.3%)
  [5] row 700000/1491288 (46.9%)
  [5] row 710000/1491288 (47.6%)
  [5] row 720000/1491288 (48.3%)
  [5] row 730000/1491288 (49.0%)
  [5] row 740000/1491288 (49.6%)
  [5] row 750000/1491288 (50.3%)
  [5] row 760000/1491288 (51.0%)
  [5] row 770000/1491288 (51.6%)
  [5] row 780000/1491288 (52.3%)
  [5] row 790000/1491288 (53.0%)
  [5] row 800000/1491288 (53.6%)
  [5] row 810000/1491288 (54.3%)
  [5] row 820000/1491288 (55.0%)
  [5] row 830000/1491288 (55.7%)
  [5] row 840000/1491288 (56.3%)
  [5] row 850000/1491288 (57.0%)
  [5] row 860000/1491288 (57.7%)
  [5] row 870000/1491288 (58.3%)
  [5] row 880000/1491288 (59.0%)
  [5] row 890000/1491288 (59.7%)
  [5] row 900000/1491288 (60.4%)
  [5] row 910000/1491288 (61.0%)
  [5] row 920000/1491288 (61.7%)
  [5] row 930000/1491288 (62.4%)
  [5] row 940000/1491288 (63.0%)
  [5] row 950000/1491288 (63.7%)
  [5] row 960000/1491288 (64.4%)
  [5] row 970000/1491288 (65.0%)
  [5] row 980000/1491288 (65.7%)
  [5] row 990000/1491288 (66.4%)
  [5] row 1000000/1491288 (67.1%)
  [5] row 1010000/1491288 (67.7%)
  [5] row 1020000/1491288 (68.4%)
  [5] row 1030000/1491288 (69.1%)
  [5] row 1040000/1491288 (69.7%)
  [5] row 1050000/1491288 (70.4%)
  [5] row 1060000/1491288 (71.1%)
  [5] row 1070000/1491288 (71.8%)
  [5] row 1080000/1491288 (72.4%)
  [5] row 1090000/1491288 (73.1%)
  [5] row 1100000/1491288 (73.8%)
  [5] row 1110000/1491288 (74.4%)
  [5] row 1120000/1491288 (75.1%)
  [5] row 1130000/1491288 (75.8%)
  [5] row 1140000/1491288 (76.4%)
  [5] row 1150000/1491288 (77.1%)
  [5] row 1160000/1491288 (77.8%)
  [5] row 1170000/1491288 (78.5%)
  [5] row 1180000/1491288 (79.1%)
  [5] row 1190000/1491288 (79.8%)
  [5] row 1200000/1491288 (80.5%)
  [5] row 1210000/1491288 (81.1%)
  [5] row 1220000/1491288 (81.8%)
  [5] row 1230000/1491288 (82.5%)
  [5] row 1240000/1491288 (83.1%)
  [5] row 1250000/1491288 (83.8%)
  [5] row 1260000/1491288 (84.5%)
  [5] row 1270000/1491288 (85.2%)
  [5] row 1280000/1491288 (85.8%)
  [5] row 1290000/1491288 (86.5%)
  [5] row 1300000/1491288 (87.2%)
  [5] row 1310000/1491288 (87.8%)
  [5] row 1320000/1491288 (88.5%)
  [5] row 1330000/1491288 (89.2%)
  [5] row 1340000/1491288 (89.9%)
  [5] row 1350000/1491288 (90.5%)
  [5] row 1360000/1491288 (91.2%)
  [5] row 1370000/1491288 (91.9%)
  [5] row 1380000/1491288 (92.5%)
  [5] row 1390000/1491288 (93.2%)
  [5] row 1400000/1491288 (93.9%)
  [5] row 1410000/1491288 (94.5%)
  [5] row 1420000/1491288 (95.2%)
  [5] row 1430000/1491288 (95.9%)
  [5] row 1440000/1491288 (96.6%)
  [5] row 1450000/1491288 (97.2%)
  [5] row 1460000/1491288 (97.9%)
  [5] row 1470000/1491288 (98.6%)
  [5] row 1480000/1491288 (99.2%)
  [5] row 1490000/1491288 (99.9%)
[5] Found 1214036 protein/enzyme name matches
[6] EC-only matches...
  [6] row 0/1491288 (0.0%)
  [6] row 10000/1491288 (0.7%)
  [6] row 20000/1491288 (1.3%)
  [6] row 30000/1491288 (2.0%)
  [6] row 40000/1491288 (2.7%)
  [6] row 50000/1491288 (3.4%)
  [6] row 60000/1491288 (4.0%)
  [6] row 70000/1491288 (4.7%)
  [6] row 80000/1491288 (5.4%)
  [6] row 90000/1491288 (6.0%)
  [6] row 100000/1491288 (6.7%)
  [6] row 110000/1491288 (7.4%)
  [6] row 120000/1491288 (8.0%)
  [6] row 130000/1491288 (8.7%)
  [6] row 140000/1491288 (9.4%)
  [6] row 150000/1491288 (10.1%)
  [6] row 160000/1491288 (10.7%)
  [6] row 170000/1491288 (11.4%)
  [6] row 180000/1491288 (12.1%)
  [6] row 190000/1491288 (12.7%)
  [6] row 200000/1491288 (13.4%)
  [6] row 210000/1491288 (14.1%)
  [6] row 220000/1491288 (14.8%)
  [6] row 230000/1491288 (15.4%)
  [6] row 240000/1491288 (16.1%)
  [6] row 250000/1491288 (16.8%)
  [6] row 260000/1491288 (17.4%)
  [6] row 270000/1491288 (18.1%)
  [6] row 280000/1491288 (18.8%)
  [6] row 290000/1491288 (19.4%)
  [6] row 300000/1491288 (20.1%)
  [6] row 310000/1491288 (20.8%)
  [6] row 320000/1491288 (21.5%)
  [6] row 330000/1491288 (22.1%)
  [6] row 340000/1491288 (22.8%)
  [6] row 350000/1491288 (23.5%)
  [6] row 360000/1491288 (24.1%)
  [6] row 370000/1491288 (24.8%)
  [6] row 380000/1491288 (25.5%)
  [6] row 390000/1491288 (26.2%)
  [6] row 400000/1491288 (26.8%)
  [6] row 410000/1491288 (27.5%)
  [6] row 420000/1491288 (28.2%)
  [6] row 430000/1491288 (28.8%)
  [6] row 440000/1491288 (29.5%)
  [6] row 450000/1491288 (30.2%)
  [6] row 460000/1491288 (30.8%)
  [6] row 470000/1491288 (31.5%)
  [6] row 480000/1491288 (32.2%)
  [6] row 490000/1491288 (32.9%)
  [6] row 500000/1491288 (33.5%)
  [6] row 510000/1491288 (34.2%)
  [6] row 520000/1491288 (34.9%)
  [6] row 530000/1491288 (35.5%)
  [6] row 540000/1491288 (36.2%)
  [6] row 550000/1491288 (36.9%)
  [6] row 560000/1491288 (37.6%)
  [6] row 570000/1491288 (38.2%)
  [6] row 580000/1491288 (38.9%)
  [6] row 590000/1491288 (39.6%)
  [6] row 600000/1491288 (40.2%)
  [6] row 610000/1491288 (40.9%)
  [6] row 620000/1491288 (41.6%)
  [6] row 630000/1491288 (42.2%)
  [6] row 640000/1491288 (42.9%)
  [6] row 650000/1491288 (43.6%)
  [6] row 660000/1491288 (44.3%)
  [6] row 670000/1491288 (44.9%)
  [6] row 680000/1491288 (45.6%)
  [6] row 690000/1491288 (46.3%)
  [6] row 700000/1491288 (46.9%)
  [6] row 710000/1491288 (47.6%)
  [6] row 720000/1491288 (48.3%)
  [6] row 730000/1491288 (49.0%)
  [6] row 740000/1491288 (49.6%)
  [6] row 750000/1491288 (50.3%)
  [6] row 760000/1491288 (51.0%)
  [6] row 770000/1491288 (51.6%)
  [6] row 780000/1491288 (52.3%)
  [6] row 790000/1491288 (53.0%)
  [6] row 800000/1491288 (53.6%)
  [6] row 810000/1491288 (54.3%)
  [6] row 820000/1491288 (55.0%)
  [6] row 830000/1491288 (55.7%)
  [6] row 840000/1491288 (56.3%)
  [6] row 850000/1491288 (57.0%)
  [6] row 860000/1491288 (57.7%)
  [6] row 870000/1491288 (58.3%)
  [6] row 880000/1491288 (59.0%)
  [6] row 890000/1491288 (59.7%)
  [6] row 900000/1491288 (60.4%)
  [6] row 910000/1491288 (61.0%)
  [6] row 920000/1491288 (61.7%)
  [6] row 930000/1491288 (62.4%)
  [6] row 940000/1491288 (63.0%)
  [6] row 950000/1491288 (63.7%)
  [6] row 960000/1491288 (64.4%)
  [6] row 970000/1491288 (65.0%)
  [6] row 980000/1491288 (65.7%)
  [6] row 990000/1491288 (66.4%)
  [6] row 1000000/1491288 (67.1%)
  [6] row 1010000/1491288 (67.7%)
  [6] row 1020000/1491288 (68.4%)
  [6] row 1030000/1491288 (69.1%)
  [6] row 1040000/1491288 (69.7%)
  [6] row 1050000/1491288 (70.4%)
  [6] row 1060000/1491288 (71.1%)
  [6] row 1070000/1491288 (71.8%)
  [6] row 1080000/1491288 (72.4%)
  [6] row 1090000/1491288 (73.1%)
  [6] row 1100000/1491288 (73.8%)
  [6] row 1110000/1491288 (74.4%)
  [6] row 1120000/1491288 (75.1%)
  [6] row 1130000/1491288 (75.8%)
  [6] row 1140000/1491288 (76.4%)
  [6] row 1150000/1491288 (77.1%)
  [6] row 1160000/1491288 (77.8%)
  [6] row 1170000/1491288 (78.5%)
  [6] row 1180000/1491288 (79.1%)
  [6] row 1190000/1491288 (79.8%)
  [6] row 1200000/1491288 (80.5%)
  [6] row 1210000/1491288 (81.1%)
  [6] row 1220000/1491288 (81.8%)
  [6] row 1230000/1491288 (82.5%)
  [6] row 1240000/1491288 (83.1%)
  [6] row 1250000/1491288 (83.8%)
  [6] row 1260000/1491288 (84.5%)
  [6] row 1270000/1491288 (85.2%)
  [6] row 1280000/1491288 (85.8%)
  [6] row 1290000/1491288 (86.5%)
  [6] row 1300000/1491288 (87.2%)
  [6] row 1310000/1491288 (87.8%)
  [6] row 1320000/1491288 (88.5%)
  [6] row 1330000/1491288 (89.2%)
  [6] row 1340000/1491288 (89.9%)
  [6] row 1350000/1491288 (90.5%)
  [6] row 1360000/1491288 (91.2%)
  [6] row 1370000/1491288 (91.9%)
  [6] row 1380000/1491288 (92.5%)
  [6] row 1390000/1491288 (93.2%)
  [6] row 1400000/1491288 (93.9%)
  [6] row 1410000/1491288 (94.5%)
  [6] row 1420000/1491288 (95.2%)
  [6] row 1430000/1491288 (95.9%)
  [6] row 1440000/1491288 (96.6%)
  [6] row 1450000/1491288 (97.2%)
  [6] row 1460000/1491288 (97.9%)
  [6] row 1470000/1491288 (98.6%)
  [6] row 1480000/1491288 (99.2%)
  [6] row 1490000/1491288 (99.9%)
[6] Found 277252 EC-only matches
[7] Applying metadata to matched rows...
  [7] row 0/1491288 (0.0%)
  [7] row 10000/1491288 (0.7%)
  [7] row 20000/1491288 (1.3%)
  [7] row 30000/1491288 (2.0%)
  [7] row 60000/1491288 (4.0%)
  [7] row 70000/1491288 (4.7%)
  [7] row 80000/1491288 (5.4%)
  [7] row 90000/1491288 (6.0%)
  [7] row 100000/1491288 (6.7%)
  [7] row 110000/1491288 (7.4%)
  [7] row 120000/1491288 (8.0%)
  [7] row 150000/1491288 (10.1%)
  [7] row 160000/1491288 (10.7%)
  [7] row 170000/1491288 (11.4%)
  [7] row 180000/1491288 (12.1%)
  [7] row 190000/1491288 (12.7%)
  [7] row 200000/1491288 (13.4%)
  [7] row 220000/1491288 (14.8%)
  [7] row 230000/1491288 (15.4%)
  [7] row 240000/1491288 (16.1%)
  [7] row 250000/1491288 (16.8%)
  [7] row 260000/1491288 (17.4%)
  [7] row 270000/1491288 (18.1%)
  [7] row 280000/1491288 (18.8%)
  [7] row 290000/1491288 (19.4%)
  [7] row 310000/1491288 (20.8%)
  [7] row 320000/1491288 (21.5%)
  [7] row 330000/1491288 (22.1%)
  [7] row 340000/1491288 (22.8%)
  [7] row 350000/1491288 (23.5%)
  [7] row 360000/1491288 (24.1%)
  [7] row 380000/1491288 (25.5%)
  [7] row 390000/1491288 (26.2%)
  [7] row 400000/1491288 (26.8%)
  [7] row 410000/1491288 (27.5%)
  [7] row 420000/1491288 (28.2%)
  [7] row 430000/1491288 (28.8%)
  [7] row 440000/1491288 (29.5%)
  [7] row 450000/1491288 (30.2%)
  [7] row 460000/1491288 (30.8%)
  [7] row 470000/1491288 (31.5%)
  [7] row 480000/1491288 (32.2%)
  [7] row 490000/1491288 (32.9%)
  [7] row 500000/1491288 (33.5%)
  [7] row 520000/1491288 (34.9%)
  [7] row 530000/1491288 (35.5%)
  [7] row 540000/1491288 (36.2%)
  [7] row 550000/1491288 (36.9%)
  [7] row 560000/1491288 (37.6%)
  [7] row 570000/1491288 (38.2%)
  [7] row 580000/1491288 (38.9%)
  [7] row 600000/1491288 (40.2%)
  [7] row 610000/1491288 (40.9%)
  [7] row 630000/1491288 (42.2%)
  [7] row 640000/1491288 (42.9%)
  [7] row 650000/1491288 (43.6%)
  [7] row 660000/1491288 (44.3%)
  [7] row 670000/1491288 (44.9%)
  [7] row 680000/1491288 (45.6%)
  [7] row 690000/1491288 (46.3%)
  [7] row 700000/1491288 (46.9%)
  [7] row 710000/1491288 (47.6%)
  [7] row 720000/1491288 (48.3%)
  [7] row 730000/1491288 (49.0%)
  [7] row 740000/1491288 (49.6%)
  [7] row 750000/1491288 (50.3%)
  [7] row 770000/1491288 (51.6%)
  [7] row 780000/1491288 (52.3%)
  [7] row 790000/1491288 (53.0%)
  [7] row 800000/1491288 (53.6%)
  [7] row 820000/1491288 (55.0%)
  [7] row 840000/1491288 (56.3%)
  [7] row 850000/1491288 (57.0%)
  [7] row 860000/1491288 (57.7%)
  [7] row 870000/1491288 (58.3%)
  [7] row 880000/1491288 (59.0%)
  [7] row 890000/1491288 (59.7%)
  [7] row 920000/1491288 (61.7%)
  [7] row 930000/1491288 (62.4%)
  [7] row 940000/1491288 (63.0%)
  [7] row 950000/1491288 (63.7%)
  [7] row 970000/1491288 (65.0%)
  [7] row 990000/1491288 (66.4%)
  [7] row 1000000/1491288 (67.1%)
  [7] row 1010000/1491288 (67.7%)
  [7] row 1020000/1491288 (68.4%)
  [7] row 1030000/1491288 (69.1%)
  [7] row 1040000/1491288 (69.7%)
  [7] row 1050000/1491288 (70.4%)
  [7] row 1070000/1491288 (71.8%)
  [7] row 1080000/1491288 (72.4%)
  [7] row 1100000/1491288 (73.8%)
  [7] row 1110000/1491288 (74.4%)
  [7] row 1120000/1491288 (75.1%)
  [7] row 1130000/1491288 (75.8%)
  [7] row 1140000/1491288 (76.4%)
  [7] row 1170000/1491288 (78.5%)
  [7] row 1190000/1491288 (79.8%)
  [7] row 1200000/1491288 (80.5%)
  [7] row 1210000/1491288 (81.1%)
  [7] row 1220000/1491288 (81.8%)
  [7] row 1230000/1491288 (82.5%)
  [7] row 1240000/1491288 (83.1%)
  [7] row 1250000/1491288 (83.8%)
  [7] row 1260000/1491288 (84.5%)
  [7] row 1270000/1491288 (85.2%)
  [7] row 1290000/1491288 (86.5%)
  [7] row 1300000/1491288 (87.2%)
  [7] row 1310000/1491288 (87.8%)
  [7] row 1320000/1491288 (88.5%)
  [7] row 1330000/1491288 (89.2%)
  [7] row 1340000/1491288 (89.9%)
  [7] row 1360000/1491288 (91.2%)
  [7] row 1370000/1491288 (91.9%)
  [7] row 1380000/1491288 (92.5%)
  [7] row 1390000/1491288 (93.2%)
  [7] row 1400000/1491288 (93.9%)
  [7] row 1410000/1491288 (94.5%)
  [7] row 1420000/1491288 (95.2%)
  [7] row 1450000/1491288 (97.2%)
  [7] row 1460000/1491288 (97.9%)
  [7] row 1470000/1491288 (98.6%)
  [7] row 1480000/1491288 (99.2%)

TypeError: Cannot setitem on a Categorical with a new category (2-oxoacid oxidoreductase), set the categories first

In [ ]:
import pandas as pd
import time
import json

def _ensure_list(v):
    if v is None or (isinstance(v, float) and pd.isna(v)):
        return []
    if isinstance(v, (list, tuple)):
        return list(v)
    return [v]

def _first_scalar(value):
    """Return a scalar from value which may be list/tuple/string/None.
    Picks the first meaningful entry when list-like, else returns stringified scalar or None."""
    if value is None:
        return None
    if isinstance(value, (list, tuple)):
        for v in value:
            if v is None:
                continue
            s = str(v).strip()
            if s and s.lower() not in {'nan','none'}:
                return s
        return None
    s = str(value).strip()
    return s if s and s.lower() not in {'nan','none'} else None

def enrich_eccontri_data(
    eccontri_df, 
    ec_records_flat,
    pathways_primary_mapping=None,
    cs=None,
    meta_fields_to_copy=None,
    list_fields_to_explode=None,
    progress=True,
):
    """
    Enrich the ECcontri_Uniprot dataframe with complete information from ec_records dictionary
    and apply validation using pathways_primary and reaction_primary columns.
    Searches protein names, enzyme names and EC numbers from ec_records to enrich the original eccontri.
    Returns enriched_df with additional metadata columns and scoring applied, plus validation stats.
    """

    # 1. Make a copy to avoid modifying the original
    enriched_df = eccontri_df.copy()

    start_time = time.time()
    total_rows = len(enriched_df)

    # 2. Create dictionaries for faster lookups
    print("Creating lookup dictionaries...") if progress else None

    # 2a. EC number dictionary flatten
    ec_dict = {str(record['ec_number']).strip(): record for record in ec_records_flat if 'ec_number' in record and record['ec_number']}
    print(f"Created EC dictionary with {len(ec_dict)} entries") if progress else None

    # 2b. Protein name dictionary
    protein_name_dict = {}
    for record in ec_records_flat:
        enzyme_names_str = record.get('enzyme_names', '')
        if enzyme_names_str:
            # Handle both string and list formats
            if isinstance(enzyme_names_str, list):
                names = enzyme_names_str
            else:
                names = [name.strip() for name in str(enzyme_names_str).split(';')]
            for name in names:
                if name:
                    protein_name_dict[name.lower()] = record
    print(f"Created protein name dictionary with {len(protein_name_dict)} entries") if progress else None

    # 3. Create a mapping dictionary to store all matches
    idx_to_metadata = {}

    # 4. Metadata columns to copy (user can override defaults)
    if meta_fields_to_copy is None:
        meta_fields_to_copy = [
            'enzyme_class', 'functional_combined', 'functional_sub', 'functional_child',
            'synergy_child', 'synergy_sub', 'synergy_combined', 'consolidated_metals',
            'pathways_db', 'reaction_db', 'hierarchy', 'corrosion_mechanisms', 
            'operational_combi', 'overall_functional_score', 'overall_metal_score',
            'overall_synergy_score', 'corrosion_relevance_score'
        ]
    for col in meta_fields_to_copy:
        if col not in enriched_df.columns:
            enriched_df[col] = None

    # 5. List fields to explode (user can override defaults)
    if list_fields_to_explode is None:
        list_fields_to_explode = ['consolidated_metals', 'pathways_db', 'reaction_db']

    # 6. Progress reporting setup
    log_interval = max(1, min(10000, total_rows // 20)) if progress else total_rows

    # 7. Protein name matches
    print("Performing protein name matches...") if progress else None
    mask_valid_protein = enriched_df['protein_name'].notna() & (enriched_df['protein_name'].str.lower() != "uncharacterized protein")
    protein_matches = 0
    for idx in enriched_df.index[mask_valid_protein]:
        if progress and idx % log_interval == 0:
            print(f"Processing protein matches: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
        protein_name = enriched_df.loc[idx, 'protein_name']
        if not isinstance(protein_name, str):
            continue
        protein_name_lower = protein_name.lower()
        if protein_name_lower in protein_name_dict:
            idx_to_metadata[idx] = protein_name_dict[protein_name_lower]
            protein_matches += 1
        else:
            for name, record in protein_name_dict.items():
                if name in protein_name_lower or protein_name_lower in name:
                    idx_to_metadata[idx] = record
                    protein_matches += 1
                    break
    print(f"Found {protein_matches} protein name matches") if progress else None

    # 8. EC-only matches
    print("Performing EC-only matches...") if progress else None
    mask_valid_ec = enriched_df['ec'].notna()
    ec_only_matches = 0
    for idx in enriched_df.index[mask_valid_ec]:
        if idx in idx_to_metadata:
            continue
        if progress and idx % log_interval == 0:
            print(f"Processing EC matches: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
        ec_num = str(enriched_df.loc[idx, 'ec'])
        if ec_num in ec_dict:
            idx_to_metadata[idx] = ec_dict[ec_num]
            ec_only_matches += 1
    print(f"Found {ec_only_matches} EC-only matches") if progress else None

    # 9. Apply metadata to matched rows, inject lists for explode fields
    print("Applying metadata to matched rows...") if progress else None
    for idx, metadata in idx_to_metadata.items():
        if progress and idx % log_interval == 0:
            print(f"Applying metadata: row {idx}/{total_rows} ({idx/total_rows*100:.1f}%)")
        if metadata is not None:
            # Only copy metadata fields, skip core eccontri fields
            for field in meta_fields_to_copy:
                if field in metadata:
                    val = metadata[field]
                    # For fields to explode, inject as list
                    if field in list_fields_to_explode:
                        if isinstance(val, (list, tuple)):
                            enriched_df.at[idx, field] = list(val)
                        elif pd.isna(val) or val is None or val == '':
                            enriched_df.at[idx, field] = []
                        else:
                            enriched_df.at[idx, field] = [val]
                    else:
                        # For other fields, collapse list to string (but keep lists for scores if needed)
                        if isinstance(val, (list, tuple)):
                            enriched_df.at[idx, field] = '; '.join(str(v) for v in val if v is not None)
                        elif isinstance(val, dict):
                            enriched_df.at[idx, field] = json.dumps(val)
                        else:
                            enriched_df.at[idx, field] = str(val) if val is not None else None

    # 10. Explode DataFrame on list fields (multi-explode)
    long_df = enriched_df.copy()
    for col in list_fields_to_explode:
        if col in long_df.columns:
            long_df[col] = long_df[col].apply(lambda x: x if isinstance(x, (list, tuple)) else ([x] if x not in [None, '', float('nan')] else []))
            long_df = long_df.explode(col)

    # 11. Validation section (on the enriched records)
    print("Running enhanced validation...") if progress else None
    validation_issues = []
    validation_metrics = {
        'total_validated': 0,
        'high_confidence': 0,
        'medium_confidence': 0,
        'low_confidence': 0,
        'avg_pathway_f1': 0,
        'avg_mechanism_f1': 0
    }
    pathway_f1_scores = []
    mechanism_f1_scores = []

    # If cs and pathways_primary_mapping are available, run validation for each unique ec
    if cs is not None and pathways_primary_mapping is not None:
        unique_ecs = long_df['ec'].dropna().unique()
        for ec_num in unique_ecs:
            mask = long_df['ec'] == ec_num
            # Use the first row for validation context (or aggregate as needed)
            rec = long_df.loc[mask].iloc[0].to_dict()
            # Basic field validation
            if not rec.get('ec'):
                validation_issues.append(f"Record EC {ec_num} missing EC number")
            if not rec.get('protein_name'):
                validation_issues.append(f"EC {ec_num} missing protein name")
            # Content validation using validate_against_pathways
            try:
                validation_results = cs.validate_against_pathways(rec, pathways_primary_mapping)
                validation_metrics['total_validated'] += 1
                confidence = validation_results.get('overall_confidence', 0)
                long_df.loc[mask, 'validation_confidence'] = confidence
                # Categorize confidence levels
                if confidence >= 0.7:
                    validation_metrics['high_confidence'] += 1
                elif confidence >= 0.4:
                    validation_metrics['medium_confidence'] += 1
                else:
                    validation_metrics['low_confidence'] += 1
                # Collect F1 scores
                if 'pathway_validation' in validation_results and 'f1_score' in validation_results['pathway_validation']:
                    pathway_f1_scores.append(validation_results['pathway_validation']['f1_score'])
                    long_df.loc[mask, 'pathway_f1'] = validation_results['pathway_validation']['f1_score']
                if 'mechanism_validation' in validation_results and 'f1_score' in validation_results['mechanism_validation']:
                    mechanism_f1_scores.append(validation_results['mechanism_validation']['f1_score'])
                    long_df.loc[mask, 'mechanism_f1'] = validation_results['mechanism_validation']['f1_score']
            except Exception as e:
                validation_issues.append(f"Error validating {ec_num}: {e}")
                long_df.loc[mask, 'validation_confidence'] = 0.0

    # Calculate average F1 scores
    if pathway_f1_scores:
        validation_metrics['avg_pathway_f1'] = sum(pathway_f1_scores) / len(pathway_f1_scores)
    if mechanism_f1_scores:
        validation_metrics['avg_mechanism_f1'] = sum(mechanism_f1_scores) / len(mechanism_f1_scores)

    # 12. Print validation results
    print("\nField Validation Issues:") if progress and validation_issues else None
    for issue in validation_issues[:10]:
        print(f"- {issue}") if progress else None
    if progress and len(validation_issues) > 10:
        print(f"...and {len(validation_issues) - 10} more issues")
    print("\nContent Validation Metrics:") if progress else None
    print(f"Total records validated: {validation_metrics['total_validated']}") if progress else None
    print(f"High confidence (≥0.7): {validation_metrics['high_confidence']} ({validation_metrics['high_confidence']/validation_metrics['total_validated']*100:.1f}%)") if validation_metrics['total_validated'] else None
    print(f"Medium confidence (0.4-0.7): {validation_metrics['medium_confidence']} ({validation_metrics['medium_confidence']/validation_metrics['total_validated']*100:.1f}%)") if validation_metrics['total_validated'] else None
    print(f"Low confidence (<0.4): {validation_metrics['low_confidence']} ({validation_metrics['low_confidence']/validation_metrics['total_validated']*100:.1f}%)") if validation_metrics['total_validated'] else None
    print(f"Average pathway F1 score: {validation_metrics['avg_pathway_f1']:.3f}") if progress else None
    print(f"Average mechanism F1 score: {validation_metrics['avg_mechanism_f1']:.3f}") if progress else None

    # 13. Final report
    end_time = time.time()
    total_time = end_time - start_time
    print(f"\nCompleted enrichment in {total_time:.2f} seconds")
    print(f"Processed {total_rows} rows at {total_rows/total_time:.1f} rows/second")

    # 14. Metadata population statistics
    metadata_counts = {col: long_df[col].notnull().sum() for col in meta_fields_to_copy}
    print("\nMetadata population statistics:") if progress else None
    for col, count in metadata_counts.items():
        print(f"  {col}: {count} rows ({count/len(long_df)*100:.1f}%)") if progress else None

    return long_df.reset_index(drop=True)

In [57]:
long_enriched = enrich_eccontri_data(pre_ECcontri_enriched, ec_record_flat)

Creating lookup dictionaries...
[1] EC dictionary: 1793 entries
[1] protein/enzyme name dictionary: 9599 entries
[3] Processing 1491288 rows, logging every 10000 rows
[5] Protein/enzyme name matches...
  [5] row 0/1491288 (0.0%)
  [5] row 10000/1491288 (0.7%)
  [5] row 20000/1491288 (1.3%)
  [5] row 30000/1491288 (2.0%)
  [5] row 40000/1491288 (2.7%)
  [5] row 50000/1491288 (3.4%)
  [5] row 60000/1491288 (4.0%)
  [5] row 70000/1491288 (4.7%)
  [5] row 80000/1491288 (5.4%)
  [5] row 90000/1491288 (6.0%)
  [5] row 100000/1491288 (6.7%)
  [5] row 110000/1491288 (7.4%)
  [5] row 120000/1491288 (8.0%)
  [5] row 130000/1491288 (8.7%)
  [5] row 140000/1491288 (9.4%)
  [5] row 150000/1491288 (10.1%)
  [5] row 160000/1491288 (10.7%)
  [5] row 170000/1491288 (11.4%)
  [5] row 180000/1491288 (12.1%)
  [5] row 190000/1491288 (12.7%)
  [5] row 200000/1491288 (13.4%)
  [5] row 210000/1491288 (14.1%)
  [5] row 220000/1491288 (14.8%)
  [5] row 230000/1491288 (15.4%)
  [5] row 240000/1491288 (16.1%)
  [5] row 250000/1491288 (16.8%)
  [5] row 260000/1491288 (17.4%)
  [5] row 270000/1491288 (18.1%)
  [5] row 280000/1491288 (18.8%)
  [5] row 290000/1491288 (19.4%)
  [5] row 300000/1491288 (20.1%)
  [5] row 310000/1491288 (20.8%)
  [5] row 320000/1491288 (21.5%)
  [5] row 330000/1491288 (22.1%)
  [5] row 340000/1491288 (22.8%)
  [5] row 350000/1491288 (23.5%)
  [5] row 360000/1491288 (24.1%)
  [5] row 370000/1491288 (24.8%)
  [5] row 380000/1491288 (25.5%)
  [5] row 390000/1491288 (26.2%)
  [5] row 400000/1491288 (26.8%)
  [5] row 410000/1491288 (27.5%)
  [5] row 420000/1491288 (28.2%)
  [5] row 430000/1491288 (28.8%)
  [5] row 440000/1491288 (29.5%)
  [5] row 450000/1491288 (30.2%)
  [5] row 460000/1491288 (30.8%)
  [5] row 470000/1491288 (31.5%)
  [5] row 480000/1491288 (32.2%)
  [5] row 490000/1491288 (32.9%)
  [5] row 500000/1491288 (33.5%)
  [5] row 510000/1491288 (34.2%)
  [5] row 520000/1491288 (34.9%)
  [5] row 530000/1491288 (35.5%)
  [5] row 540000/1491288 (36.2%)
  [5] row 550000/1491288 (36.9%)
  [5] row 560000/1491288 (37.6%)
  [5] row 570000/1491288 (38.2%)
  [5] row 580000/1491288 (38.9%)
  [5] row 590000/1491288 (39.6%)
  [5] row 600000/1491288 (40.2%)
  [5] row 610000/1491288 (40.9%)
  [5] row 620000/1491288 (41.6%)
  [5] row 630000/1491288 (42.2%)
  [5] row 640000/1491288 (42.9%)
  [5] row 650000/1491288 (43.6%)
  [5] row 660000/1491288 (44.3%)
  [5] row 670000/1491288 (44.9%)
  [5] row 680000/1491288 (45.6%)
  [5] row 690000/1491288 (46.3%)
  [5] row 700000/1491288 (46.9%)
  [5] row 710000/1491288 (47.6%)
  [5] row 720000/1491288 (48.3%)
  [5] row 730000/1491288 (49.0%)
  [5] row 740000/1491288 (49.6%)
  [5] row 750000/1491288 (50.3%)
  [5] row 760000/1491288 (51.0%)
  [5] row 770000/1491288 (51.6%)
  [5] row 780000/1491288 (52.3%)
  [5] row 790000/1491288 (53.0%)
  [5] row 800000/1491288 (53.6%)
  [5] row 810000/1491288 (54.3%)
  [5] row 820000/1491288 (55.0%)
  [5] row 830000/1491288 (55.7%)
  [5] row 840000/1491288 (56.3%)
  [5] row 850000/1491288 (57.0%)
  [5] row 860000/1491288 (57.7%)
  [5] row 870000/1491288 (58.3%)
  [5] row 880000/1491288 (59.0%)
  [5] row 890000/1491288 (59.7%)
  [5] row 900000/1491288 (60.4%)
  [5] row 910000/1491288 (61.0%)
  [5] row 920000/1491288 (61.7%)
  [5] row 930000/1491288 (62.4%)
  [5] row 940000/1491288 (63.0%)
  [5] row 950000/1491288 (63.7%)
  [5] row 960000/1491288 (64.4%)
  [5] row 970000/1491288 (65.0%)
  [5] row 980000/1491288 (65.7%)
  [5] row 990000/1491288 (66.4%)
  [5] row 1000000/1491288 (67.1%)
  [5] row 1010000/1491288 (67.7%)
  [5] row 1020000/1491288 (68.4%)
  [5] row 1030000/1491288 (69.1%)
  [5] row 1040000/1491288 (69.7%)
  [5] row 1050000/1491288 (70.4%)
  [5] row 1060000/1491288 (71.1%)
  [5] row 1070000/1491288 (71.8%)
  [5] row 1080000/1491288 (72.4%)
  [5] row 1090000/1491288 (73.1%)
  [5] row 1100000/1491288 (73.8%)
  [5] row 1110000/1491288 (74.4%)
  [5] row 1120000/1491288 (75.1%)
  [5] row 1130000/1491288 (75.8%)
  [5] row 1140000/1491288 (76.4%)
  [5] row 1150000/1491288 (77.1%)
  [5] row 1160000/1491288 (77.8%)
  [5] row 1170000/1491288 (78.5%)
  [5] row 1180000/1491288 (79.1%)
  [5] row 1190000/1491288 (79.8%)
  [5] row 1200000/1491288 (80.5%)
  [5] row 1210000/1491288 (81.1%)
  [5] row 1220000/1491288 (81.8%)
  [5] row 1230000/1491288 (82.5%)
  [5] row 1240000/1491288 (83.1%)
  [5] row 1250000/1491288 (83.8%)
  [5] row 1260000/1491288 (84.5%)
  [5] row 1270000/1491288 (85.2%)
  [5] row 1280000/1491288 (85.8%)
  [5] row 1290000/1491288 (86.5%)
  [5] row 1300000/1491288 (87.2%)
  [5] row 1310000/1491288 (87.8%)
  [5] row 1320000/1491288 (88.5%)
  [5] row 1330000/1491288 (89.2%)
  [5] row 1340000/1491288 (89.9%)
  [5] row 1350000/1491288 (90.5%)
  [5] row 1360000/1491288 (91.2%)
  [5] row 1370000/1491288 (91.9%)
  [5] row 1380000/1491288 (92.5%)
  [5] row 1390000/1491288 (93.2%)
  [5] row 1400000/1491288 (93.9%)
  [5] row 1410000/1491288 (94.5%)
  [5] row 1420000/1491288 (95.2%)
  [5] row 1430000/1491288 (95.9%)
  [5] row 1440000/1491288 (96.6%)
  [5] row 1450000/1491288 (97.2%)
  [5] row 1460000/1491288 (97.9%)
  [5] row 1470000/1491288 (98.6%)
  [5] row 1480000/1491288 (99.2%)
  [5] row 1490000/1491288 (99.9%)
[5] Found 1214036 protein/enzyme name matches
[6] EC-only matches...
  [6] row 0/1491288 (0.0%)
  [6] row 10000/1491288 (0.7%)
  [6] row 20000/1491288 (1.3%)
  [6] row 30000/1491288 (2.0%)
  [6] row 40000/1491288 (2.7%)
  [6] row 50000/1491288 (3.4%)
  [6] row 60000/1491288 (4.0%)
  [6] row 70000/1491288 (4.7%)
  [6] row 80000/1491288 (5.4%)
  [6] row 90000/1491288 (6.0%)
  [6] row 100000/1491288 (6.7%)
  [6] row 110000/1491288 (7.4%)
  [6] row 120000/1491288 (8.0%)
  [6] row 130000/1491288 (8.7%)
  [6] row 140000/1491288 (9.4%)
  [6] row 150000/1491288 (10.1%)
  [6] row 160000/1491288 (10.7%)
  [6] row 170000/1491288 (11.4%)
  [6] row 180000/1491288 (12.1%)
  [6] row 190000/1491288 (12.7%)
  [6] row 200000/1491288 (13.4%)
  [6] row 210000/1491288 (14.1%)
  [6] row 220000/1491288 (14.8%)
  [6] row 230000/1491288 (15.4%)
  [6] row 240000/1491288 (16.1%)
  [6] row 250000/1491288 (16.8%)
  [6] row 260000/1491288 (17.4%)
  [6] row 270000/1491288 (18.1%)
  [6] row 280000/1491288 (18.8%)
  [6] row 290000/1491288 (19.4%)
  [6] row 300000/1491288 (20.1%)
  [6] row 310000/1491288 (20.8%)
  [6] row 320000/1491288 (21.5%)
  [6] row 330000/1491288 (22.1%)
  [6] row 340000/1491288 (22.8%)
  [6] row 350000/1491288 (23.5%)
  [6] row 360000/1491288 (24.1%)
  [6] row 370000/1491288 (24.8%)
  [6] row 380000/1491288 (25.5%)
  [6] row 390000/1491288 (26.2%)
  [6] row 400000/1491288 (26.8%)
  [6] row 410000/1491288 (27.5%)
  [6] row 420000/1491288 (28.2%)
  [6] row 430000/1491288 (28.8%)
  [6] row 440000/1491288 (29.5%)
  [6] row 450000/1491288 (30.2%)
  [6] row 460000/1491288 (30.8%)
  [6] row 470000/1491288 (31.5%)
  [6] row 480000/1491288 (32.2%)
  [6] row 490000/1491288 (32.9%)
  [6] row 500000/1491288 (33.5%)
  [6] row 510000/1491288 (34.2%)
  [6] row 520000/1491288 (34.9%)
  [6] row 530000/1491288 (35.5%)
  [6] row 540000/1491288 (36.2%)
  [6] row 550000/1491288 (36.9%)
  [6] row 560000/1491288 (37.6%)
  [6] row 570000/1491288 (38.2%)
  [6] row 580000/1491288 (38.9%)
  [6] row 590000/1491288 (39.6%)
  [6] row 600000/1491288 (40.2%)
  [6] row 610000/1491288 (40.9%)
  [6] row 620000/1491288 (41.6%)
  [6] row 630000/1491288 (42.2%)
  [6] row 640000/1491288 (42.9%)
  [6] row 650000/1491288 (43.6%)
  [6] row 660000/1491288 (44.3%)
  [6] row 670000/1491288 (44.9%)
  [6] row 680000/1491288 (45.6%)
  [6] row 690000/1491288 (46.3%)
  [6] row 700000/1491288 (46.9%)
  [6] row 710000/1491288 (47.6%)
  [6] row 720000/1491288 (48.3%)
  [6] row 730000/1491288 (49.0%)
  [6] row 740000/1491288 (49.6%)
  [6] row 750000/1491288 (50.3%)
  [6] row 760000/1491288 (51.0%)
  [6] row 770000/1491288 (51.6%)
  [6] row 780000/1491288 (52.3%)
  [6] row 790000/1491288 (53.0%)
  [6] row 800000/1491288 (53.6%)
  [6] row 810000/1491288 (54.3%)
  [6] row 820000/1491288 (55.0%)
  [6] row 830000/1491288 (55.7%)
  [6] row 840000/1491288 (56.3%)
  [6] row 850000/1491288 (57.0%)
  [6] row 860000/1491288 (57.7%)
  [6] row 870000/1491288 (58.3%)
  [6] row 880000/1491288 (59.0%)
  [6] row 890000/1491288 (59.7%)
  [6] row 900000/1491288 (60.4%)
  [6] row 910000/1491288 (61.0%)
  [6] row 920000/1491288 (61.7%)
  [6] row 930000/1491288 (62.4%)
  [6] row 940000/1491288 (63.0%)
  [6] row 950000/1491288 (63.7%)
  [6] row 960000/1491288 (64.4%)
  [6] row 970000/1491288 (65.0%)
  [6] row 980000/1491288 (65.7%)
  [6] row 990000/1491288 (66.4%)
  [6] row 1000000/1491288 (67.1%)
  [6] row 1010000/1491288 (67.7%)
  [6] row 1020000/1491288 (68.4%)
  [6] row 1030000/1491288 (69.1%)
  [6] row 1040000/1491288 (69.7%)
  [6] row 1050000/1491288 (70.4%)
  [6] row 1060000/1491288 (71.1%)
  [6] row 1070000/1491288 (71.8%)
  [6] row 1080000/1491288 (72.4%)
  [6] row 1090000/1491288 (73.1%)
  [6] row 1100000/1491288 (73.8%)
  [6] row 1110000/1491288 (74.4%)
  [6] row 1120000/1491288 (75.1%)
  [6] row 1130000/1491288 (75.8%)
  [6] row 1140000/1491288 (76.4%)
  [6] row 1150000/1491288 (77.1%)
  [6] row 1160000/1491288 (77.8%)
  [6] row 1170000/1491288 (78.5%)
  [6] row 1180000/1491288 (79.1%)
  [6] row 1190000/1491288 (79.8%)
  [6] row 1200000/1491288 (80.5%)
  [6] row 1210000/1491288 (81.1%)
  [6] row 1220000/1491288 (81.8%)
  [6] row 1230000/1491288 (82.5%)
  [6] row 1240000/1491288 (83.1%)
  [6] row 1250000/1491288 (83.8%)
  [6] row 1260000/1491288 (84.5%)
  [6] row 1270000/1491288 (85.2%)
  [6] row 1280000/1491288 (85.8%)
  [6] row 1290000/1491288 (86.5%)
  [6] row 1300000/1491288 (87.2%)
  [6] row 1310000/1491288 (87.8%)
  [6] row 1320000/1491288 (88.5%)
  [6] row 1330000/1491288 (89.2%)
  [6] row 1340000/1491288 (89.9%)
  [6] row 1350000/1491288 (90.5%)
  [6] row 1360000/1491288 (91.2%)
  [6] row 1370000/1491288 (91.9%)
  [6] row 1380000/1491288 (92.5%)
  [6] row 1390000/1491288 (93.2%)
  [6] row 1400000/1491288 (93.9%)
  [6] row 1410000/1491288 (94.5%)
  [6] row 1420000/1491288 (95.2%)
  [6] row 1430000/1491288 (95.9%)
  [6] row 1440000/1491288 (96.6%)
  [6] row 1450000/1491288 (97.2%)
  [6] row 1460000/1491288 (97.9%)
  [6] row 1470000/1491288 (98.6%)
  [6] row 1480000/1491288 (99.2%)
  [6] row 1490000/1491288 (99.9%)
[6] Found 277252 EC-only matches
[7] Applying metadata to matched rows...
  [7] row 0/1491288 (0.0%)
  [7] row 10000/1491288 (0.7%)
  [7] row 20000/1491288 (1.3%)
  [7] row 30000/1491288 (2.0%)
  [7] row 60000/1491288 (4.0%)
  [7] row 70000/1491288 (4.7%)
  [7] row 80000/1491288 (5.4%)
  [7] row 90000/1491288 (6.0%)
  [7] row 100000/1491288 (6.7%)
  [7] row 110000/1491288 (7.4%)
  [7] row 120000/1491288 (8.0%)
  [7] row 150000/1491288 (10.1%)
  [7] row 160000/1491288 (10.7%)
  [7] row 170000/1491288 (11.4%)
  [7] row 180000/1491288 (12.1%)
  [7] row 190000/1491288 (12.7%)
  [7] row 200000/1491288 (13.4%)
  [7] row 220000/1491288 (14.8%)
  [7] row 230000/1491288 (15.4%)
  [7] row 240000/1491288 (16.1%)
  [7] row 250000/1491288 (16.8%)
  [7] row 260000/1491288 (17.4%)
  [7] row 270000/1491288 (18.1%)
  [7] row 280000/1491288 (18.8%)
  [7] row 290000/1491288 (19.4%)
  [7] row 310000/1491288 (20.8%)
  [7] row 320000/1491288 (21.5%)
  [7] row 330000/1491288 (22.1%)
  [7] row 340000/1491288 (22.8%)
  [7] row 350000/1491288 (23.5%)
  [7] row 360000/1491288 (24.1%)
  [7] row 380000/1491288 (25.5%)
  [7] row 390000/1491288 (26.2%)
  [7] row 400000/1491288 (26.8%)
  [7] row 410000/1491288 (27.5%)
  [7] row 420000/1491288 (28.2%)
  [7] row 430000/1491288 (28.8%)
  [7] row 440000/1491288 (29.5%)
  [7] row 450000/1491288 (30.2%)
  [7] row 460000/1491288 (30.8%)
  [7] row 470000/1491288 (31.5%)
  [7] row 480000/1491288 (32.2%)
  [7] row 490000/1491288 (32.9%)
  [7] row 500000/1491288 (33.5%)
  [7] row 520000/1491288 (34.9%)
  [7] row 530000/1491288 (35.5%)
  [7] row 540000/1491288 (36.2%)
  [7] row 550000/1491288 (36.9%)
  [7] row 560000/1491288 (37.6%)
  [7] row 570000/1491288 (38.2%)
  [7] row 580000/1491288 (38.9%)
  [7] row 600000/1491288 (40.2%)
  [7] row 610000/1491288 (40.9%)
  [7] row 630000/1491288 (42.2%)
  [7] row 640000/1491288 (42.9%)
  [7] row 650000/1491288 (43.6%)
  [7] row 660000/1491288 (44.3%)
  [7] row 670000/1491288 (44.9%)
  [7] row 680000/1491288 (45.6%)
  [7] row 690000/1491288 (46.3%)
  [7] row 700000/1491288 (46.9%)
  [7] row 710000/1491288 (47.6%)
  [7] row 720000/1491288 (48.3%)
  [7] row 730000/1491288 (49.0%)
  [7] row 740000/1491288 (49.6%)
  [7] row 750000/1491288 (50.3%)
  [7] row 770000/1491288 (51.6%)
  [7] row 780000/1491288 (52.3%)
  [7] row 790000/1491288 (53.0%)
  [7] row 800000/1491288 (53.6%)
  [7] row 820000/1491288 (55.0%)
  [7] row 840000/1491288 (56.3%)
  [7] row 850000/1491288 (57.0%)
  [7] row 860000/1491288 (57.7%)
  [7] row 870000/1491288 (58.3%)
  [7] row 880000/1491288 (59.0%)
  [7] row 890000/1491288 (59.7%)
  [7] row 920000/1491288 (61.7%)
  [7] row 930000/1491288 (62.4%)
  [7] row 940000/1491288 (63.0%)
  [7] row 950000/1491288 (63.7%)
  [7] row 970000/1491288 (65.0%)
  [7] row 990000/1491288 (66.4%)
  [7] row 1000000/1491288 (67.1%)
  [7] row 1010000/1491288 (67.7%)
  [7] row 1020000/1491288 (68.4%)
  [7] row 1030000/1491288 (69.1%)
  [7] row 1040000/1491288 (69.7%)
  [7] row 1050000/1491288 (70.4%)
  [7] row 1070000/1491288 (71.8%)
  [7] row 1080000/1491288 (72.4%)
  [7] row 1100000/1491288 (73.8%)
  [7] row 1110000/1491288 (74.4%)
  [7] row 1120000/1491288 (75.1%)
  [7] row 1130000/1491288 (75.8%)
  [7] row 1140000/1491288 (76.4%)
  [7] row 1170000/1491288 (78.5%)
  [7] row 1190000/1491288 (79.8%)
  [7] row 1200000/1491288 (80.5%)
  [7] row 1210000/1491288 (81.1%)
  [7] row 1220000/1491288 (81.8%)
  [7] row 1230000/1491288 (82.5%)
  [7] row 1240000/1491288 (83.1%)
  [7] row 1250000/1491288 (83.8%)
  [7] row 1260000/1491288 (84.5%)
  [7] row 1270000/1491288 (85.2%)
  [7] row 1290000/1491288 (86.5%)
  [7] row 1300000/1491288 (87.2%)
  [7] row 1310000/1491288 (87.8%)
  [7] row 1320000/1491288 (88.5%)
  [7] row 1330000/1491288 (89.2%)
  [7] row 1340000/1491288 (89.9%)
  [7] row 1360000/1491288 (91.2%)
  [7] row 1370000/1491288 (91.9%)
  [7] row 1380000/1491288 (92.5%)
  [7] row 1390000/1491288 (93.2%)
  [7] row 1400000/1491288 (93.9%)
  [7] row 1410000/1491288 (94.5%)
  [7] row 1420000/1491288 (95.2%)
  [7] row 1450000/1491288 (97.2%)
  [7] row 1460000/1491288 (97.9%)
  [7] row 1470000/1491288 (98.6%)
  [7] row 1480000/1491288 (99.2%)

TypeError: Cannot setitem on a Categorical with a new category (2-oxoacid oxidoreductase), set the categories first

____________________
## Ocurrencies after enrichment
___________________

In [ ]:
# Count occurrences of each value in both columns
enzyme_counts = ECcontri_enriched['enzyme_names'].explode().value_counts()
protein_counts = ECcontri_enriched['protein_name'].value_counts()
ec_counts = ECcontri_enriched['ec_number'].value_counts()
# Get the number of unique values in each column
enzyme_unique_count = ECcontri_enriched['enzyme_names'].explode().nunique()
protein_unique_count = ECcontri_enriched['protein_name'].nunique()
ec_unique_count = ECcontri_enriched['ec_number'].nunique()

# Print the results
print("EC Numbers - Unique Values:", ec_unique_count)
print("\nProtein Names - Unique Values:", protein_unique_count)
print("Protein Names - Top 5 Occurrences:\n", protein_counts.head())
print("\nEnzyme Names - Unique Values:", enzyme_unique_count)
print("Enzyme Names - Top 5 Occurrences:\n", enzyme_counts.head())